/** Props applied to the root form element. */
export interface FormElementProps {
  /** DOM id for the form element. */
  readonly id: string;
  /** Submission URL. */
  readonly action: string;
  /** HTTP method used by the form. */
  readonly method: string;
  /** Disable native browser validation when framework validation owns errors. */
  readonly noValidate: boolean;
}

/** Props for the hidden CSRF token input. */
export interface FormCsrfInputProps {
  /** Hidden input type. */
  readonly type: 'hidden';
  /** CSRF field name. */
  readonly name: string;
  /** CSRF token value. */
  readonly value: string;
}

/** Props for a hidden collection-key input. */
export interface CollectionKeyInputProps {
  /** Hidden input type. */
  readonly type: 'hidden';
  /** Collection key field name. */
  readonly name: string;
  /** Stable collection item key. */
  readonly value: string;
  /** Owning form id. */
  readonly form: string;
}

/** Props applied to a field label. */
export interface LabelProps {
  /** DOM id of the labelled control. */
  readonly for: string;
}

/** Props applied to a field error element. */
export interface ErrorProps {
  /** DOM id for the error element. */
  readonly id: string;
  /** Alert role used by assistive technologies. */
  readonly role: 'alert';
  /** Live-region behavior for updated errors. */
  readonly 'aria-live': 'polite';
}

/** Props applied to a field description element. */
export interface DescriptionProps {
  /** DOM id for the description element. */
  readonly id: string;
}

/** Props applied to an input, select, textarea, or compatible control. */
export interface ControlProps {
  /** DOM id for the control. */
  readonly id: string;
  /** Submitted field name. */
  readonly name: string;
  /** Owning form id. */
  readonly form: string;
  /** Initial string value. */
  readonly defaultValue?: string;
  /** Initial checked state. */
  readonly defaultChecked?: boolean;
  /** Controlled string value. */
  readonly value?: string;
  /** Controlled checked state. */
  readonly checked?: boolean;
  /** Whether the control currently has validation errors. */
  readonly 'aria-invalid'?: boolean;
  /** Space-separated ids describing the control. */
  readonly 'aria-describedby'?: string;
  /** Whether the field is required for assistive technologies. */
  readonly 'aria-required'?: boolean;
  /** Native required constraint. */
  readonly required?: boolean;
  /** Native minimum string length. */
  readonly minLength?: number;
  /** Native maximum string length. */
  readonly maxLength?: number;
  /** Native minimum value. */
  readonly min?: number | string;
  /** Native maximum value. */
  readonly max?: number | string;
  /** Native pattern constraint. */
  readonly pattern?: string;
  /** Native step constraint. */
  readonly step?: number | string;
  /** Native multiple-value flag. */
  readonly multiple?: boolean;
  /** Override form validation for this control. */
  readonly formNoValidate?: boolean;
  /** Input type when rendered as an input element. */
  readonly type?: string;
  /** Disabled control state. */
  readonly disabled?: boolean;
  /** Read-only control state. */
  readonly readOnly?: boolean;
  /** Placeholder text. */
  readonly placeholder?: string;
  /** Input mode hint. */
  readonly inputMode?: string;
  /** Textarea row count. */
  readonly rows?: number;
  /** Textarea column count. */
  readonly cols?: number;
  /** Autocomplete hint. */
  readonly autocomplete?: string;
  /** Spellcheck hint. */
  readonly spellCheck?: boolean;
  /** Accepted file types for file inputs. */
  readonly accept?: string;
  /** Submitter-specific action URL. */
  readonly formAction?: string;
  /** Submitter-specific method. */
  readonly formMethod?: string;
  /** Submitter-specific target. */
  readonly formTarget?: string;
  /** Submitter-specific encoding. */
  readonly formEncType?: string;
  /** Submitter-specific validation override. */
  readonly formNoValidateButton?: boolean;
  /** Associated datalist id. */
  readonly list?: string;
  /** Optional ARIA role. */
  readonly role?: string;
  /** Optional tab order. */
  readonly tabIndex?: number;
  /** Field path diagnostic marker. */
  readonly 'data-field-path'?: string;
  /** Field validity diagnostic marker. */
  readonly 'data-field-invalid'?: 'true' | 'false';
  /** Field dirtiness diagnostic marker. */
  readonly 'data-field-dirty'?: 'true' | 'false';
  /** Owning form diagnostic marker. */
  readonly 'data-form-id'?: string;
  /** Submit intent diagnostic marker. */
  readonly 'data-intent'?: string;
  /** Collection name diagnostic marker. */
  readonly 'data-collection-name'?: string;
  /** Collection index diagnostic marker. */
  readonly 'data-collection-index'?: string;
}

/** Props for an intent submit button generated by a form field helper. */
export interface IntentButtonProps {
  /** Submit button type. */
  readonly type: 'submit';
  /** Hidden intent field name. */
  readonly name: '__intent__';
  /** Encoded intent value. */
  readonly value: string;
  /** Disable native validation for intent-only operations. */
  readonly formNoValidate: boolean;
  /** Intent diagnostic marker. */
  readonly 'data-intent': string;
  /** Collection name diagnostic marker. */
  readonly 'data-collection-name'?: string;
  /** Collection index diagnostic marker. */
  readonly 'data-collection-index'?: string;
}

/** Form element props after progressive enhancement handlers are attached. */
export interface EnhancedFormProps extends FormElementProps {
  /** Fresh client-navigation flag. */
  readonly 'f-client-nav'?: boolean;
  /** Fresh partial route name. */
  readonly 'f-partial'?: string;
  /** Enhanced submit handler. */
  readonly onSubmit?: (event: Event) => void;
  /** Enhanced blur-capture handler. */
  readonly onBlurCapture?: (event: FocusEvent) => void;
  /** Enhanced input-capture handler. */
  readonly onInputCapture?: (event: Event) => void;
  /** Form element ref callback. */
  readonly ref?: (element: HTMLFormElement | null) => void;
}
