import { join } from '@std/path';

export interface MilestoneClusterStateView {
  readonly milestone?: unknown;
  readonly updatedAt?: unknown;
  readonly currentMainSha?: unknown;
  readonly lanes?: unknown;
  readonly leaves?: unknown;
  readonly expensiveGates?: unknown;
  readonly canaryCheckpoints?: unknown;
  readonly releaseCaptain?: unknown;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function stableValue(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stableValue);
  if (!isRecord(value)) return value;
  return Object.fromEntries(
    Object.keys(value).sort().map((key) => [key, stableValue(value[key])]),
  );
}

export async function stateDigest(state: unknown): Promise<string> {
  const bytes = new TextEncoder().encode(JSON.stringify(stableValue(state)));
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
}

function text(value: unknown, fallback = '—'): string {
  return typeof value === 'string' && value.length > 0 ? value : fallback;
}

function records(value: unknown): Record<string, unknown>[] {
  return Array.isArray(value) ? value.filter(isRecord) : [];
}

export async function renderMilestoneStatus(state: MilestoneClusterStateView): Promise<string> {
  const digest = await stateDigest(state);
  const lanes = records(state.lanes);
  const leaves = records(state.leaves);
  const gates = records(state.expensiveGates);
  const checkpoints = records(state.canaryCheckpoints);
  const captain = isRecord(state.releaseCaptain) ? state.releaseCaptain : {};

  const lines = [
    '<!-- Generated by .llm/tools/harness/render-milestone-status.ts. Do not edit. -->',
    `<!-- milestone-cluster-state-sha256: ${digest} -->`,
    '',
    `# Milestone ${text(state.milestone)} cluster status`,
    '',
    `- Updated: ${text(state.updatedAt)}`,
    `- Current main: \`${text(state.currentMainSha)}\``,
    `- Release captain: ${text(captain.state, 'inactive')}`,
    '',
    '## Topic lanes',
    '',
    '| Lane | Orchestrator | Issues | Active implementation | Active evaluation |',
    '| --- | --- | ---: | ---: | ---: |',
  ];

  for (const lane of lanes) {
    const laneId = text(lane.id);
    const issueCount = Array.isArray(lane.issueNumbers) ? lane.issueNumbers.length : 0;
    const laneLeaves = leaves.filter((leaf) => leaf.lane === lane.id);
    const implementationCount = laneLeaves.filter((leaf) =>
      leaf.phase === 'implementing' || leaf.phase === 'gating'
    ).length;
    const evaluationCount = laneLeaves.filter((leaf) => leaf.phase === 'evaluating').length;
    lines.push(
      `| ${laneId} | ${
        text(lane.orchestratorAgentId)
      } | ${issueCount} | ${implementationCount} | ${evaluationCount} |`,
    );
  }

  lines.push('', '## Leaves', '');
  if (leaves.length === 0) {
    lines.push('_No leaf PRs dispatched._');
  } else {
    lines.push('| PR | Lane | Phase | Head | Blocker |', '| --- | --- | --- | --- | --- |');
    for (const leaf of leaves) {
      const pr = typeof leaf.prNumber === 'number' ? `#${leaf.prNumber}` : '—';
      lines.push(
        `| ${pr} | ${text(leaf.lane)} | ${text(leaf.phase)} | \`${text(leaf.headSha)}\` | ${
          text(leaf.blocker)
        } |`,
      );
    }
  }

  const runningGates = gates.filter((gate) => gate.state === 'running').length;
  lines.push(
    '',
    '## Release train',
    '',
    `- Global expensive gates running: ${runningGates}`,
    `- Canary checkpoints: ${checkpoints.length}`,
    `- Release writer: ${text(captain.agentId)}`,
    '',
  );
  return `${lines.join('\n')}\n`;
}

export interface RenderCliArgs {
  readonly runDir?: string;
  readonly check: boolean;
  readonly error?: string;
}

/** Parse both direct invocation and `deno task ... -- <run-dir>` arguments. */
export function parseRenderCliArgs(args: readonly string[]): RenderCliArgs {
  let runDir: string | undefined;
  let check = false;
  for (const arg of args) {
    if (arg === '--') continue;
    if (arg === '--check') {
      check = true;
      continue;
    }
    if (arg.startsWith('-')) return { check, error: `unknown option: ${arg}` };
    if (runDir) return { check, error: 'expected exactly one run directory' };
    runDir = arg;
  }
  if (!runDir) return { check, error: 'missing run directory' };
  return { runDir, check };
}

async function main(): Promise<void> {
  const parsed = parseRenderCliArgs(Deno.args);
  if (!parsed.runDir || parsed.error) {
    if (parsed.error) console.error(`error: ${parsed.error}`);
    console.error('usage: render-milestone-status.ts <run-dir> [--check]');
    Deno.exit(2);
  }

  const runDir = parsed.runDir;
  const statePath = join(runDir, 'milestone-cluster-state.json');
  const statusPath = join(runDir, 'milestone-status.md');
  let rendered: string;
  try {
    const state = JSON.parse(await Deno.readTextFile(statePath)) as MilestoneClusterStateView;
    rendered = await renderMilestoneStatus(state);
  } catch (error) {
    console.error(
      `error: unable to render milestone status: ${
        error instanceof Error ? error.message : String(error)
      }`,
    );
    Deno.exit(1);
  }

  if (parsed.check) {
    let current = '';
    try {
      current = await Deno.readTextFile(statusPath);
    } catch (error) {
      if (!(error instanceof Deno.errors.NotFound)) throw error;
    }
    if (current !== rendered) {
      console.error(`stale or missing generated status: ${statusPath}`);
      Deno.exit(1);
    }
    console.log(`current: ${statusPath}`);
    return;
  }

  await Deno.writeTextFile(statusPath, rendered);
  console.log(`rendered: ${statusPath}`);
}

if (import.meta.main) await main();
