// register-background.mts — GENERATED BY @netscript/cli. DO NOT EDIT.
// Re-run `netscript generate` to regenerate after config changes.

import type { DistributedApplicationBuilder } from '../.aspire/modules/aspire.mts';
import { OtlpProtocol } from '../.aspire/modules/aspire.mts';
import type { NetScriptConfig } from './_aspire-compat.mts';
import type { InfrastructureContext } from './register-infrastructure.mts';
import {
  buildDatabaseProviderEnvVars,
  buildDatabaseUriEnvKey,
  buildOtelEnvVars,
  buildSqliteDatabaseUrl,
  resolvePermissions,
  resolveWorkspacePath,
  withCacheReference as _withCacheReference,
} from './_aspire-compat.mts';

type ExecutableResource = ReturnType<DistributedApplicationBuilder['addExecutable']>;

/**
 * Registers background processors (workers, sagas, triggers, benchmark)
 * with the Aspire SDK builder.
 *
 * Each processor is registered via `addExecutable()` from the Aspire SDK.
 * Telemetry-enabled entries receive the full executable OTEL env set;
 * telemetry-disabled entries receive explicit opt-out vars.
 *
 * Background processors do not cross-reference each other, so no two-pass
 * registration is needed.
 *
 * @param builder - The Aspire distributed application builder
 * @param config - Parsed NetScript configuration
 * @param infrastructure - Infrastructure context with database/cache resources
 * @param services - Map of registered service resources (for endpoint-based env var wiring)
 * @param plugins - Map of registered plugin resources (for endpoint-based env var wiring)
 * @param appHostDir - Absolute path to the AppHost directory
 * @returns Map of registered background processor resources keyed by name
 */
export async function registerBackgroundProcessors(
  builder: DistributedApplicationBuilder,
  config: NetScriptConfig,
  infrastructure: InfrastructureContext,
  _services: Map<string, ExecutableResource>,
  _plugins: Map<string, ExecutableResource>,
  appHostDir: string,
): Promise<Map<string, ExecutableResource>> {
  const backgroundProcessors = new Map<string, ExecutableResource>();
  const databaseEnvKey = buildDatabaseUriEnvKey(config);
  const databaseProviderEnv = buildDatabaseProviderEnvVars(config);

  // --- sagas ---
  if (config.BackgroundProcessors['sagas']?.Enabled !== false) {
    const sagas_perms = resolvePermissions(
      ['--unstable-kv', '--allow-all'],
      ['--allow-net', '--allow-env', '--allow-read', '--allow-sys'],
      true,
      '--watch',
    );
    const sagas_workdir = resolveWorkspacePath(appHostDir, '.');
    const sagas_bootstrapModule =
      new URL('../../services/_shared/plugin-service-context.ts', import.meta.url).href;
    const sagas = builder.addExecutable('sagas', 'deno', sagas_workdir, [
      'run',
      '--minimum-dependency-age=0',
      '--node-modules-dir=none',
      '--unstable-worker-options',
      ...sagas_perms,
      'sagas/runtime.ts',
    ]);

    // Saga supervisor health endpoint and real Aspire probe.
    await sagas.withHttpEndpoint({ env: 'PORT' });
    await sagas.withHttpHealthCheck({ path: '/health', endpointName: 'http' });
    await sagas.withEnvironment('NETSCRIPT_PLUGIN_SERVICE_BOOTSTRAP_MODULE', sagas_bootstrapModule);
    await sagas.withEnvironment('NETSCRIPT_SAGA_STORE', 'kv');

    // OTEL telemetry (full executable env set)
    const sagas_otel = buildOtelEnvVars('sagas', config.Version, 'executable');
    for (const [key, value] of Object.entries(sagas_otel)) {
      await sagas.withEnvironment(key, value);
    }
    await sagas.withOtlpExporter({ protocol: OtlpProtocol.HttpProtobuf });

    // Concurrency
    await sagas.withEnvironment('SAGA_CONCURRENCY', String(2));

    // Database dependency
    for (const [key, value] of Object.entries(databaseProviderEnv)) {
      await sagas.withEnvironment(key, value);
    }
    const sagas_sqliteDatabase = config.PrimaryDatabase
      ? config.Databases[config.PrimaryDatabase]
      : undefined;
    if (sagas_sqliteDatabase?.Engine === 'Sqlite' && config.PrimaryDatabase) {
      const sagas_sqliteUrl = buildSqliteDatabaseUrl(
        appHostDir,
        config.PrimaryDatabase,
        sagas_sqliteDatabase.DatabaseName ?? `${config.PrimaryDatabase}.db`,
      );
      await sagas.withEnvironment('DATABASE_URL', sagas_sqliteUrl);
      if (databaseEnvKey) {
        await sagas.withEnvironment(databaseEnvKey, sagas_sqliteUrl);
      }
    } else if (infrastructure.primaryDatabase) {
      let sagas_databaseBinding = sagas.withEnvironment(
        'DATABASE_URL',
        infrastructure.primaryDatabase,
      );
      if (databaseEnvKey) {
        sagas_databaseBinding = sagas_databaseBinding.withEnvironment(
          databaseEnvKey,
          infrastructure.primaryDatabase,
        );
      }
      await sagas_databaseBinding
        .withReference(infrastructure.primaryDatabase)
        .waitFor(infrastructure.primaryDatabase);
    }

    // KV cache dependency
    await _withCacheReference(sagas, infrastructure.primaryCacheWiring);

    // Plugin references — wired via endpoint env vars
    {
      const sagas_apiEndpoint = await _plugins.get('sagas-api')?.getEndpoint('http');
      if (sagas_apiEndpoint) {
        await sagas.withEnvironment('services__sagas-api__http__0', sagas_apiEndpoint);
      }
    }
    {
      const streamsEndpoint = await _plugins.get('streams')?.getEndpoint('http');
      if (streamsEndpoint) {
        await sagas.withEnvironment('services__streams__http__0', streamsEndpoint);
      }
    }
    {
      const workers_apiEndpoint = await _plugins.get('workers-api')?.getEndpoint('http');
      if (workers_apiEndpoint) {
        await sagas.withEnvironment('services__workers-api__http__0', workers_apiEndpoint);
      }
    }

    backgroundProcessors.set('sagas', sagas);
  }

  // --- triggers ---
  if (config.BackgroundProcessors['triggers']?.Enabled !== false) {
    const triggers_perms = resolvePermissions(
      ['--unstable-kv', '--allow-all'],
      ['--allow-net', '--allow-env', '--allow-read', '--allow-sys'],
      true,
      '--watch',
    );
    const triggers_workdir = resolveWorkspacePath(appHostDir, '.');
    const triggers_bootstrapModule =
      new URL('../../services/_shared/plugin-service-context.ts', import.meta.url).href;
    const triggers = builder.addExecutable('triggers', 'deno', triggers_workdir, [
      'run',
      '--minimum-dependency-age=0',
      '--node-modules-dir=none',
      '--unstable-worker-options',
      ...triggers_perms,
      'triggers/runtime.ts',
    ]);
    await triggers.withEnvironment(
      'NETSCRIPT_PLUGIN_SERVICE_BOOTSTRAP_MODULE',
      triggers_bootstrapModule,
    );
    const triggers_triggerRegistryModule =
      new URL('../../.netscript/generated/plugin-triggers/triggers.registry.ts', import.meta.url)
        .href;
    await triggers.withEnvironment(
      'NETSCRIPT_TRIGGER_REGISTRY_MODULE',
      triggers_triggerRegistryModule,
    );

    // OTEL telemetry (full executable env set)
    const triggers_otel = buildOtelEnvVars('triggers', config.Version, 'executable');
    for (const [key, value] of Object.entries(triggers_otel)) {
      await triggers.withEnvironment(key, value);
    }
    await triggers.withOtlpExporter({ protocol: OtlpProtocol.HttpProtobuf });

    // Concurrency
    await triggers.withEnvironment('TRIGGER_CONCURRENCY', String(10));

    // Database dependency
    for (const [key, value] of Object.entries(databaseProviderEnv)) {
      await triggers.withEnvironment(key, value);
    }
    const triggers_sqliteDatabase = config.PrimaryDatabase
      ? config.Databases[config.PrimaryDatabase]
      : undefined;
    if (triggers_sqliteDatabase?.Engine === 'Sqlite' && config.PrimaryDatabase) {
      const triggers_sqliteUrl = buildSqliteDatabaseUrl(
        appHostDir,
        config.PrimaryDatabase,
        triggers_sqliteDatabase.DatabaseName ?? `${config.PrimaryDatabase}.db`,
      );
      await triggers.withEnvironment('DATABASE_URL', triggers_sqliteUrl);
      if (databaseEnvKey) {
        await triggers.withEnvironment(databaseEnvKey, triggers_sqliteUrl);
      }
    } else if (infrastructure.primaryDatabase) {
      let triggers_databaseBinding = triggers.withEnvironment(
        'DATABASE_URL',
        infrastructure.primaryDatabase,
      );
      if (databaseEnvKey) {
        triggers_databaseBinding = triggers_databaseBinding.withEnvironment(
          databaseEnvKey,
          infrastructure.primaryDatabase,
        );
      }
      await triggers_databaseBinding
        .withReference(infrastructure.primaryDatabase)
        .waitFor(infrastructure.primaryDatabase);
    }

    // KV cache dependency
    await _withCacheReference(triggers, infrastructure.primaryCacheWiring);

    // Service references — wired via endpoint env vars
    {
      const ghost_serviceEndpoint = await _services.get('ghost-service')?.getEndpoint('http');
      if (ghost_serviceEndpoint) {
        await triggers.withEnvironment('services__ghost-service__http__0', ghost_serviceEndpoint);
      }
    }

    // Plugin references — wired via endpoint env vars
    {
      const streamsEndpoint = await _plugins.get('streams')?.getEndpoint('http');
      if (streamsEndpoint) {
        await triggers.withEnvironment('services__streams__http__0', streamsEndpoint);
      }
    }
    {
      const triggers_apiEndpoint = await _plugins.get('triggers-api')?.getEndpoint('http');
      if (triggers_apiEndpoint) {
        await triggers.withEnvironment('services__triggers-api__http__0', triggers_apiEndpoint);
      }
    }
    {
      const workers_apiEndpoint = await _plugins.get('workers-api')?.getEndpoint('http');
      if (workers_apiEndpoint) {
        await triggers.withEnvironment('services__workers-api__http__0', workers_apiEndpoint);
      }
    }

    backgroundProcessors.set('triggers', triggers);
  }

  // --- workers ---
  if (config.BackgroundProcessors['workers']?.Enabled !== false) {
    const workers_perms = resolvePermissions(
      [
        '--unstable-kv',
        '--allow-net',
        '--allow-env',
        '--allow-read',
        '--allow-write',
        '--allow-run',
        '--allow-ffi',
      ],
      ['--allow-net', '--allow-env', '--allow-read', '--allow-sys'],
      true,
      '--watch',
    );
    const workers_workdir = resolveWorkspacePath(appHostDir, '.');
    const workers_bootstrapModule =
      new URL('../../services/_shared/plugin-service-context.ts', import.meta.url).href;
    const workers = builder.addExecutable('workers', 'deno', workers_workdir, [
      'run',
      '--minimum-dependency-age=0',
      '--node-modules-dir=none',
      '--unstable-worker-options',
      ...workers_perms,
      'workers/runtime.ts',
    ]);
    await workers.withEnvironment(
      'NETSCRIPT_PLUGIN_SERVICE_BOOTSTRAP_MODULE',
      workers_bootstrapModule,
    );

    // OTEL telemetry (full executable env set)
    const workers_otel = buildOtelEnvVars('workers', config.Version, 'executable');
    for (const [key, value] of Object.entries(workers_otel)) {
      await workers.withEnvironment(key, value);
    }
    await workers.withOtlpExporter({ protocol: OtlpProtocol.HttpProtobuf });

    // Concurrency
    await workers.withEnvironment('WORKER_CONCURRENCY', String(2));

    // Database dependency
    for (const [key, value] of Object.entries(databaseProviderEnv)) {
      await workers.withEnvironment(key, value);
    }
    const workers_sqliteDatabase = config.PrimaryDatabase
      ? config.Databases[config.PrimaryDatabase]
      : undefined;
    if (workers_sqliteDatabase?.Engine === 'Sqlite' && config.PrimaryDatabase) {
      const workers_sqliteUrl = buildSqliteDatabaseUrl(
        appHostDir,
        config.PrimaryDatabase,
        workers_sqliteDatabase.DatabaseName ?? `${config.PrimaryDatabase}.db`,
      );
      await workers.withEnvironment('DATABASE_URL', workers_sqliteUrl);
      if (databaseEnvKey) {
        await workers.withEnvironment(databaseEnvKey, workers_sqliteUrl);
      }
    } else if (infrastructure.primaryDatabase) {
      let workers_databaseBinding = workers.withEnvironment(
        'DATABASE_URL',
        infrastructure.primaryDatabase,
      );
      if (databaseEnvKey) {
        workers_databaseBinding = workers_databaseBinding.withEnvironment(
          databaseEnvKey,
          infrastructure.primaryDatabase,
        );
      }
      await workers_databaseBinding
        .withReference(infrastructure.primaryDatabase)
        .waitFor(infrastructure.primaryDatabase);
    }

    // KV cache dependency
    await _withCacheReference(workers, infrastructure.primaryCacheWiring);

    // Service references — wired via endpoint env vars
    {
      const usersEndpoint = await _services.get('users')?.getEndpoint('http');
      if (usersEndpoint) {
        await workers.withEnvironment('services__users__http__0', usersEndpoint);
      }
    }

    // Plugin references — wired via endpoint env vars
    {
      const streamsEndpoint = await _plugins.get('streams')?.getEndpoint('http');
      if (streamsEndpoint) {
        await workers.withEnvironment('services__streams__http__0', streamsEndpoint);
      }
    }
    {
      const workers_apiEndpoint = await _plugins.get('workers-api')?.getEndpoint('http');
      if (workers_apiEndpoint) {
        await workers.withEnvironment('services__workers-api__http__0', workers_apiEndpoint);
      }
    }

    backgroundProcessors.set('workers', workers);
  }

  return backgroundProcessors;
}
