import { GATE, GATE_PHASE } from '../../../domain/cli-surface.ts';
import type { GateDefinition } from '../../../domain/gate-definition.ts';
import { commandGate } from './gate-factory.ts';

const WEBHOOK_URL = 'http://127.0.0.1:8093/api/v1/webhooks/inbound/generic';
const LEGACY_DASHBOARD_TRACES_URL = 'https://localhost:18888/api/telemetry/traces';

export function createOtelGates(): readonly GateDefinition[] {
  return [
    commandGate(
      GATE.BEHAVIOR_OTEL_WEBHOOK,
      'Fire webhook for OTEL trace capture',
      GATE_PHASE.BEHAVIOR,
      () => [
        'curl',
        '-sf',
        '-X',
        'POST',
        WEBHOOK_URL,
        '-H',
        'Content-Type: application/json',
        '-d',
        JSON.stringify({
          message: 'e2e-otel-gate',
          timestamp: new Date().toISOString(),
        }),
      ],
    ),
    commandGate(
      GATE.BEHAVIOR_OTEL_TRACES,
      'Validate OTEL trace chain via Dashboard API',
      GATE_PHASE.BEHAVIOR,
      (context) => [
        'deno',
        'eval',
        '--unsafely-ignore-certificate-errors=localhost',
        VALIDATE_TRACES_SCRIPT,
        '--',
        context.project.appHost,
        context.project.projectRoot,
      ],
      undefined,
      'capture',
      'No OTEL traces found. Ensure the AppHost was started with --isolated and the dashboard telemetry API is reachable.',
    ),
  ];
}

const VALIDATE_TRACES_SCRIPT = resolveValidateTracesScript();

function resolveValidateTracesScript(): string {
  return [
    'const appHost = Deno.args[0];',
    'const projectRoot = Deno.args[1];',
    'const MAX_ATTEMPTS = 30;',
    'const DELAY_MS = 2000;',
    'let cachedStartMetadata: StartMetadata | undefined;',
    'let otlpChecked = false;',
    'let loggedEndpoints = false;',
    '',
    'interface StartMetadata { dashboardUrl?: string; logFile?: string; }',
    '',
    'async function resolveDashboardBaseUrl(): Promise<string> {',
    '  const metadata = await readStartMetadata();',
    '  if (metadata?.dashboardUrl) return new URL(metadata.dashboardUrl).origin;',
    '  if (!appHost) return new URL("/", "' + LEGACY_DASHBOARD_TRACES_URL + '").origin;',
    '  try {',
    '    const command = new Deno.Command("aspire", {',
    '      args: ["ps", "--format", "Json", "--non-interactive", "--nologo"],',
    '      stdout: "piped",',
    '      stderr: "piped",',
    '    });',
    '    const output = await command.output();',
    '    if (!output.success) return new URL("/", "' + LEGACY_DASHBOARD_TRACES_URL + '").origin;',
    '    const stdout = new TextDecoder().decode(output.stdout);',
    '    const parsed = JSON.parse(extractJson(stdout));',
    '    const appHostRecord = findAppHostRecord(parsed, appHost);',
    '    const urls = collectUrls(appHostRecord ?? parsed);',
    '    const dashboardUrl = urls.find((url) => url.protocol === "https:" && !url.pathname.includes("/api/"));',
    '    return dashboardUrl?.origin ?? new URL("/", "' + LEGACY_DASHBOARD_TRACES_URL +
    '").origin;',
    '  } catch {',
    '    return new URL("/", "' + LEGACY_DASHBOARD_TRACES_URL + '").origin;',
    '  }',
    '}',
    '',
    'async function readStartMetadata(): Promise<StartMetadata | undefined> {',
    '  if (cachedStartMetadata) return cachedStartMetadata;',
    '  if (!projectRoot) return undefined;',
    '  try {',
    '    const text = await Deno.readTextFile(`${projectRoot}/.netscript/e2e/aspire-start.json`);',
    '    cachedStartMetadata = JSON.parse(text) as StartMetadata;',
    '    return cachedStartMetadata;',
    '  } catch {',
    '    return undefined;',
    '  }',
    '}',
    '',
    'async function resolveOtlpHttpEndpoint(): Promise<string | undefined> {',
    '  const metadata = await readStartMetadata();',
    '  if (!metadata?.logFile) return undefined;',
    '  try {',
    '    const text = await Deno.readTextFile(metadata.logFile);',
    '    const matches = [...text.matchAll(/OTLP\\/HTTP:\\s+(https?:\\/\\/\\S+)/g)];',
    '    return matches.at(-1)?.[1];',
    '  } catch {',
    '    return undefined;',
    '  }',
    '}',
    '',
    'async function validateOtlpExporterEndpoint(): Promise<void> {',
    '  if (otlpChecked) return;',
    '  otlpChecked = true;',
    '  const otlpEndpoint = await resolveOtlpHttpEndpoint();',
    '  if (!otlpEndpoint || !appHost) return;',
    '  try {',
    '    const command = new Deno.Command("aspire", {',
    '      args: ["describe", "--apphost", appHost, "--format", "Json"],',
    '      stdout: "piped",',
    '      stderr: "piped",',
    '    });',
    '    const output = await command.output();',
    '    if (!output.success) return;',
    '    const topology = JSON.parse(extractJson(new TextDecoder().decode(output.stdout)));',
    '    const exporters = collectOtelExporterEndpoints(topology);',
    '    if (exporters.length === 0) return;',
    '    const mismatched = exporters.filter((value) => value !== otlpEndpoint);',
    '    if (mismatched.length > 0) {',
    '      throw new Error(`OTLP exporter mismatch: dashboard ${otlpEndpoint}, resources ${[...new Set(mismatched)].join(", ")}`);',
    '    }',
    '    globalThis["console"].log(`OTLP exporter endpoint matches dashboard collector: ${otlpEndpoint}`);',
    '  } catch (error) {',
    '    if (error instanceof Error && error.message.startsWith("OTLP exporter mismatch:")) throw error;',
    '  }',
    '}',
    '',
    'async function fetchTraces(): Promise<unknown> {',
    '  const dashboardBaseUrl = await resolveDashboardBaseUrl();',
    '  const otlpEndpoint = await resolveOtlpHttpEndpoint();',
    '  if (!loggedEndpoints) {',
    '    globalThis["console"].log(`dashboard API: ${dashboardBaseUrl}`);',
    '    if (otlpEndpoint) globalThis["console"].log(`dashboard OTLP/HTTP: ${otlpEndpoint}`);',
    '    loggedEndpoints = true;',
    '  }',
    '  await validateOtlpExporterEndpoint();',
    '  const tracesUrl = new URL("/api/telemetry/traces", dashboardBaseUrl).toString();',
    '  const resp = await fetch(tracesUrl, {',
    '    headers: { Accept: "application/json" },',
    '  });',
    '  if (!resp.ok) throw new Error("Dashboard API " + resp.status);',
    '  return resp.json();',
    '}',
    '',
    'function extractJson(text: string): string {',
    '  const trimmed = text.trim();',
    '  if (trimmed.startsWith("{") || trimmed.startsWith("[")) return trimmed;',
    '  const objectIndex = trimmed.indexOf("{");',
    '  const arrayIndex = trimmed.indexOf("[");',
    '  const indexes = [objectIndex, arrayIndex].filter((index) => index >= 0);',
    '  if (indexes.length === 0) throw new Error("aspire ps did not emit JSON");',
    '  return trimmed.slice(Math.min(...indexes));',
    '}',
    '',
    'function findAppHostRecord(value: unknown, expectedPath: string): unknown {',
    '  if (!isRecord(value)) return undefined;',
    '  const values = Object.values(value);',
    '  if (values.some((candidate) => typeof candidate === "string" && candidate === expectedPath)) return value;',
    '  for (const child of values) {',
    '    if (Array.isArray(child)) {',
    '      for (const item of child) {',
    '        const match = findAppHostRecord(item, expectedPath);',
    '        if (match) return match;',
    '      }',
    '      continue;',
    '    }',
    '    const match = findAppHostRecord(child, expectedPath);',
    '    if (match) return match;',
    '  }',
    '  return undefined;',
    '}',
    '',
    'function collectUrls(value: unknown): URL[] {',
    '  const urls: URL[] = [];',
    '  collectUrlValues(value, urls);',
    '  return urls;',
    '}',
    '',
    'function collectUrlValues(value: unknown, urls: URL[]): void {',
    '  if (typeof value === "string") {',
    '    if (!/^https?:\\/\\//i.test(value)) return;',
    '    try { urls.push(new URL(value)); } catch { /* ignore non-URL strings */ }',
    '    return;',
    '  }',
    '  if (Array.isArray(value)) {',
    '    for (const item of value) collectUrlValues(item, urls);',
    '    return;',
    '  }',
    '  if (!isRecord(value)) return;',
    '  for (const child of Object.values(value)) collectUrlValues(child, urls);',
    '}',
    '',
    'function collectOtelExporterEndpoints(value: unknown): string[] {',
    '  const endpoints: string[] = [];',
    '  collectOtelExporterEndpointValues(value, endpoints);',
    '  return endpoints;',
    '}',
    '',
    'function collectOtelExporterEndpointValues(value: unknown, endpoints: string[]): void {',
    '  if (Array.isArray(value)) {',
    '    for (const item of value) collectOtelExporterEndpointValues(item, endpoints);',
    '    return;',
    '  }',
    '  if (!isRecord(value)) return;',
    '  const env = value.environment;',
    '  if (isRecord(env) && typeof env.OTEL_EXPORTER_OTLP_ENDPOINT === "string") {',
    '    endpoints.push(env.OTEL_EXPORTER_OTLP_ENDPOINT);',
    '  }',
    '  for (const child of Object.values(value)) collectOtelExporterEndpointValues(child, endpoints);',
    '}',
    '',
    'function isRecord(value: unknown): value is Record<string, unknown> {',
    '  return typeof value === "object" && value !== null && !Array.isArray(value);',
    '}',
    '',
    'interface Span { name: string; kind: number; traceId: string; spanId: string; parentSpanId: string; }',
    'interface ScopeSpans { scope: { name: string }; spans: Span[]; }',
    'interface Resource { attributes: { key: string; value: { stringValue: string } }[]; }',
    'interface ResourceSpans { scopeSpans: ScopeSpans[]; resource: Resource; }',
    'interface TraceResponse { data: { resourceSpans: ResourceSpans[] }; totalCount: number; }',
    '',
    'function getServiceName(r: Resource): string {',
    '  return (r.attributes.find(a => a.key === "service.name")?.value.stringValue) ?? "unknown";',
    '}',
    '',
    'let foundTrace = false;',
    '',
    'for (let attempt = 1; attempt <= MAX_ATTEMPTS && !foundTrace; attempt++) {',
    '  if (attempt > 1) await new Promise(r => setTimeout(r, DELAY_MS));',
    '  try {',
    '    const data = await fetchTraces() as TraceResponse;',
    '    const rs = data.data.resourceSpans;',
    '    const allSpans: (Span & { service: string })[] = [];',
    '    for (const r of rs) {',
    '      const svc = getServiceName(r.resource);',
    '      for (const ss of r.scopeSpans) {',
    '        for (const span of ss.spans) {',
    '          allSpans.push({ ...span, service: svc, name: span.name });',
    '        }',
    '      }',
    '    }',
    '    const byTrace = new Map<string, (Span & { service: string })[]>();',
    '    for (const s of allSpans) {',
    '      const arr = byTrace.get(s.traceId) ?? [];',
    '      arr.push(s);',
    '      byTrace.set(s.traceId, arr);',
    '    }',
    '    for (const [tid, spans] of byTrace) {',
    '      const services = new Set(spans.map(s => s.service));',
    '      if (!services.has("triggers-api") || !services.has("workers")) continue;',
    '      const enqueue = spans.find(s => s.name === "queue.enqueue" && s.service === "triggers-api");',
    '      const dequeue = spans.find(s => s.name === "queue.dequeue" && s.service === "workers");',
    '      const detect = spans.find(s => s.name === "trigger.detect" && s.service === "triggers-api");',
    '      const execute = spans.find(s => s.name === "job.execute" && s.service === "workers");',
    '      if (!enqueue || !dequeue || !detect || !execute) continue;',
    '      const parentLinked = dequeue.parentSpanId === enqueue.spanId;',
    '      const crossServices = services.size;',
    '      globalThis["console"].log("PASS: cross-service trace " + tid.substring(0, 16) + "...");',
    '      globalThis["console"].log("  services: " + [...services].join(", ") + " (" + crossServices + " services)");',
    '      globalThis["console"].log("  trigger.detect -> trigger.process -> queue.enqueue -> queue.dequeue -> job.execute");',
    '      globalThis["console"].log("  enqueue.spanId=" + enqueue.spanId.substring(0,8) + " dequeue.parent=" + dequeue.parentSpanId.substring(0,8) + " linked=" + parentLinked);',
    '      globalThis["console"].log("  spans in trace: " + spans.length);',
    '      if (!parentLinked) {',
    '        globalThis["console"].error("FAIL: queue.dequeue parent does not match queue.enqueue spanId");',
    '        throw new Error("queue.dequeue parent does not match queue.enqueue spanId");',
    '      }',
    '      foundTrace = true;',
    '      break;',
    '    }',
    '    if (!foundTrace) {',
    '      globalThis["console"].log("attempt " + attempt + "/" + MAX_ATTEMPTS + ": no cross-service trace found yet (" + allSpans.length + " spans, " + byTrace.size + " traces)");',
    '    }',
    '  } catch (e) {',
    '    globalThis["console"].log("attempt " + attempt + "/" + MAX_ATTEMPTS + ": " + (e as Error).message);',
    '  }',
    '}',
    'if (!foundTrace) {',
    '  globalThis["console"].error("FAIL: no cross-service trigger->worker trace found after " + MAX_ATTEMPTS + " attempts");',
    '  throw new Error("no cross-service trigger->worker trace found");',
    '}',
  ].join('\n');
}
