import { GATE, GATE_PHASE } from '../../../domain/cli-surface.ts';
import type { GateDefinition } from '../../../domain/gate-definition.ts';
import { commandGate } from './gate-factory.ts';

const WEBHOOK_URL = 'http://localhost:8093/api/v1/webhooks/inbound/generic';
const DASHBOARD_TRACES_URL = 'https://localhost:18888/api/telemetry/traces';

export function createOtelGates(): readonly GateDefinition[] {
  return [
    commandGate(
      GATE.BEHAVIOR_OTEL_WEBHOOK,
      'Fire webhook for OTEL trace capture',
      GATE_PHASE.BEHAVIOR,
      () => [
        'curl',
        '-sf',
        '-X',
        'POST',
        WEBHOOK_URL,
        '-H',
        'Content-Type: application/json',
        '-d',
        JSON.stringify({
          message: 'e2e-otel-gate',
          timestamp: new Date().toISOString(),
        }),
      ],
    ),
    commandGate(
      GATE.BEHAVIOR_OTEL_TRACES,
      'Validate OTEL trace chain via Dashboard API',
      GATE_PHASE.BEHAVIOR,
      () => [
        'deno',
        'eval',
        '--unsafely-ignore-certificate-errors=localhost',
        VALIDATE_TRACES_SCRIPT,
      ],
      undefined,
      'capture',
      'No OTEL traces found. Ensure the AppHost was started with --isolated and OTLP port 4318 is accepting telemetry.',
    ),
  ];
}

const VALIDATE_TRACES_SCRIPT = resolveValidateTracesScript();

function resolveValidateTracesScript(): string {
  return [
    'const MAX_ATTEMPTS = 8;',
    'const DELAY_MS = 2000;',
    '',
    'async function fetchTraces(): Promise<unknown> {',
    `  const resp = await fetch(${JSON.stringify(DASHBOARD_TRACES_URL)}, {`,
    '    headers: { Accept: "application/json" },',
    '  });',
    '  if (!resp.ok) throw new Error("Dashboard API " + resp.status);',
    '  return resp.json();',
    '}',
    '',
    'interface Span { name: string; kind: number; traceId: string; spanId: string; parentSpanId: string; }',
    'interface ScopeSpans { scope: { name: string }; spans: Span[]; }',
    'interface Resource { attributes: { key: string; value: { stringValue: string } }[]; }',
    'interface ResourceSpans { scopeSpans: ScopeSpans[]; resource: Resource; }',
    'interface TraceResponse { data: { resourceSpans: ResourceSpans[] }; totalCount: number; }',
    '',
    'function getServiceName(r: Resource): string {',
    '  return (r.attributes.find(a => a.key === "service.name")?.value.stringValue) ?? "unknown";',
    '}',
    '',
    'let foundTrace = false;',
    '',
    'for (let attempt = 1; attempt <= MAX_ATTEMPTS && !foundTrace; attempt++) {',
    '  if (attempt > 1) await new Promise(r => setTimeout(r, DELAY_MS));',
    '  try {',
    '    const data = await fetchTraces() as TraceResponse;',
    '    const rs = data.data.resourceSpans;',
    '    const allSpans: (Span & { service: string })[] = [];',
    '    for (const r of rs) {',
    '      const svc = getServiceName(r.resource);',
    '      for (const ss of r.scopeSpans) {',
    '        for (const span of ss.spans) {',
    '          allSpans.push({ ...span, service: svc, name: span.name });',
    '        }',
    '      }',
    '    }',
    '    const byTrace = new Map<string, (Span & { service: string })[]>();',
    '    for (const s of allSpans) {',
    '      const arr = byTrace.get(s.traceId) ?? [];',
    '      arr.push(s);',
    '      byTrace.set(s.traceId, arr);',
    '    }',
    '    for (const [tid, spans] of byTrace) {',
    '      const services = new Set(spans.map(s => s.service));',
    '      if (!services.has("triggers-api") || !services.has("workers")) continue;',
    '      const enqueue = spans.find(s => s.name === "queue.enqueue" && s.service === "triggers-api");',
    '      const dequeue = spans.find(s => s.name === "queue.dequeue" && s.service === "workers");',
    '      const detect = spans.find(s => s.name === "trigger.detect" && s.service === "triggers-api");',
    '      const execute = spans.find(s => s.name === "job.execute" && s.service === "workers");',
    '      if (!enqueue || !dequeue || !detect || !execute) continue;',
    '      const parentLinked = dequeue.parentSpanId === enqueue.spanId;',
    '      const crossServices = services.size;',
    '      globalThis["console"].log("PASS: cross-service trace " + tid.substring(0, 16) + "...");',
    '      globalThis["console"].log("  services: " + [...services].join(", ") + " (" + crossServices + " services)");',
    '      globalThis["console"].log("  trigger.detect -> trigger.process -> queue.enqueue -> queue.dequeue -> job.execute");',
    '      globalThis["console"].log("  enqueue.spanId=" + enqueue.spanId.substring(0,8) + " dequeue.parent=" + dequeue.parentSpanId.substring(0,8) + " linked=" + parentLinked);',
    '      globalThis["console"].log("  spans in trace: " + spans.length);',
    '      if (!parentLinked) {',
    '        globalThis["console"].error("FAIL: queue.dequeue parent does not match queue.enqueue spanId");',
    '        throw new Error("queue.dequeue parent does not match queue.enqueue spanId");',
    '      }',
    '      foundTrace = true;',
    '      break;',
    '    }',
    '    if (!foundTrace) {',
    '      globalThis["console"].log("attempt " + attempt + "/" + MAX_ATTEMPTS + ": no cross-service trace found yet (" + allSpans.length + " spans, " + byTrace.size + " traces)");',
    '    }',
    '  } catch (e) {',
    '    globalThis["console"].log("attempt " + attempt + "/" + MAX_ATTEMPTS + ": " + (e as Error).message);',
    '  }',
    '}',
    'if (!foundTrace) {',
    '  globalThis["console"].error("FAIL: no cross-service trigger->worker trace found after " + MAX_ATTEMPTS + " attempts");',
    '  throw new Error("no cross-service trigger->worker trace found");',
    '}',
  ].join('\n');
}
