import {
  ASPIRE_RESOURCE,
  type AspireResource,
  GATE,
  GATE_PHASE,
} from '../../../domain/cli-surface.ts';
import { DATABASE, type DatabaseEngine } from '../../../domain/extension-axes.ts';
import type { GateDefinition } from '../../../domain/gate-definition.ts';
import { commandGate, httpGate } from './gate-factory.ts';

const ASPIRE_RESOURCE_WAIT_TIMEOUT_SECONDS: Partial<Record<AspireResource, number>> = {
  [ASPIRE_RESOURCE.MSSQL]: 600,
};

function runtimeWaitGate(resource: AspireResource): GateDefinition {
  return commandGate(
    `runtime.wait.${resource}`,
    `Wait for ${resource}`,
    GATE_PHASE.RUNTIME,
    (context) => {
      const command = [
        'aspire',
        'wait',
        resource,
        '--apphost',
        context.project.appHost,
        '--non-interactive',
        '--nologo',
      ];
      const timeoutSeconds = ASPIRE_RESOURCE_WAIT_TIMEOUT_SECONDS[resource];
      if (timeoutSeconds !== undefined) {
        command.splice(3, 0, '--status', 'healthy', '--timeout', String(timeoutSeconds));
      }
      return command;
    },
  );
}

/** Create runtime and health-check gates for the generated application. */
export function createRuntimeGates(
  database: DatabaseEngine = DATABASE.POSTGRES,
): readonly GateDefinition[] {
  return [
    commandGate(
      GATE.RUNTIME_ASPIRE_RESTORE,
      'Restore Aspire TypeScript SDK',
      GATE_PHASE.RUNTIME,
      (context) => [
        'aspire',
        'restore',
        '--apphost',
        context.project.appHost,
        '--non-interactive',
        '--nologo',
      ],
    ),
    commandGate(
      GATE.RUNTIME_AUTH_SMOKE_ENV,
      'Wire auth smoke environment',
      GATE_PHASE.RUNTIME,
      (context) => ['deno', 'eval', AUTH_SMOKE_ENV_SCRIPT, context.project.projectRoot],
    ),
    commandGate(
      GATE.RUNTIME_FLOW_B_FIXTURE,
      'Wire real Flow-B callback fixture',
      GATE_PHASE.RUNTIME,
      (context) => [
        'deno',
        'run',
        '--allow-read',
        '--allow-write',
        'packages/cli/e2e/src/application/gates/scaffold/prepare-flow-b-fixture.ts',
        context.project.projectRoot,
      ],
    ),
    commandGate(
      GATE.RUNTIME_ASPIRE_START,
      'Start generated Aspire AppHost',
      GATE_PHASE.RUNTIME,
      (
        context,
      ) => [
        'deno',
        'eval',
        ASPIRE_START_SCRIPT,
        context.project.appHost,
        context.project.projectRoot,
      ],
    ),
    ...runtimeResources(database).map(runtimeWaitGate),
    commandGate(
      GATE.RUNTIME_ASPIRE_DESCRIBE,
      'Describe generated topology',
      GATE_PHASE.RUNTIME,
      (context) => [
        'aspire',
        'describe',
        '--apphost',
        context.project.appHost,
        '--format',
        'Json',
      ],
    ),
    commandGate(
      GATE.BEHAVIOR_SERVICE_HEALTH,
      'Users service health',
      GATE_PHASE.BEHAVIOR,
      (context) => ['deno', 'eval', PROBE_SERVICE_HEALTH_SCRIPT, context.project.appHost, 'users'],
    ),
    httpGate(
      GATE.BEHAVIOR_WORKERS_HEALTH,
      'Workers API health',
      'http://127.0.0.1:8091/health/live',
    ),
    httpGate(
      GATE.BEHAVIOR_WORKERS_JOBS,
      'List worker jobs',
      'http://127.0.0.1:8091/api/v1/workers/jobs',
    ),
    httpGate(
      GATE.BEHAVIOR_WORKERS_TASKS,
      'List worker tasks',
      'http://127.0.0.1:8091/api/v1/workers/tasks',
    ),
    httpGate(
      GATE.BEHAVIOR_WORKERS_SEED,
      'Seed worker demo data through API',
      'http://127.0.0.1:8091/api/v1/workers/seed',
      'POST',
    ),
    commandGate(
      GATE.BEHAVIOR_WORKERS_TRIGGER_HEALTH_JOB,
      'Trigger workers plugin health job',
      GATE_PHASE.BEHAVIOR,
      (context) => [
        'deno',
        'run',
        '--allow-read',
        '--allow-net=127.0.0.1:8091',
        'packages/cli/e2e/src/application/gates/scaffold/configure-flow-b-job.ts',
        context.project.projectRoot,
      ],
    ),
    commandGate(
      GATE.BEHAVIOR_WORKERS_EXECUTIONS,
      'List recent worker executions',
      GATE_PHASE.BEHAVIOR,
      () => ['deno', 'eval', VALIDATE_WORKER_EXECUTIONS_SCRIPT],
    ),
    httpGate(GATE.BEHAVIOR_SAGAS_HEALTH, 'Sagas API health', 'http://127.0.0.1:8092/health/live'),
    httpGate(
      GATE.BEHAVIOR_SAGAS_LIST,
      'List saga definitions',
      'http://127.0.0.1:8092/api/v1/sagas/sagas',
    ),
    httpGate(
      GATE.BEHAVIOR_SAGAS_INSTANCES,
      'List saga instances',
      'http://127.0.0.1:8092/api/v1/sagas/instances',
    ),
    httpGate(
      GATE.BEHAVIOR_TRIGGERS_HEALTH,
      'Triggers API health',
      'http://127.0.0.1:8093/health',
    ),
    commandGate(
      GATE.BEHAVIOR_TRIGGERS_WEBHOOK,
      'Accept generic trigger webhook',
      GATE_PHASE.BEHAVIOR,
      () => ['deno', 'eval', ACCEPT_TRIGGER_WEBHOOK_SCRIPT],
    ),
    commandGate(
      GATE.BEHAVIOR_TRIGGERS_EVENTS,
      'List trigger events',
      GATE_PHASE.BEHAVIOR,
      () => ['deno', 'eval', VALIDATE_TRIGGER_EVENTS_SCRIPT],
    ),
    httpGate(GATE.BEHAVIOR_AUTH_LIVE, 'Auth API liveness', 'http://127.0.0.1:8094/health/live'),
    httpGate(GATE.BEHAVIOR_AUTH_READY, 'Auth API readiness', 'http://127.0.0.1:8094/health/ready'),
    httpGate(
      GATE.BEHAVIOR_AUTH_SESSION,
      'Read auth session route',
      'http://127.0.0.1:8094/api/v1/auth/session',
    ),
    commandGate(
      GATE.BEHAVIOR_AI_CHAT_ROUTE,
      'Import generated AI chat route',
      GATE_PHASE.BEHAVIOR,
      (context) => ['deno', 'eval', VALIDATE_AI_CHAT_ROUTE_SCRIPT, context.project.projectRoot],
      (context) => context.project.projectRoot,
    ),
  ];
}

const ASPIRE_START_SCRIPT = [
  'const appHost = Deno.args[0];',
  'const projectRoot = Deno.args[1];',
  'if (!appHost) throw new Error("apphost argument is required");',
  'if (!projectRoot) throw new Error("project root argument is required");',
  'const command = new Deno.Command("aspire", {',
  '  args: [',
  '    "start",',
  '    "--apphost",',
  '    appHost,',
  '    "--isolated",',
  '    "--non-interactive",',
  '    "--nologo",',
  '    "--format",',
  '    "Json",',
  '  ],',
  '  stdout: "piped",',
  '  stderr: "piped",',
  '});',
  'const output = await command.output();',
  'const stdout = new TextDecoder().decode(output.stdout);',
  'const stderr = new TextDecoder().decode(output.stderr);',
  'if (!output.success) {',
  '  throw new Error(`aspire start failed with code ${output.code}: ${stderr || stdout}`);',
  '}',
  'const metadata = JSON.parse(extractJson(stdout));',
  'if (!metadata.dashboardUrl) throw new Error("aspire start did not report dashboardUrl");',
  'const stateDir = `${projectRoot}/.netscript/e2e`;',
  'await Deno.mkdir(stateDir, { recursive: true });',
  'await Deno.writeTextFile(`${stateDir}/aspire-start.json`, JSON.stringify(metadata, null, 2));',
  'console.info(`Aspire dashboard: ${metadata.dashboardUrl}`);',
  'if (metadata.logFile) console.info(`Aspire log: ${metadata.logFile}`);',
  '',
  'function extractJson(text) {',
  '  const trimmed = text.trim();',
  '  const objectIndex = trimmed.indexOf("{");',
  '  if (objectIndex < 0) throw new Error("aspire start did not emit JSON");',
  '  return trimmed.slice(objectIndex);',
  '}',
].join('\n');
function runtimeResources(database: DatabaseEngine): readonly AspireResource[] {
  return [
    ...databaseRuntimeResources(database),
    ASPIRE_RESOURCE.GARNET,
    ASPIRE_RESOURCE.WORKERS_API,
    ASPIRE_RESOURCE.WORKERS,
    ASPIRE_RESOURCE.SAGAS_API,
    ASPIRE_RESOURCE.SAGAS,
    ASPIRE_RESOURCE.TRIGGERS_API,
    ASPIRE_RESOURCE.TRIGGERS,
    ASPIRE_RESOURCE.AUTH,
    ASPIRE_RESOURCE.STREAMS,
  ];
}

const VALIDATE_AI_CHAT_ROUTE_SCRIPT = [
  'const projectRoot = Deno.args[0];',
  'if (!projectRoot) throw new Error("project root argument is required");',
  'const route = await import(`file://${projectRoot}/ai/routes/chat-stream.ts`);',
  'if (typeof route.handler !== "function") throw new Error("AI chat-stream handler is not exported");',
  'if (typeof route.aiRouter !== "object" || route.aiRouter === null) {',
  '  throw new Error("AI chat-stream route did not export a contract-bound aiRouter");',
  '}',
  'if (typeof route.aiRouteContract !== "object" || route.aiRouteContract === null) {',
  '  throw new Error("AI chat-stream route did not export aiContractV1 handle");',
  '}',
  'console.info("AI chat route contract import smoke passed");',
].join('\n');

function databaseRuntimeResources(database: DatabaseEngine): readonly AspireResource[] {
  switch (database) {
    case DATABASE.POSTGRES:
      return [ASPIRE_RESOURCE.POSTGRES];
    case DATABASE.MYSQL:
      return [ASPIRE_RESOURCE.MYSQL];
    case DATABASE.MSSQL:
      return [ASPIRE_RESOURCE.MSSQL];
    case DATABASE.SQLITE:
      return [];
  }
}

const PROBE_SERVICE_HEALTH_SCRIPT = [
  'const appHost = Deno.args[0];',
  'const resourceName = Deno.args[1] ?? "users";',
  'if (!appHost) throw new Error("apphost argument is required");',
  'const command = new Deno.Command("aspire", {',
  '  args: ["describe", "--apphost", appHost, "--format", "Json"],',
  '  stdout: "piped",',
  '  stderr: "piped",',
  '});',
  'const output = await command.output();',
  'const stdout = new TextDecoder().decode(output.stdout);',
  'const stderr = new TextDecoder().decode(output.stderr);',
  'if (!output.success) {',
  '  throw new Error(`aspire describe failed with code ${output.code}: ${stderr || stdout}`);',
  '}',
  'const topology = JSON.parse(extractJson(stdout));',
  'const resource = findResource(topology, resourceName);',
  'if (!resource) {',
  '  throw new Error(`resource ${resourceName} was not present in aspire describe output`);',
  '}',
  'const urls = collectHttpUrls(resource);',
  'if (urls.length === 0) {',
  '  throw new Error(`resource ${resourceName} did not expose an HTTP endpoint in aspire describe output`);',
  '}',
  'const errors = [];',
  'for (const baseUrl of urls) {',
  '  const healthUrl = new URL("/health", baseUrl).toString();',
  '  const result = await probe(healthUrl);',
  '  if (result.ok) {',
  '    console.info(`service health probe passed: ${healthUrl} -> ${result.status}`);',
  '    Deno.exit(0);',
  '  }',
  '  errors.push(`${healthUrl} -> ${result.status}: ${result.body}`);',
  '}',
  'throw new Error(`service health probe failed for ${resourceName}: ${errors.join("; ")}`);',
  '',
  'function extractJson(text) {',
  '  const trimmed = text.trim();',
  '  if (trimmed.startsWith("{") || trimmed.startsWith("[")) return trimmed;',
  '  const objectIndex = trimmed.indexOf("{");',
  '  const arrayIndex = trimmed.indexOf("[");',
  '  const indexes = [objectIndex, arrayIndex].filter((index) => index >= 0);',
  '  if (indexes.length === 0) throw new Error("aspire describe did not emit JSON");',
  '  return trimmed.slice(Math.min(...indexes));',
  '}',
  '',
  'function findResource(value, name) {',
  '  if (!isRecord(value)) return undefined;',
  '  if (resourceNameMatches(value, name)) return value;',
  '  for (const child of Object.values(value)) {',
  '    if (Array.isArray(child)) {',
  '      for (const item of child) {',
  '        const match = findResource(item, name);',
  '        if (match) return match;',
  '      }',
  '      continue;',
  '    }',
  '    const match = findResource(child, name);',
  '    if (match) return match;',
  '  }',
  '  return undefined;',
  '}',
  '',
  'function resourceNameMatches(value, name) {',
  '  for (const key of ["name", "displayName", "resourceName"]) {',
  '    const candidate = value[key];',
  '    if (typeof candidate === "string" && candidate.toLowerCase() === name.toLowerCase()) {',
  '      return true;',
  '    }',
  '  }',
  '  return false;',
  '}',
  '',
  'function collectHttpUrls(value) {',
  '  const urls = new Set();',
  '  collect(value, urls);',
  '  return [...urls];',
  '}',
  '',
  'function collect(value, urls) {',
  '  if (typeof value === "string") {',
  '    if (/^https?:\\/\\//i.test(value)) urls.add(value);',
  '    return;',
  '  }',
  '  if (Array.isArray(value)) {',
  '    for (const item of value) collect(item, urls);',
  '    return;',
  '  }',
  '  if (!isRecord(value)) return;',
  '  for (const child of Object.values(value)) collect(child, urls);',
  '}',
  '',
  'function isRecord(value) {',
  '  return typeof value === "object" && value !== null && !Array.isArray(value);',
  '}',
  '',
  'async function probe(url) {',
  '  for (let attempt = 1; attempt <= 30; attempt++) {',
  '    try {',
  '      const response = await fetch(url);',
  '      const body = await response.text();',
  '      if (response.ok) return { ok: true, status: response.status, body: body.slice(0, 200) };',
  '      if (attempt === 30) return { ok: false, status: response.status, body: body.slice(0, 200) };',
  '    } catch (error) {',
  '      if (attempt === 30) {',
  '        return { ok: false, status: 0, body: error instanceof Error ? error.message : String(error) };',
  '      }',
  '    }',
  '    await new Promise((resolve) => setTimeout(resolve, 1_000));',
  '  }',
  '  return { ok: false, status: 0, body: "probe exhausted without a request" };',
  '}',
].join('\n');

const VALIDATE_TRIGGER_EVENTS_SCRIPT = [
  'const url = "http://127.0.0.1:8093/api/v1/events?limit=10";',
  'const response = await fetch(url);',
  'if (!response.ok) throw new Error("HTTP " + response.status + " from " + url);',
  'const body = await response.json() as { events?: unknown[]; total?: number };',
  'if (!Array.isArray(body.events)) throw new Error("events response is missing events[]");',
  'if (typeof body.total !== "number") throw new Error("events response is missing total");',
  'if (body.total < 1) throw new Error("expected at least one trigger event after webhook gate");',
].join('\n');

const ACCEPT_TRIGGER_WEBHOOK_SCRIPT = [
  'const url = "http://127.0.0.1:8093/api/v1/webhooks/inbound/generic";',
  'let lastStatus = 0;',
  'let lastBody = "";',
  'for (let attempt = 1; attempt <= 30; attempt++) {',
  '  const response = await fetch(url, {',
  '    method: "POST",',
  '    headers: { "Content-Type": "application/json" },',
  '    body: JSON.stringify({',
  '      message: "e2e-trigger-gate",',
  '      timestamp: new Date().toISOString(),',
  '    }),',
  '  });',
  '  lastStatus = response.status;',
  '  lastBody = await response.text();',
  '  if (response.ok) {',
  '    console.info(`trigger webhook accepted: HTTP ${response.status}`);',
  '    Deno.exit(0);',
  '  }',
  '  await new Promise((resolve) => setTimeout(resolve, 500));',
  '}',
  'throw new Error(`trigger webhook was not accepted after retries: HTTP ${lastStatus}: ${lastBody}`);',
].join('\n');

const AUTH_SMOKE_ENV_SCRIPT = [
  'const projectRoot = Deno.args[0];',
  'if (!projectRoot) throw new Error("project root argument is required");',
  'const helperPath = `${projectRoot}/aspire/.helpers/register-plugins.mts`;',
  'const env = {',
  '  NETSCRIPT_AUTH_BACKEND: "kv-oauth",',
  '  NETSCRIPT_AUTH_CLIENT_ID: "scaffold_runtime_smoke",',
  '  NETSCRIPT_AUTH_CLIENT_SECRET: "scaffold_runtime_smoke_secret",',
  '  NETSCRIPT_AUTH_AUTHORIZATION_ENDPOINT: "https://issuer.example.test/oauth/authorize",',
  '  NETSCRIPT_AUTH_TOKEN_ENDPOINT: "https://issuer.example.test/oauth/token",',
  '  NETSCRIPT_AUTH_REDIRECT_URI: "http://127.0.0.1:8094/api/v1/auth/callback",',
  '  NETSCRIPT_AUTH_KV_OAUTH_KEY: "BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwc=",',
  '  NETSCRIPT_AUTH_ALLOW_INSECURE_REQUESTS: "true",',
  '};',
  'const source = await Deno.readTextFile(helperPath);',
  'const marker = "  // --- auth ---";',
  'const markerIndex = source.indexOf(marker);',
  'if (markerIndex < 0) throw new Error("register-plugins.mts does not contain auth block");',
  'const nextMarkerIndex = source.indexOf("  // ---", markerIndex + marker.length);',
  'const blockEnd = nextMarkerIndex < 0 ? source.length : nextMarkerIndex;',
  'const bootstrapLine = "    await resource.withEnvironment(\\\'NETSCRIPT_PLUGIN_SERVICE_BOOTSTRAP_MODULE\\\', bootstrapModule);";',
  'const bootstrapIndex = source.indexOf(bootstrapLine, markerIndex);',
  'if (bootstrapIndex < 0) throw new Error("auth block does not contain bootstrap env line");',
  'if (bootstrapIndex >= blockEnd) throw new Error("bootstrap env line was not in auth block");',
  'const lines = Object.entries(env).map(([key, value]) =>',
  '  `    await resource.withEnvironment(${JSON.stringify(key)}, ${JSON.stringify(value)});\\n`,',
  ');',
  'const insertAt = bootstrapIndex + bootstrapLine.length;',
  'const updated = source.includes("NETSCRIPT_AUTH_BACKEND")',
  '  ? source',
  '  : source.slice(0, insertAt) + "\\n" + lines.join("") + source.slice(insertAt);',
  'if (!updated.includes("NETSCRIPT_AUTH_BACKEND")) throw new Error("auth smoke env insert did not take effect");',
  'await Deno.writeTextFile(helperPath, updated);',
].join('\n');

const VALIDATE_WORKER_EXECUTIONS_SCRIPT = [
  'const url = "http://127.0.0.1:8091/api/v1/workers/executions?limit=10";',
  'const expectedJobId = "workers-plugin-health-check";',
  'let lastBody = "";',
  'for (let attempt = 1; attempt <= 30; attempt++) {',
  '  const response = await fetch(url);',
  '  lastBody = await response.text();',
  '  if (!response.ok) throw new Error("HTTP " + response.status + " from " + url + ": " + lastBody);',
  '  const body = JSON.parse(lastBody);',
  '  if (!Array.isArray(body.executions)) throw new Error("executions response is missing executions[]");',
  '  if (typeof body.total !== "number") throw new Error("executions response is missing total");',
  '  const execution = body.executions.find((item) => isExecutionForJob(item, expectedJobId));',
  '  if (execution && isRecord(execution) && execution.status === "completed") {',
  '    console.info(`worker health job completed after ${attempt} attempt(s)`);',
  '    Deno.exit(0);',
  '  }',
  '  if (execution && isRecord(execution) && ["failed", "timeout", "cancelled"].includes(String(execution.status))) {',
  '    throw new Error(`worker health job reached terminal failure state: ${JSON.stringify(execution)}`);',
  '  }',
  '  await new Promise((resolve) => setTimeout(resolve, 1_000));',
  '}',
  'throw new Error(`expected completed ${expectedJobId} execution after trigger gate; last body: ${lastBody}`);',
  '',
  'function isExecutionForJob(value, jobId) {',
  '  return isRecord(value) && value.jobId === jobId;',
  '}',
  '',
  'function isRecord(value) {',
  '  return typeof value === "object" && value !== null && !Array.isArray(value);',
  '}',
].join('\n');

/** Create cleanup gates that stop generated runtime resources. */
export function createCleanupGates(): readonly GateDefinition[] {
  return [
    commandGate(GATE.CLEANUP_ASPIRE_STOP, 'Stop generated Aspire AppHost', GATE_PHASE.CLEANUP, (
      context,
    ) => [
      'aspire',
      'stop',
      '--apphost',
      context.project.appHost,
      '--non-interactive',
      '--nologo',
    ]),
  ];
}
