/**
 * Version 1 AI plugin contract: the `/v1/ai` route surface, its streamed-chunk
 * IO schemas, and the engine-derived vocabulary types.
 *
 * This subpath is the full contract surface (Zod validators + types + the oRPC
 * contract handles). The package root (`@netscript/plugin-ai-core`) re-exports a
 * curated, ≤20-symbol subset of it.
 *
 * @module
 */

export {
  aiContract,
  aiContractV1,
  ChatChunkSchema,
  ChatInputSchema,
  EmbedInputSchema,
  EmbedResponseSchema,
  ModelsInputSchema,
  ModelsResponseSchema,
  ToolInvokeInputSchema,
  ToolInvokeResponseSchema,
  TranscribeInputSchema,
  TranscribeResponseSchema,
} from './ai.contract.ts';
export type {
  AgentChunk,
  AiCapabilities,
  AiContract,
  AiContractDefinition,
  AiContractDefinitionShape,
  AiContractV1,
  AiRouter,
  AudioContentPart,
  ChatChunk,
  ChatInput,
  CompletionTokensDetails,
  ContentModality,
  ContentPart,
  ContentSource,
  DataContentSource,
  DocumentContentPart,
  DoneChunk,
  EmbedInput,
  EmbedResponse,
  ErrorChunk,
  ImageContentPart,
  JsonSchema,
  Message,
  MessageChunk,
  MessageContent,
  MessageRole,
  ModelCapabilities,
  ModelDescriptor,
  ModelId,
  ModelRef,
  ModelSelector,
  ModelsInput,
  ModelsResponse,
  PromptTokensDetails,
  ProviderUsageDetails,
  ReasoningChunk,
  TextChunk,
  TextContentPart,
  ToolCall,
  ToolCallChunk,
  ToolCallState,
  ToolDescriptor,
  ToolInvokeInput,
  ToolInvokeResponse,
  ToolParameters,
  ToolResult,
  ToolResultChunk,
  ToolResultState,
  TranscribeInput,
  TranscribeResponse,
  UrlContentSource,
  Usage,
  UsageChunk,
  UsageCostBreakdown,
  VideoContentPart,
} from './ai.contract.ts';
