// @generated by .llm/tools/generate-publish-assets.ts
// Do not edit by hand. Run `deno task gen:publish-assets`.

/** Version of the published plugin package. */
export const PLUGIN_PACKAGE_VERSION: string = '0.0.1-beta.10';
