import { renderRegistryModule } from '@netscript/plugin/cli';

interface Args {
  readonly manifestPath: string;
  readonly officialSamples: boolean;
  readonly profile?: string;
  readonly projectRoot: string;
}

interface RuntimeManifest {
  readonly runtimeRegistries?: readonly RuntimeRegistryTarget[];
}

interface RuntimeRegistryTarget {
  readonly kind: 'map';
  readonly dir: string;
  readonly fileSuffixes: readonly string[];
  readonly exclude: readonly string[];
  readonly registryPath?: string;
}

interface ProjectFileEntry {
  readonly relativePath: string;
}

if (import.meta.main) {
  const args = parseArgs(Deno.args);
  const target = await readTriggerRegistryTarget(args.manifestPath);
  if (target === undefined) {
    throw new Error(`No trigger registry target found in ${args.manifestPath}.`);
  }

  const registryPath = target.registryPath ?? `${target.dir}/_registry.ts`;
  await generateTriggerRegistry(args.projectRoot, {
    ...target,
    registryPath,
  });
  console.log(`generated ${registryPath}`);
}

async function generateTriggerRegistry(
  projectRoot: string,
  options: RuntimeRegistryTarget & { readonly registryPath: string },
): Promise<void> {
  const files = await listRootFiles(projectRoot, options.dir, options.fileSuffixes);
  const triggerFiles = files.filter((file) => isIncludedSourcePath(file.relativePath, options));
  const source = renderTriggerRegistrySource(options.registryPath, triggerFiles);
  await writeTextFile(projectRoot, options.registryPath, source);
}

function renderTriggerRegistrySource(
  registryPath: string,
  triggers: readonly ProjectFileEntry[],
): string {
  return renderRegistryModule({
    registryPath,
    items: triggers,
    alias: (index) => `trigger${index}`,
    renderImport: (alias, specifier) => `import * as ${alias} from ${quoteString(specifier)};`,
    renderEntry: (alias, trigger) => [
      `  ...resolveTriggerDefinitions(${alias}, ${quoteString(trigger.relativePath)}),`,
    ],
    header: [
      '/**',
      ' * Trigger Registry - AUTO-GENERATED',
      ' *',
      ' * DO NOT EDIT - regenerated by the triggers plugin CLI.',
      ' *',
      ' * @module',
      ' */',
      '',
      "import type { TriggerDefinition } from '@netscript/plugin-triggers-core/domain';",
    ],
    body: (entries) => [
      'const definitions: readonly TriggerDefinition[] = [',
      ...entries,
      '];',
      '',
      'export const registry: ReadonlyMap<string, TriggerDefinition> = new Map<string, TriggerDefinition>(',
      '  definitions.map((definition): readonly [string, TriggerDefinition] => [String(definition.id), definition]),',
      ');',
      '',
      'function resolveTriggerDefinitions(',
      '  module: Record<string, unknown>,',
      '  path: string,',
      '): readonly TriggerDefinition[] {',
      '  const candidates = [module.default, module.trigger, module.definition, ...Object.values(module)];',
      '  const definitions = candidates.flatMap((candidate) =>',
      '    Array.isArray(candidate) ? candidate : [candidate]',
      '  ).filter(isTriggerDefinition);',
      '',
      '  if (definitions.length === 0) {',
      '    throw new Error(`Trigger module ${path} does not export a TriggerDefinition.`);',
      '  }',
      '  return definitions;',
      '}',
      '',
      'function isTriggerDefinition(candidate: unknown): candidate is TriggerDefinition {',
      "  if (typeof candidate !== 'object' || candidate === null) {",
      '    return false;',
      '  }',
      '  const value = candidate as Record<string, unknown>;',
      "  return typeof value.id === 'string' &&",
      "    typeof value.kind === 'string' &&",
      "    typeof value.handler === 'function';",
      '}',
      '',
    ],
  });
}

function parseArgs(args: readonly string[]): Args {
  let projectRoot = Deno.cwd();
  let manifestPath = 'plugins/triggers/scaffold.runtime.json';
  let officialSamples = true;
  let profile: string | undefined;

  for (let index = 0; index < args.length; index++) {
    const arg = args[index];
    if (arg === '--project-root') {
      projectRoot = requiredValue(args, ++index, arg);
    } else if (arg === '--manifest') {
      manifestPath = requiredValue(args, ++index, arg);
    } else if (arg === '--profile') {
      profile = requiredValue(args, ++index, arg);
    } else if (arg === '--official-samples') {
      officialSamples = requiredValue(args, ++index, arg) !== 'false';
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return { manifestPath, officialSamples, profile, projectRoot };
}

async function readTriggerRegistryTarget(
  manifestPath: string,
): Promise<RuntimeRegistryTarget | undefined> {
  const manifest = JSON.parse(await Deno.readTextFile(manifestPath)) as RuntimeManifest;
  return manifest.runtimeRegistries?.find((target) => target.kind === 'map');
}

async function listRootFiles(
  projectRoot: string,
  root: string,
  extensions: readonly string[],
): Promise<readonly ProjectFileEntry[]> {
  const entries: ProjectFileEntry[] = [];
  const absoluteRoot = joinPath(projectRoot, root);
  if (!await isDirectory(absoluteRoot)) {
    return entries;
  }

  for await (const entry of Deno.readDir(absoluteRoot)) {
    if (entry.isFile && extensions.some((extension) => entry.name.endsWith(extension))) {
      entries.push({ relativePath: joinPath(normalizeRelative(root), entry.name) });
    }
  }
  return entries.toSorted((left, right) => left.relativePath.localeCompare(right.relativePath));
}

async function writeTextFile(projectRoot: string, path: string, content: string): Promise<void> {
  const target = joinPath(projectRoot, path);
  await Deno.mkdir(dirname(target), { recursive: true });
  await Deno.writeTextFile(target, content);
}

async function isDirectory(path: string): Promise<boolean> {
  try {
    return (await Deno.stat(path)).isDirectory;
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      return false;
    }
    throw error;
  }
}

function isIncludedSourcePath(path: string, options: RuntimeRegistryTarget): boolean {
  const fileName = basename(path);
  return !options.exclude.includes(fileName);
}

function requiredValue(args: readonly string[], index: number, flag: string): string {
  const value = args[index];
  if (!value) {
    throw new Error(`Missing value for ${flag}.`);
  }
  return value;
}

function basename(path: string): string {
  const normalized = normalize(path);
  const index = normalized.lastIndexOf('/');
  return index < 0 ? normalized : normalized.slice(index + 1);
}

function dirname(path: string): string {
  const normalized = normalize(path);
  const index = normalized.lastIndexOf('/');
  return index < 0 ? normalized : normalized.slice(0, index);
}

function joinPath(...parts: readonly string[]): string {
  return normalize(parts.filter((part) => part.length > 0).join('/'));
}

function normalizeRelative(path: string): string {
  return normalize(path).replace(/^\/+/, '').replace(/\/+$/, '');
}

function normalize(path: string): string {
  return path.replaceAll('\\', '/').replace(/\/+/g, '/');
}

function quoteString(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}
