import { type ProjectFiles, renderRegistryModule } from '@netscript/plugin/cli';

/** Result returned after compiling the trigger runtime registry. */
export type TriggerRegistryCompileResult = Readonly<{
  files: readonly string[];
  registryPath: string;
  triggerCount: number;
}>;

const REGISTRY_PATH = '.netscript/generated/plugin-triggers/triggers.registry.ts';
const EXCLUDED_FILES = new Set([
  'triggers/_jobs.ts',
  'triggers/_registry.ts',
  'triggers/mod.ts',
  'triggers/types.ts',
  'triggers/csv-import-trigger.ts',
]);

/** Compile project trigger definitions into the runtime registry module. */
export async function compileTriggerRegistry(
  files: ProjectFiles,
): Promise<TriggerRegistryCompileResult> {
  const triggerFiles = (await files.listFiles('triggers', ['.ts']))
    .map((entry) => entry.relativePath.replaceAll('\\', '/'))
    .filter((path) => isRegistryInput(path))
    .sort((left, right) => left.localeCompare(right));

  await files.writeTextFile(REGISTRY_PATH, renderRegistry(triggerFiles));
  return {
    files: triggerFiles,
    registryPath: REGISTRY_PATH,
    triggerCount: triggerFiles.length,
  };
}

function isRegistryInput(path: string): boolean {
  if (EXCLUDED_FILES.has(path)) {
    return false;
  }
  return path.startsWith('triggers/') &&
    path.slice('triggers/'.length).includes('/') === false;
}

function renderRegistry(files: readonly string[]): string {
  return renderRegistryModule({
    registryPath: REGISTRY_PATH,
    items: files.map((relativePath) => ({ relativePath })),
    alias: (index) => `trigger${index}`,
    renderImport: (alias, specifier) => `import * as ${alias} from ${JSON.stringify(specifier)};`,
    renderEntry: (alias, item) => [
      `  ...resolveTriggerDefinitions(${alias}, ${JSON.stringify(item.relativePath)}),`,
    ],
    header: [
      '/**',
      ' * Trigger Registry - AUTO-GENERATED',
      ' *',
      ' * DO NOT EDIT - regenerated by the triggers plugin CLI.',
      ' *',
      ' * @module',
      ' */',
      '',
      "import type { TriggerDefinition } from '@netscript/plugin-triggers-core/domain';",
    ],
    body: (entries) => [
      'const definitions: readonly TriggerDefinition[] = [',
      ...entries,
      '];',
      '',
      'export const registry: ReadonlyMap<string, TriggerDefinition> = new Map<string, TriggerDefinition>(',
      '  definitions.map((definition): readonly [string, TriggerDefinition] => [String(definition.id), definition]),',
      ');',
      '',
      'function resolveTriggerDefinitions(',
      '  module: Record<string, unknown>,',
      '  path: string,',
      '): readonly TriggerDefinition[] {',
      '  const candidates = [module.default, module.trigger, module.definition, ...Object.values(module)];',
      '  const definitions = candidates.flatMap((candidate) =>',
      '    Array.isArray(candidate) ? candidate : [candidate]',
      '  ).filter(isTriggerDefinition);',
      '',
      '  if (definitions.length === 0) {',
      '    throw new Error(`Trigger module ${path} does not export a TriggerDefinition.`);',
      '  }',
      '  return definitions;',
      '}',
      '',
      'function isTriggerDefinition(candidate: unknown): candidate is TriggerDefinition {',
      "  if (typeof candidate !== 'object' || candidate === null) {",
      '    return false;',
      '  }',
      '  const value = candidate as Record<string, unknown>;',
      "  return typeof value.id === 'string' &&",
      "    typeof value.kind === 'string' &&",
      "    typeof value.handler === 'function';",
      '}',
      '',
    ],
  });
}
