import type { ProjectFiles } from './adapters/local-project-files.ts';

/** Result returned after compiling the trigger runtime registry. */
export type TriggerRegistryCompileResult = Readonly<{
  files: readonly string[];
  registryPath: string;
  triggerCount: number;
}>;

const REGISTRY_PATH = '.netscript/generated/plugin-triggers/triggers.registry.ts';
const EXCLUDED_FILES = new Set([
  'triggers/_jobs.ts',
  'triggers/_registry.ts',
  'triggers/mod.ts',
  'triggers/types.ts',
  'triggers/csv-import-trigger.ts',
]);

/** Compile project trigger definitions into the runtime registry module. */
export async function compileTriggerRegistry(
  files: ProjectFiles,
): Promise<TriggerRegistryCompileResult> {
  const triggerFiles = (await files.listFiles('triggers', ['.ts']))
    .map((entry) => entry.relativePath.replaceAll('\\', '/'))
    .filter((path) => isRegistryInput(path))
    .sort((left, right) => left.localeCompare(right));

  await files.writeTextFile(REGISTRY_PATH, renderRegistry(triggerFiles));
  return {
    files: triggerFiles,
    registryPath: REGISTRY_PATH,
    triggerCount: triggerFiles.length,
  };
}

function isRegistryInput(path: string): boolean {
  if (EXCLUDED_FILES.has(path)) {
    return false;
  }
  return path.startsWith('triggers/') &&
    path.slice('triggers/'.length).includes('/') === false;
}

function renderRegistry(files: readonly string[]): string {
  const registryDir = dirname(REGISTRY_PATH);
  const imports = files.map((file, index) =>
    `import * as trigger${index} from ${JSON.stringify(toRelativeImport(registryDir, file))};`
  );
  const definitions = files.map((file, index) =>
    `  ...resolveTriggerDefinitions(trigger${index}, ${JSON.stringify(file)}),`
  );

  return [
    '/**',
    ' * Trigger Registry - AUTO-GENERATED',
    ' *',
    ' * DO NOT EDIT - regenerated by the triggers plugin CLI.',
    ' *',
    ' * @module',
    ' */',
    '',
    "import type { TriggerDefinition } from '@netscript/plugin-triggers-core/domain';",
    ...imports,
    '',
    'const definitions: readonly TriggerDefinition[] = [',
    ...definitions,
    '];',
    '',
    'export const registry: ReadonlyMap<string, TriggerDefinition> = new Map<string, TriggerDefinition>(',
    '  definitions.map((definition): readonly [string, TriggerDefinition] => [String(definition.id), definition]),',
    ');',
    '',
    'function resolveTriggerDefinitions(',
    '  module: Record<string, unknown>,',
    '  path: string,',
    '): readonly TriggerDefinition[] {',
    '  const candidates = [module.default, module.trigger, module.definition, ...Object.values(module)];',
    '  const definitions = candidates.flatMap((candidate) =>',
    '    Array.isArray(candidate) ? candidate : [candidate]',
    '  ).filter(isTriggerDefinition);',
    '',
    '  if (definitions.length === 0) {',
    '    throw new Error(`Trigger module ${path} does not export a TriggerDefinition.`);',
    '  }',
    '  return definitions;',
    '}',
    '',
    'function isTriggerDefinition(candidate: unknown): candidate is TriggerDefinition {',
    "  if (typeof candidate !== 'object' || candidate === null) {",
    '    return false;',
    '  }',
    '  const value = candidate as Record<string, unknown>;',
    "  return typeof value.id === 'string' &&",
    "    typeof value.kind === 'string' &&",
    "    typeof value.handler === 'function';",
    '}',
    '',
  ].join('\n');
}

function dirname(path: string): string {
  const normalized = normalize(path);
  const index = normalized.lastIndexOf('/');
  return index < 0 ? normalized : normalized.slice(0, index);
}

function normalize(path: string): string {
  return path.replaceAll('\\', '/').replace(/\/+/g, '/');
}

function toRelativeImport(fromDir: string, target: string): string {
  const fromParts = normalize(fromDir).split('/').filter(Boolean);
  const targetParts = normalize(target).split('/').filter(Boolean);
  const shared = sharedPrefixLength(fromParts, targetParts);
  const up = fromParts.slice(shared).map(() => '..');
  const down = targetParts.slice(shared);
  const specifier = [...up, ...down].join('/');
  return specifier.startsWith('.') ? specifier : `./${specifier}`;
}

function sharedPrefixLength(left: readonly string[], right: readonly string[]): number {
  const mismatch = left.findIndex((part, index) => part !== right[index]);
  return mismatch < 0 ? Math.min(left.length, right.length) : mismatch;
}
