// This file is seeded by netscript init and regenerated by @netscript/fresh/vite.

export const routePatterns = {
  $route: '/',
  health: {
    $route: '/health',
  },
  examples: {
    $route: '/examples',
    telemetry: {
      $route: '/examples/telemetry',
    },
  },
} as const;
