// This file is seeded by netscript init and regenerated by @netscript/fresh/vite.

import { createRouteReference } from '@netscript/fresh/route';
import { routePatterns } from './manifest.ts';

export const routes = {
  $route: createRouteReference(routePatterns.$route, {
    id: 'home',
    kind: 'page',
  }),
  health: {
    $route: createRouteReference(routePatterns.health.$route, {
      id: 'health',
      kind: 'page',
    }),
  },
  examples: {
    $route: createRouteReference(routePatterns.examples.$route, {
      id: 'examples',
      kind: 'page',
    }),
    telemetry: createRouteReference(routePatterns.examples.telemetry.$route, {
      id: 'examples.telemetry',
      kind: 'page',
    }),
  },
} as const;
