/** Guidance printed when detached dashboard discovery cannot resolve a URL. */
export const ASPIRE_DASHBOARD_RESOLUTION_GUIDANCE =
  'Try: aspire otel <sub> <resource> --dashboard-url <url>\n' +
  'Try: aspire export --dashboard-url <url> -o <path>';

/** Format the actionable failure emitted by generated Aspire workspace tasks. */
export function formatAspireDashboardResolutionFailure(cause: string): string {
  return `Dashboard URL resolution failed: ${cause}\n${ASPIRE_DASHBOARD_RESOLUTION_GUIDANCE}`;
}

/** Generate the dependency-free detached Aspire CLI task runner. */
export function generateAspireCliTaskRunner(): string {
  return `// GENERATED BY @netscript/cli. DO NOT EDIT.
// Resolves detached Aspire dashboard discovery without jq or third-party dependencies.

const decoder = new TextDecoder();
const guidance = ${JSON.stringify(ASPIRE_DASHBOARD_RESOLUTION_GUIDANCE)};
const [mode, ...forwardedArgs] = Deno.args;

if (mode !== 'otel' && mode !== 'export') {
  console.error('Expected task mode "otel" or "export".');
  Deno.exit(2);
}

const primary = await runAspire([mode, ...forwardedArgs]);
await relay(primary);
if (primary.success) Deno.exit(0);

try {
  const dashboardUrl = await resolveDashboardUrl();
  const fallback = await runAspire([mode, ...forwardedArgs, '--dashboard-url', dashboardUrl]);
  await relay(fallback);
  Deno.exit(fallback.code);
} catch (error) {
  const cause = error instanceof Error ? error.message : String(error);
  console.error(\`Dashboard URL resolution failed: \${cause}\`);
  console.error(guidance);
  Deno.exit(primary.code || 1);
}

async function runAspire(args: string[]): Promise<Deno.CommandOutput> {
  return await new Deno.Command('aspire', {
    args,
    stdout: 'piped',
    stderr: 'piped',
  }).output();
}

async function relay(output: Deno.CommandOutput): Promise<void> {
  if (output.stdout.length > 0) await Deno.stdout.write(output.stdout);
  if (output.stderr.length > 0) await Deno.stderr.write(output.stderr);
}

async function resolveDashboardUrl(): Promise<string> {
  const output = await runAspire(['ps', '--format', 'Json']);
  if (!output.success) {
    const detail = decoder.decode(output.stderr).trim() || \`aspire ps exited \${output.code}\`;
    throw new Error(detail);
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(extractJson(decoder.decode(output.stdout)));
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new Error(\`aspire ps JSON was invalid: \${detail}\`);
  }
  if (!Array.isArray(parsed)) throw new Error('aspire ps JSON was not an array');

  const expectedAppHost = await Deno.realPath('aspire/apphost.mts');
  const match = parsed.find((value) => {
    if (!isRecord(value) || typeof value.appHostPath !== 'string') return false;
    return value.appHostPath === expectedAppHost && value.status === 'running';
  });
  if (!isRecord(match) || typeof match.dashboardUrl !== 'string' || match.dashboardUrl.length === 0) {
    throw new Error(\`no running AppHost matched \${expectedAppHost}\`);
  }
  return match.dashboardUrl;
}

function extractJson(text: string): string {
  const trimmed = text.trim();
  if (trimmed.startsWith('[')) return trimmed;
  const arrayStart = trimmed.indexOf('[');
  if (arrayStart < 0) throw new Error('aspire ps did not emit a JSON array');
  return trimmed.slice(arrayStart);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
`;
}
