/** Guidance printed when detached dashboard discovery cannot resolve a URL. */
export const ASPIRE_DASHBOARD_RESOLUTION_GUIDANCE =
  'Try: aspire otel <sub> <resource> --dashboard-url <url>\n' +
  'Try: aspire export --dashboard-url <url> -o <path>';

/** Format the actionable failure emitted by generated Aspire workspace tasks. */
export function formatAspireDashboardResolutionFailure(cause: string): string {
  return `Dashboard URL resolution failed: ${cause}\n${ASPIRE_DASHBOARD_RESOLUTION_GUIDANCE}`;
}

/** Generate the detached Aspire CLI task runner using the shared dashboard reader. */
export function generateAspireCliTaskRunner(): string {
  return `// GENERATED BY @netscript/cli. DO NOT EDIT.
// Resolves detached Aspire dashboard discovery without jq.

import { AspirePsDashboardReader } from '@netscript/mcp';

const guidance = ${JSON.stringify(ASPIRE_DASHBOARD_RESOLUTION_GUIDANCE)};
const [mode, ...rawForwardedArgs] = Deno.args;
const forwardedArgs = rawForwardedArgs[0] === '--' ? rawForwardedArgs.slice(1) : rawForwardedArgs;

if (mode !== 'otel' && mode !== 'export') {
  console.error('Expected task mode "otel" or "export".');
  Deno.exit(2);
}

let primary: Deno.CommandOutput;
try {
  primary = await runAspire([mode, ...forwardedArgs]);
} catch (error) {
  const cause = error instanceof Error ? error.message : String(error);
  console.error(\`Dashboard URL resolution failed: aspire command failed to start: \${cause}\`);
  console.error(guidance);
  Deno.exit(1);
}
await relay(primary);
if (primary.success) Deno.exit(0);
if (hasOption(forwardedArgs, '--dashboard-url')) Deno.exit(primary.code || 1);

try {
  const dashboardUrl = resolveDashboardUrl();
  const fallback = await runAspire([mode, ...forwardedArgs, '--dashboard-url', dashboardUrl]);
  await relay(fallback);
  Deno.exit(fallback.code);
} catch (error) {
  const cause = error instanceof Error ? error.message : String(error);
  console.error(\`Dashboard URL resolution failed: \${cause}\`);
  console.error(guidance);
  Deno.exit(primary.code || 1);
}

async function runAspire(args: string[]): Promise<Deno.CommandOutput> {
  return await new Deno.Command('aspire', {
    args,
    stdout: 'piped',
    stderr: 'piped',
  }).output();
}

async function relay(output: Deno.CommandOutput): Promise<void> {
  if (output.stdout.length > 0) await Deno.stdout.write(output.stdout);
  if (output.stderr.length > 0) await Deno.stderr.write(output.stderr);
}

function resolveDashboardUrl(): string {
  const reader = new AspirePsDashboardReader({ appHostPath: 'aspire/apphost.mts' });
  const dashboardUrl = reader.readDashboardUrl();
  if (!dashboardUrl) throw new Error('no running AppHost matched aspire/apphost.mts');
  return dashboardUrl;
}

function hasOption(args: readonly string[], name: string): boolean {
  return args.some((arg) => arg === name || arg.startsWith(\`\${name}=\`));
}

`;
}
