/**
 * @module templates/workspace/dependency-closure-verifier
 *
 * Generates the app-context preflight that rejects split Fresh/SDK module identities before Vite.
 */

import {
  NETSCRIPT_WEB_RUNTIME_TELEMETRY,
  netScriptWebRuntimeSpecifiers,
} from '../../domain/dependency-closures/netscript-web-runtime-closure.ts';

/** Generate the dependency-free Fresh/SDK closure verifier. */
export function generateDependencyClosureVerifier(): string {
  const requiredSpecifiers = JSON.stringify(netScriptWebRuntimeSpecifiers(), null, 2);
  return `// GENERATED BY @netscript/cli. DO NOT EDIT.
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REQUIRED_SPECIFIERS = ${requiredSpecifiers} as const;
const TELEMETRY_SPECIFIER = '${NETSCRIPT_WEB_RUNTIME_TELEMETRY}';
const EXACT_VERSION = /^\\d+\\.\\d+\\.\\d+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?$/;
const identities: PackageIdentity[] = [];
const reasons: string[] = [];

interface PackageIdentity {
  specifier: string;
  resolution: string;
  packageName: string;
  version: string;
  source: 'jsr' | 'local' | 'unsupported';
  originRoot: string;
}

const appConfig = JSON.parse(await Deno.readTextFile(join(Deno.cwd(), 'deno.json')));
const directImports = appConfig.imports ?? {};
const specifiers = Object.hasOwn(directImports, TELEMETRY_SPECIFIER)
  ? [...REQUIRED_SPECIFIERS, TELEMETRY_SPECIFIER]
  : REQUIRED_SPECIFIERS;

for (const specifier of specifiers) {
  let resolution: string;
  try {
    resolution = import.meta.resolve(specifier);
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    reasons.push(specifier + ' could not be resolved: ' + detail);
    identities.push({
      specifier,
      resolution: '<unresolved>',
      packageName: expectedPackage(specifier),
      version: '<unknown>',
      source: 'unsupported',
      originRoot: '<unresolved>',
    });
    continue;
  }

  const jsr = /^jsr:\\/?(@netscript\\/(?:fresh|sdk|telemetry))@([^/]+)(?:\\/.*)?$/.exec(resolution);
  if (jsr) {
    const version = jsr[2];
    if (!EXACT_VERSION.test(version)) {
      reasons.push(specifier + ' uses non-exact version "' + version + '"; pin this member exactly.');
    }
    identities.push({
      specifier,
      resolution,
      packageName: jsr[1],
      version,
      source: 'jsr',
      originRoot: 'jsr:' + jsr[1] + '@' + version,
    });
    continue;
  }

  if (resolution.startsWith('file:')) {
    const manifest = await findPackageManifest(fileURLToPath(resolution));
    if (manifest) {
      if (!EXACT_VERSION.test(manifest.version)) {
        reasons.push(specifier + ' uses non-exact local version "' + manifest.version + '"; pin this member exactly.');
      }
      identities.push({
        specifier,
        resolution,
        packageName: manifest.name,
        version: manifest.version,
        source: 'local',
        originRoot: manifest.root,
      });
      continue;
    }
  }

  reasons.push(specifier + ' has unsupported resolution "' + resolution + '".');
  identities.push({
    specifier,
    resolution,
    packageName: expectedPackage(specifier),
    version: '<unknown>',
    source: 'unsupported',
    originRoot: resolution,
  });
}

for (const identity of identities) {
  const expected = expectedPackage(identity.specifier);
  if (identity.packageName !== expected) {
    reasons.push(identity.specifier + ' resolves to package ' + identity.packageName + ', expected ' + expected + '.');
  }
}

const supported = identities.filter((identity) => identity.source !== 'unsupported');
const sources = new Set(supported.map((identity) => identity.source));
if (sources.size > 1) reasons.push('closure members mix local and JSR module identities.');

// Version equality is a deliberate proxy for the real Fresh -> SDK graph edge. It is sound only
// while NetScript publishes Fresh, SDK, and telemetry in lockstep.
const versions = new Set(supported.map((identity) => identity.version));
if (versions.size > 1) {
  reasons.push('closure members resolve to different exact versions: ' + [...versions].join(', ') + '.');
}

for (const packageName of ['@netscript/fresh', '@netscript/sdk', '@netscript/telemetry']) {
  const roots = new Set(
    supported.filter((identity) => identity.packageName === packageName).map((identity) =>
      identity.originRoot
    ),
  );
  if (roots.size > 1) reasons.push(packageName + ' resolves from multiple package roots.');
}

if (reasons.length > 0) {
  console.error('NetScript dependency closure is incoherent.');
  for (const identity of identities) {
    console.error('  ' + identity.specifier.padEnd(36) + ' -> ' + identity.resolution);
  }
  for (const reason of reasons) console.error('  reason: ' + reason);
  console.error(
    'Pin @netscript/fresh, all @netscript/fresh/* and @netscript/sdk/* imports, and any direct @netscript/telemetry import to one exact release, then rerun.',
  );
  Deno.exit(1);
}

const release = supported[0]?.version ?? '<unknown>';
const source = supported[0]?.source ?? '<unknown>';
console.log('NetScript dependency closure verified: exact release ' + release + ' (' + source + ').');

function expectedPackage(specifier: string): string {
  if (specifier === TELEMETRY_SPECIFIER) return TELEMETRY_SPECIFIER;
  return specifier.startsWith('@netscript/fresh') ? '@netscript/fresh' : '@netscript/sdk';
}

async function findPackageManifest(path: string): Promise<
  { name: string; version: string; root: string } | undefined
> {
  let directory = dirname(resolve(path));
  while (true) {
    const manifestPath = join(directory, 'deno.json');
    try {
      const manifest = JSON.parse(await Deno.readTextFile(manifestPath));
      if (typeof manifest.name === 'string' && typeof manifest.version === 'string') {
        return { name: manifest.name, version: manifest.version, root: directory };
      }
    } catch (error) {
      if (!(error instanceof Deno.errors.NotFound)) throw error;
    }
    const parent = dirname(directory);
    if (parent === directory) return undefined;
    directory = parent;
  }
}
`;
}
