/**
 * @module templates/workspace/quality-runner
 *
 * Generates the dependency-free scoped quality runner installed in every consumer workspace.
 */

/** Generate the project-local scoped check, lint, and format runner. */
export function generateQualityRunner(): string {
  return String.raw`// GENERATED BY @netscript/cli. DO NOT EDIT.
import { relative, resolve } from 'node:path';

const MODES = ['check', 'lint', 'fmt-check', 'fmt-write'] as const;
type QualityMode = typeof MODES[number];

const SOURCE_ROOTS = [
  '.netscript',
  'apps',
  'aspire/.helpers',
  'contracts',
  'database',
  'plugins',
  'sagas',
  'services',
  'streams',
  'tests',
  'triggers',
  'workers',
] as const;
const SOURCE_FILES = ['aspire/apphost.mts', 'netscript.config.ts'] as const;
const EXTENSIONS = new Set(['ts', 'tsx', 'mts']);
const SKIP_SEGMENTS = new Set([
  '.agents',
  '.aspire',
  '.claude',
  '.data',
  '.git',
  '.llm',
  '.generated',
  'node_modules',
]);
const SKIP_PREFIXES = ['.netscript/generated/'] as const;
const BATCH_SIZE = 200;

interface BatchResult {
  readonly files: readonly string[];
  readonly exitCode: number;
  readonly stdout: string;
  readonly stderr: string;
}

const mode = parseMode(Deno.args[0]);
const projectRoot = resolve(Deno.cwd());
const files = await selectFiles(projectRoot);

if (files.length === 0) {
  console.log(
    JSON.stringify({
      ok: false,
      mode,
      selection: { filesSelected: 0 },
      batches: [],
    }),
  );
  Deno.exit(2);
}

const batches: BatchResult[] = [];
const denoFiles = mode === 'check' ? files.filter((file) => !isAppHostSource(file)) : files;
for (let index = 0; index < denoFiles.length; index += BATCH_SIZE) {
  const batch = denoFiles.slice(index, index + BATCH_SIZE);
  batches.push(await runBatch(mode, projectRoot, batch));
}
if (mode === 'check') {
  const appHostFiles = files.filter(isAppHostSource);
  if (appHostFiles.length > 0) {
    batches.push(await runAppHostCheck(projectRoot, appHostFiles));
  }
}
const ok = batches.every((batch) => batch.exitCode === 0);
console.log(JSON.stringify(
  {
    ok,
    mode,
    selection: { filesSelected: files.length, files },
    batches,
  },
  null,
  2,
));
if (!ok) Deno.exit(1);

function parseMode(value: string | undefined): QualityMode {
  const mode = MODES.find((candidate) => candidate === value);
  if (mode !== undefined) return mode;
  console.error('Usage: quality-runner.ts <check|lint|fmt-check|fmt-write>');
  Deno.exit(2);
}

async function selectFiles(projectRoot: string): Promise<string[]> {
  const selected: string[] = [];
  for (const root of SOURCE_ROOTS) {
    await collect(resolve(projectRoot, root), projectRoot, selected);
  }
  for (const file of SOURCE_FILES) {
    const absolute = resolve(projectRoot, file);
    if (await isFile(absolute)) selected.push(file);
  }
  return [...new Set(selected)].sort();
}

async function collect(
  path: string,
  projectRoot: string,
  selected: string[],
): Promise<void> {
  let entries: Deno.DirEntry[];
  try {
    entries = [];
    for await (const entry of Deno.readDir(path)) entries.push(entry);
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return;
    throw error;
  }
  entries.sort((left, right) => left.name.localeCompare(right.name));
  for (const entry of entries) {
    const child = resolve(path, entry.name);
    const projectRelative = relative(projectRoot, child).replaceAll('\\', '/');
    if (entry.isDirectory) {
      if (shouldSkip(projectRelative)) continue;
      await collect(child, projectRoot, selected);
    } else if (
      entry.isFile && isTypeScript(entry.name) && !shouldSkip(projectRelative)
    ) {
      selected.push(projectRelative);
    }
  }
}

function shouldSkip(path: string): boolean {
  const segments = path.split('/');
  return segments.some((segment) => SKIP_SEGMENTS.has(segment)) ||
    SKIP_PREFIXES.some((prefix) => path.startsWith(prefix));
}

function isTypeScript(name: string): boolean {
  const dot = name.lastIndexOf('.');
  return dot >= 0 && EXTENSIONS.has(name.slice(dot + 1).toLowerCase());
}

function isAppHostSource(path: string): boolean {
  return path === 'aspire/apphost.mts' ||
    (path.startsWith('aspire/.helpers/') && path !== 'aspire/.helpers/run-tool.mts');
}

async function isFile(path: string): Promise<boolean> {
  try {
    return (await Deno.stat(path)).isFile;
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return false;
    throw error;
  }
}

async function runBatch(
  mode: QualityMode,
  projectRoot: string,
  files: readonly string[],
): Promise<BatchResult> {
  const args = mode === 'check'
    ? ['check', '--unstable-kv', ...files]
    : mode === 'lint'
    ? ['lint', '--no-config', '--rules-include=no-explicit-any', ...files]
    : mode === 'fmt-check'
    ? ['fmt', '--check', ...files]
    : ['fmt', ...files];
  const output = await new Deno.Command('deno', {
    args,
    cwd: projectRoot,
    stdout: 'piped',
    stderr: 'piped',
  }).output();
  const decoder = new TextDecoder();
  return {
    files,
    exitCode: output.code,
    stdout: decoder.decode(output.stdout),
    stderr: decoder.decode(output.stderr),
  };
}

async function runAppHostCheck(
  projectRoot: string,
  files: readonly string[],
): Promise<BatchResult> {
  const output = await new Deno.Command('deno', {
    args: [
      'run',
      '--allow-read',
      '--allow-env',
      'aspire/node_modules/typescript/bin/tsc',
      '--noEmit',
      '-p',
      'aspire/tsconfig.apphost.json',
    ],
    cwd: projectRoot,
    stdout: 'piped',
    stderr: 'piped',
  }).output();
  const decoder = new TextDecoder();
  return {
    files,
    exitCode: output.code,
    stdout: decoder.decode(output.stdout),
    stderr: decoder.decode(output.stderr),
  };
}
`;
}
