/**
 * generate-cli-assets-barrel.ts — regenerate the embedded-asset barrels for CLI,
 * plugin, fresh-ui, and service packages (inlined string literals, fmt-canonical).
 *
 * Run via `deno task gen:assets-barrel`. Perms: --allow-read (asset sources),
 * --allow-write (generated barrels), --allow-run (`deno fmt`). Reads/writes only
 * under packages/**.
 *
 * Usage:
 *   deno run --allow-read --allow-write --allow-run \
 *     .llm/tools/generate-cli-assets-barrel.ts
 */

import { TEMPLATE_MANIFEST } from '../../packages/cli/src/kernel/assets/manifest.ts';
import { freshUiRegistryManifest } from '../../packages/fresh-ui/registry.manifest.ts';
import { PLUGIN_SKELETON_TEMPLATES } from '../../packages/plugin/src/kernel/assets/template-registry.ts';

const CLI_OUTPUT_URL = new URL(
  '../../packages/cli/src/kernel/assets/embedded.generated.ts',
  import.meta.url,
);
const PLUGIN_OUTPUT_URL = new URL(
  '../../packages/plugin/src/kernel/assets/embedded.generated.ts',
  import.meta.url,
);
const FRESH_UI_OUTPUT_URL = new URL(
  '../../packages/fresh-ui/registry.generated.ts',
  import.meta.url,
);
const SERVICE_OUTPUT_URL = new URL(
  '../../packages/service/src/primitives/scalar.generated.ts',
  import.meta.url,
);

function importName(index: number): string {
  return `template_${String(index).padStart(3, '0')}`;
}

function toImportSpecifier(path: string): string {
  return path.startsWith('.') ? path : `./${path}`;
}

/**
 * Read an asset's text content so it can be inlined directly into the generated
 * barrel as a string literal. The content is resolved relative to the barrel's
 * own output URL — the same base the previous `with { type: 'text' }` import
 * specifier used — so paths stay identical to the import-attribute mechanism.
 *
 * Inlined string literals replace text imports because `deno publish`'s module
 * graph build never enables `unstable_text_imports`, so `with { type: 'text' }`
 * is rejected at publish time ("The import attribute type of 'text' is
 * unsupported") even though it type-checks and runs locally. Plain string
 * constants carry the same content with no import attribute, so they publish
 * cleanly and behave identically at runtime.
 */
async function readAssetLiteral(baseUrl: URL, specifier: string): Promise<string> {
  const assetUrl = new URL(specifier, baseUrl);
  const content = await Deno.readTextFile(assetUrl);
  return JSON.stringify(content);
}

/**
 * Pipe rendered TypeScript through `deno fmt` (stdin → stdout) so the committed
 * barrel is already fmt-canonical. This keeps `check:assets-barrel` (regen +
 * `git diff --exit-code`) and `fmt:check` green: the generator emits exactly
 * what fmt would produce, including single-quote normalization of the inlined
 * string literals, so regeneration reproduces the file byte-for-byte.
 */
async function formatTypeScript(source: string): Promise<string> {
  const command = new Deno.Command('deno', {
    args: ['fmt', '--ext', 'ts', '-'],
    cwd: new URL('../../', import.meta.url),
    stdin: 'piped',
    stdout: 'piped',
    stderr: 'piped',
  });
  const process = command.spawn();
  const writer = process.stdin.getWriter();
  await writer.write(new TextEncoder().encode(source));
  await writer.close();
  const { code, stdout, stderr } = await process.output();
  if (code !== 0) {
    throw new Error(`deno fmt failed (exit ${code}): ${new TextDecoder().decode(stderr)}`);
  }
  return new TextDecoder().decode(stdout);
}

async function renderCliEmbeddedContent(): Promise<string> {
  const entries: string[] = [];

  for (const [index, item] of TEMPLATE_MANIFEST.entries()) {
    const name = importName(index);
    const literal = await readAssetLiteral(CLI_OUTPUT_URL, toImportSpecifier(item.path));
    entries.push(`const ${name} = ${literal};`);
  }

  const map = TEMPLATE_MANIFEST.map((item, index) =>
    `  ${JSON.stringify(item.key)}: ${importName(index)},`
  );

  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

import type { TemplateKey } from './manifest.ts';

${entries.join('\n')}

/** Embedded text content for every checked-in CLI template asset. */
export const EMBEDDED_TEMPLATE_CONTENT: Record<TemplateKey, string> = {
${map.join('\n')}
};
`;
}

async function renderPluginEmbeddedContent(): Promise<string> {
  const entries: string[] = [];
  const map: string[] = [];

  for (const [index, path] of PLUGIN_SKELETON_TEMPLATES.entries()) {
    const name = importName(index);
    const literal = await readAssetLiteral(PLUGIN_OUTPUT_URL, `../../templates/skeleton/${path}`);
    entries.push(`const ${name} = ${literal};`);
    map.push(`  '${path}': ${name},`);
  }

  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

import type { PluginSkeletonTemplatePath } from './template-registry.ts';

${entries.join('\n')}

/** Embedded text content for every default plugin skeleton template asset. */
export const PLUGIN_SKELETON_TEMPLATE_CONTENT: Record<PluginSkeletonTemplatePath, string> = {
${map.join('\n')}
};
`;
}

async function renderFreshUiRegistryContent(): Promise<string> {
  const paths = [
    ...new Set(
      freshUiRegistryManifest.items.flatMap((item) => item.files.map((file) => file.source)),
    ),
  ].sort((left, right) => left.localeCompare(right));
  const entries: string[] = [];
  const map: string[] = [];

  for (const [index, path] of paths.entries()) {
    const name = importName(index);
    const literal = await readAssetLiteral(FRESH_UI_OUTPUT_URL, `./${path}`);
    entries.push(`const ${name} = ${literal};`);
    map.push(`  '${path}': ${name},`);
  }

  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

${entries.join('\n')}

/** Embedded text content for every file referenced by the Fresh UI registry manifest. */
export const FRESH_UI_REGISTRY_CONTENT: Record<string, string> = {
${map.join('\n')}
};
`;
}

async function renderServiceEmbeddedContent(): Promise<string> {
  const literal = await readAssetLiteral(SERVICE_OUTPUT_URL, '../../assets/scalar.min.js');

  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

/** Embedded bundled Scalar API-reference JS, inlined for JSR-safe runtime serving. */
export const SCALAR_MIN_JS: string = ${literal};
`;
}

if (import.meta.main) {
  if (Deno.args.includes('--help') || Deno.args.includes('-h')) {
    console.log(
      [
        'generate-cli-assets-barrel.ts — regenerate embedded-asset barrels',
        '(CLI, plugin, fresh-ui, service).',
        '',
        'Usage:',
        '  deno run --allow-read --allow-write --allow-run \\',
        '    .llm/tools/generate-cli-assets-barrel.ts',
        '',
        'Takes no flags (other than --help). Rewrites the *.generated.ts barrels in place.',
      ].join('\n'),
    );
    Deno.exit(0);
  }

  await Deno.writeTextFile(
    CLI_OUTPUT_URL,
    await formatTypeScript(await renderCliEmbeddedContent()),
  );
  await Deno.writeTextFile(
    PLUGIN_OUTPUT_URL,
    await formatTypeScript(await renderPluginEmbeddedContent()),
  );
  await Deno.writeTextFile(
    FRESH_UI_OUTPUT_URL,
    await formatTypeScript(await renderFreshUiRegistryContent()),
  );
  await Deno.writeTextFile(
    SERVICE_OUTPUT_URL,
    await formatTypeScript(await renderServiceEmbeddedContent()),
  );
}
