/** Generates registry-safe TypeScript constants for publish-time package assets. */

interface PackageConfig {
  readonly version?: unknown;
}

const ROOT = new URL('../../', import.meta.url);
const CHECK = Deno.args.includes('--check');
const stalePaths: string[] = [];

export const PUBLISH_ASSET_OUTPUTS = [
  'packages/mcp/src/publish-assets.generated.ts',
  'packages/cli/src/kernel/assets/publish-assets.generated.ts',
  'plugins/ai/src/package-metadata.generated.ts',
  'plugins/auth/src/package-metadata.generated.ts',
  'plugins/sagas/src/package-metadata.generated.ts',
  'plugins/streams/src/package-metadata.generated.ts',
  'plugins/triggers/src/package-metadata.generated.ts',
  'plugins/workers/src/package-metadata.generated.ts',
] as const;

async function readVersion(path: string): Promise<string> {
  const config = JSON.parse(await Deno.readTextFile(new URL(path, ROOT))) as PackageConfig;
  if (typeof config.version !== 'string' || !config.version.trim()) {
    throw new Error(`${path} requires a non-empty version`);
  }
  return config.version;
}

function header(): string {
  return `// @generated by .llm/tools/generate-publish-assets.ts
// Do not edit by hand. Run \`deno task gen:publish-assets\`.

`;
}

async function formatTypeScript(source: string): Promise<string> {
  const command = new Deno.Command('deno', {
    args: ['fmt', '--ext', 'ts', '-'],
    cwd: ROOT,
    stdin: 'piped',
    stdout: 'piped',
    stderr: 'piped',
  }).spawn();
  const writer = command.stdin.getWriter();
  await writer.write(new TextEncoder().encode(source));
  await writer.close();
  const { code, stdout, stderr } = await command.output();
  if (code !== 0) {
    throw new Error(`deno fmt failed: ${new TextDecoder().decode(stderr)}`);
  }
  return new TextDecoder().decode(stdout);
}

async function write(path: string, source: string): Promise<void> {
  const expected = await formatTypeScript(`${header()}${source}`);
  const url = new URL(path, ROOT);
  if (CHECK) {
    const actual = await Deno.readTextFile(url).catch(() => '');
    if (actual !== expected) stalePaths.push(path);
    return;
  }
  await Deno.writeTextFile(url, expected);
}

async function generateMcpAssets(): Promise<void> {
  const version = await readVersion('packages/mcp/deno.json');
  const readme = await Deno.readTextFile(new URL('packages/mcp/README.md', ROOT));
  await write(
    'packages/mcp/src/publish-assets.generated.ts',
    `/** Version of the published MCP package. */
export const MCP_PACKAGE_VERSION: string = ${JSON.stringify(version)};

/** Published MCP README embedded as the default documentation corpus. */
export const MCP_PACKAGE_README: string = ${JSON.stringify(readme)};
`,
  );
}

async function generateCliAssets(): Promise<void> {
  const version = await readVersion('packages/cli/deno.json');
  const schema = await Deno.readTextFile(
    new URL('packages/cli/assets/schema/config-file.v1.json', ROOT),
  );
  await write(
    'packages/cli/src/kernel/assets/publish-assets.generated.ts',
    `/** Version of the published CLI package. */
export const CLI_PACKAGE_VERSION: string = ${JSON.stringify(version)};

/** Serialized Deno configuration schema copied into generated workspaces. */
export const DENO_CONFIG_SCHEMA_JSON: string = ${JSON.stringify(schema)};
`,
  );
}

async function generatePluginMetadata(): Promise<void> {
  for (const plugin of ['ai', 'auth', 'sagas', 'streams', 'triggers', 'workers']) {
    const version = await readVersion(`plugins/${plugin}/deno.json`);
    await write(
      `plugins/${plugin}/src/package-metadata.generated.ts`,
      `/** Version of the published plugin package. */
export const PLUGIN_PACKAGE_VERSION: string = ${JSON.stringify(version)};
`,
    );
  }
}

if (import.meta.main) {
  const unknownArgs = Deno.args.filter((arg) => arg !== '--check');
  if (unknownArgs.length > 0) throw new Error(`Unknown argument: ${unknownArgs[0]}`);
  await Promise.all([generateMcpAssets(), generateCliAssets(), generatePluginMetadata()]);
  if (stalePaths.length > 0) {
    throw new Error(
      `publish assets are stale: ${
        stalePaths.sort().join(', ')
      }. Run deno task gen:publish-assets.`,
    );
  }
}
