import { TEMPLATE_MANIFEST } from '../../packages/cli/src/kernel/assets/manifest.ts';
import { PLUGIN_SKELETON_TEMPLATES } from '../../packages/plugin/src/kernel/assets/template-registry.ts';

const CLI_OUTPUT_URL = new URL(
  '../../packages/cli/src/kernel/assets/embedded.generated.ts',
  import.meta.url,
);
const PLUGIN_OUTPUT_URL = new URL(
  '../../packages/plugin/src/kernel/assets/embedded.generated.ts',
  import.meta.url,
);

function importName(index: number): string {
  return `template_${String(index).padStart(3, '0')}`;
}

function toImportSpecifier(path: string): string {
  return path.startsWith('.') ? path : `./${path}`;
}

function renderCliEmbeddedContent(): string {
  const imports: string[] = [];
  const entries: string[] = [];

  for (const [index, item] of TEMPLATE_MANIFEST.entries()) {
    const name = importName(index);
    imports.push(`import ${name} from '${toImportSpecifier(item.path)}' with { type: 'text' };`);
    entries.push(`  ${JSON.stringify(item.key)}: ${name},`);
  }

  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

import type { TemplateKey } from './manifest.ts';
${imports.join('\n')}

/** Embedded text content for every checked-in CLI template asset. */
export const EMBEDDED_TEMPLATE_CONTENT: Record<TemplateKey, string> = {
${entries.join('\n')}
};
`;
}

function renderPluginEmbeddedContent(): string {
  const imports: string[] = [];
  const entries: string[] = [];

  for (const [index, path] of PLUGIN_SKELETON_TEMPLATES.entries()) {
    const name = importName(index);
    const specifier = `../../templates/skeleton/${path}`;
    const importLine = `import ${name} from '${specifier}' with { type: 'text' };`;
    imports.push(
      importLine.length <= 100
        ? importLine
        : `import ${name} from '${specifier}' with {\n  type: 'text',\n};`,
    );
    entries.push(`  '${path}': ${name},`);
  }

  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

import type { PluginSkeletonTemplatePath } from './template-registry.ts';
${imports.join('\n')}

/** Embedded text content for every default plugin skeleton template asset. */
export const PLUGIN_SKELETON_TEMPLATE_CONTENT: Record<PluginSkeletonTemplatePath, string> = {
${entries.join('\n')}
};
`;
}

await Deno.writeTextFile(CLI_OUTPUT_URL, renderCliEmbeddedContent());
await Deno.writeTextFile(PLUGIN_OUTPUT_URL, renderPluginEmbeddedContent());
