/**
 * generate-cli-assets-barrel.ts — regenerate the embedded-asset barrels for CLI,
 * plugin, fresh-ui, and service packages (inlined string literals, fmt-canonical).
 *
 * Run via `deno task gen:assets-barrel`. Perms: --allow-read (asset sources),
 * --allow-write (generated barrels), --allow-run (`deno fmt`). Reads/writes only
 * under packages/**.
 *
 * Usage:
 *   deno run --allow-read --allow-write --allow-run \
 *     .llm/tools/generate-cli-assets-barrel.ts
 */

import { TEMPLATE_MANIFEST } from '../../packages/cli/src/kernel/assets/manifest.ts';
import { freshUiRegistryManifest } from '../../packages/fresh-ui/registry.manifest.ts';
import { PLUGIN_SKELETON_TEMPLATES } from '../../packages/plugin/src/kernel/assets/template-registry.ts';
import { encodeBase64 } from 'jsr:@std/encoding@^1.0.10/base64';

const CLI_OUTPUT_URL = new URL(
  '../../packages/cli/src/kernel/assets/embedded.generated.ts',
  import.meta.url,
);
const PLUGIN_OUTPUT_URL = new URL(
  '../../packages/plugin/src/kernel/assets/embedded.generated.ts',
  import.meta.url,
);
const FRESH_UI_OUTPUT_URL = new URL(
  '../../packages/fresh-ui/registry.generated.ts',
  import.meta.url,
);
const SERVICE_OUTPUT_URL = new URL(
  '../../packages/service/src/primitives/scalar.generated.ts',
  import.meta.url,
);
const SKILL_OUTPUT_URL = new URL(
  '../../packages/cli/src/kernel/assets/skills.generated.ts',
  import.meta.url,
);
const SKILL_MANIFEST_URL = new URL(
  '../../skills/manifest.json',
  import.meta.url,
);
const AGENT_TOOL_MANIFEST_URL = new URL(
  './consumer-tools.json',
  import.meta.url,
);
const AGENT_TOOL_README_URL = new URL(
  './consumer-README.md',
  import.meta.url,
);
const AGENT_TOOL_OUTPUT_URL = new URL(
  '../../packages/cli/src/kernel/assets/agent-tools.generated.ts',
  import.meta.url,
);
const AGENT_DOCS_OUTPUT_URL = new URL(
  '../../packages/cli/src/kernel/assets/agent-docs.generated.ts',
  import.meta.url,
);

function importName(index: number): string {
  return `template_${String(index).padStart(3, '0')}`;
}

function toImportSpecifier(path: string): string {
  return path.startsWith('.') ? path : `./${path}`;
}

/**
 * Read an asset's text content so it can be inlined directly into the generated
 * barrel as a string literal. The content is resolved relative to the barrel's
 * own output URL — the same base the previous `with { type: 'text' }` import
 * specifier used — so paths stay identical to the import-attribute mechanism.
 *
 * Inlined string literals replace text imports because `deno publish`'s module
 * graph build never enables `unstable_text_imports`, so `with { type: 'text' }`
 * is rejected at publish time ("The import attribute type of 'text' is
 * unsupported") even though it type-checks and runs locally. Plain string
 * constants carry the same content with no import attribute, so they publish
 * cleanly and behave identically at runtime.
 */
async function readAssetLiteral(
  baseUrl: URL,
  specifier: string,
): Promise<string> {
  const assetUrl = new URL(specifier, baseUrl);
  const content = await Deno.readTextFile(assetUrl);
  return JSON.stringify(content);
}

/**
 * Pipe rendered TypeScript through `deno fmt` (stdin → stdout) so the committed
 * barrel is already fmt-canonical. This keeps `check:assets-barrel` (regen +
 * `git diff --exit-code`) and `fmt:check` green: the generator emits exactly
 * what fmt would produce, including single-quote normalization of the inlined
 * string literals, so regeneration reproduces the file byte-for-byte.
 */
async function formatTypeScript(source: string): Promise<string> {
  const command = new Deno.Command('deno', {
    args: ['fmt', '--ext', 'ts', '-'],
    cwd: new URL('../../', import.meta.url),
    stdin: 'piped',
    stdout: 'piped',
    stderr: 'piped',
  });
  const process = command.spawn();
  const writer = process.stdin.getWriter();
  await writer.write(new TextEncoder().encode(source));
  await writer.close();
  const { code, stdout, stderr } = await process.output();
  if (code !== 0) {
    throw new Error(
      `deno fmt failed (exit ${code}): ${new TextDecoder().decode(stderr)}`,
    );
  }
  return new TextDecoder().decode(stdout);
}

async function renderCliEmbeddedContent(): Promise<string> {
  const entries: string[] = [];

  for (const [index, item] of TEMPLATE_MANIFEST.entries()) {
    const name = importName(index);
    const literal = await readAssetLiteral(
      CLI_OUTPUT_URL,
      toImportSpecifier(item.path),
    );
    entries.push(`const ${name} = ${literal};`);
  }

  const map = TEMPLATE_MANIFEST.map((item, index) =>
    `  ${JSON.stringify(item.key)}: ${importName(index)},`
  );

  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

import type { TemplateKey } from './manifest.ts';

${entries.join('\n')}

/** Embedded text content for every checked-in CLI template asset. */
export const EMBEDDED_TEMPLATE_CONTENT: Record<TemplateKey, string> = {
${map.join('\n')}
};
`;
}

async function renderPluginEmbeddedContent(): Promise<string> {
  const entries: string[] = [];
  const map: string[] = [];

  for (const [index, path] of PLUGIN_SKELETON_TEMPLATES.entries()) {
    const name = importName(index);
    const literal = await readAssetLiteral(
      PLUGIN_OUTPUT_URL,
      `../../templates/skeleton/${path}`,
    );
    entries.push(`const ${name} = ${literal};`);
    map.push(`  '${path}': ${name},`);
  }

  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

import type { PluginSkeletonTemplatePath } from './template-registry.ts';

${entries.join('\n')}

/** Embedded text content for every default plugin skeleton template asset. */
export const PLUGIN_SKELETON_TEMPLATE_CONTENT: Record<PluginSkeletonTemplatePath, string> = {
${map.join('\n')}
};
`;
}

async function renderFreshUiRegistryContent(): Promise<string> {
  const paths = [
    ...new Set(
      freshUiRegistryManifest.items.flatMap((item) => item.files.map((file) => file.source)),
    ),
  ].sort((left, right) => left.localeCompare(right));
  const entries: string[] = [];
  const map: string[] = [];

  for (const [index, path] of paths.entries()) {
    const name = importName(index);
    const literal = await readAssetLiteral(FRESH_UI_OUTPUT_URL, `./${path}`);
    entries.push(`const ${name} = ${literal};`);
    map.push(`  '${path}': ${name},`);
  }

  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

${entries.join('\n')}

/** Embedded text content for every file referenced by the Fresh UI registry manifest. */
export const FRESH_UI_REGISTRY_CONTENT: Record<string, string> = {
${map.join('\n')}
};
`;
}

async function renderServiceEmbeddedContent(): Promise<string> {
  const literal = await readAssetLiteral(
    SERVICE_OUTPUT_URL,
    '../../assets/scalar.min.js',
  );

  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

/** Embedded bundled Scalar API-reference JS, inlined for JSR-safe runtime serving. */
export const SCALAR_MIN_JS: string = ${literal};
`;
}

async function renderSkillEmbeddedContent(): Promise<string> {
  const manifestText = await Deno.readTextFile(SKILL_MANIFEST_URL);
  const manifest = JSON.parse(manifestText) as {
    readonly files: readonly string[];
  };
  const files: Record<string, string> = {};
  for (const path of manifest.files) {
    files[path] = path === 'manifest.json' ? manifestText : await Deno.readTextFile(
      new URL(`../../skills/${path}`, import.meta.url),
    );
  }
  const canonical = manifest.files.map((path) => `${path}\0${files[path]}`)
    .join('\0');
  const hashBytes = await crypto.subtle.digest(
    'SHA-256',
    new TextEncoder().encode(canonical),
  );
  const hash = [...new Uint8Array(hashBytes)].map((byte) => byte.toString(16).padStart(2, '0'))
    .join('');
  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

/** Paths and content of the published NetScript agent skill bundle. */
export const EMBEDDED_SKILL_FILES: Readonly<Record<string, string>> = ${JSON.stringify(files)};

/** SHA-256 of canonical manifest-ordered skill paths and content. */
export const EMBEDDED_SKILL_BUNDLE_HASH: string = '${hash}';
`;
}

/** Source files and canonical path order used to render the embedded agent-tool bundle. */
export interface AgentToolEmbeddedBundle {
  readonly files: Readonly<Record<string, string>>;
  readonly orderedPaths: readonly string[];
}

interface AgentToolManifestFile {
  readonly source: string;
  readonly path: string;
}

interface AgentToolManifest {
  readonly schemaVersion: number;
  readonly supportFiles: readonly string[];
  readonly modules: readonly AgentToolManifestFile[];
  readonly tools: readonly AgentToolManifestFile[];
}

/** Read the exact consumer agent-tool bundle inputs used by the generated CLI barrel. */
export async function readAgentToolEmbeddedBundle(): Promise<AgentToolEmbeddedBundle> {
  const cliManifest = JSON.parse(
    await Deno.readTextFile(new URL('../../packages/cli/deno.json', import.meta.url)),
  ) as { readonly version: string };
  const manifestText = await Deno.readTextFile(AGENT_TOOL_MANIFEST_URL);
  const manifest = JSON.parse(manifestText) as AgentToolManifest;
  if (manifest.schemaVersion !== 2) {
    throw new Error(`consumer-tools.json must use schemaVersion 2, got ${manifest.schemaVersion}`);
  }
  const files: Record<string, string> = {
    'consumer-tools.json': manifestText,
    'README.md': await Deno.readTextFile(AGENT_TOOL_README_URL),
    'release.json': `${
      JSON.stringify({ cli: `jsr:@netscript/cli@${cliManifest.version}` }, null, 2)
    }\n`,
  };
  for (const file of [...manifest.modules, ...manifest.tools]) {
    files[file.path] = await Deno.readTextFile(
      new URL(`../../${file.source}`, import.meta.url),
    );
  }
  const orderedPaths = [
    ...manifest.supportFiles,
    ...manifest.modules.map((module) => module.path),
    ...manifest.tools.map((tool) => tool.path),
  ];
  return { files, orderedPaths };
}

async function renderAgentToolEmbeddedContent(): Promise<string> {
  const { files, orderedPaths } = await readAgentToolEmbeddedBundle();
  const canonical = orderedPaths.map((path) => `${path}\0${files[path] ?? ''}`).join('\0');
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(canonical));
  const hash = [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join(
    '',
  );
  const staticFiles = Object.fromEntries(
    Object.entries(files).filter(([path]) => path !== 'release.json'),
  );
  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

import { netscriptJsrSpecifier } from '../constants/jsr-specifiers.ts';

const EMBEDDED_AGENT_TOOL_STATIC_FILES: Readonly<Record<string, string>> = ${
    JSON.stringify(staticFiles)
  };

/** Paths and content of the published consumer agent-tool bundle. */
export const EMBEDDED_AGENT_TOOL_FILES: Readonly<Record<string, string>> = {
  ...EMBEDDED_AGENT_TOOL_STATIC_FILES,
  'release.json': JSON.stringify({ cli: netscriptJsrSpecifier('cli') }, null, 2) + '\\n',
};

/** Manifest-ordered installed paths in the consumer agent-tool bundle. */
export const EMBEDDED_AGENT_TOOL_PATHS: readonly string[] = ${JSON.stringify(orderedPaths)};

/** SHA-256 of canonical manifest-ordered agent-tool paths and content. */
export const EMBEDDED_AGENT_TOOL_BUNDLE_HASH: string = '${hash}';
`;
}

async function readPackageExportMap(): Promise<Readonly<Record<string, readonly string[]>>> {
  const exportMap: Record<string, readonly string[]> = {};
  for (const parent of ['../../packages', '../../plugins']) {
    const parentUrl = new URL(`${parent}/`, import.meta.url);
    for await (const entry of Deno.readDir(parentUrl)) {
      if (!entry.isDirectory) continue;
      const manifestUrl = new URL(`${entry.name}/deno.json`, parentUrl);
      let manifest: {
        readonly name?: string;
        readonly publish?: false | unknown;
        readonly exports?: string | Readonly<Record<string, string>>;
      };
      try {
        manifest = JSON.parse(await Deno.readTextFile(manifestUrl));
      } catch (error) {
        if (error instanceof Deno.errors.NotFound) continue;
        throw error;
      }
      if (!manifest.name?.startsWith('@netscript/') || manifest.publish === false) continue;
      const subpaths = typeof manifest.exports === 'string'
        ? ['.']
        : Object.keys(manifest.exports ?? {}).sort();
      if (subpaths.length > 0) exportMap[manifest.name] = subpaths;
    }
  }
  return Object.fromEntries(
    Object.entries(exportMap).sort(([left], [right]) => left.localeCompare(right)),
  );
}

/** Validated shared prose bytes and provenance consumed by the generated CLI fallback. */
export interface AgentDocsEmbeddedBundle {
  readonly compressed: Uint8Array;
  readonly provenance: {
    readonly schemaVersion: number;
    readonly version: string;
    readonly sourceCommit: string;
    readonly extractionTimestamp: string;
    readonly files: readonly string[];
    readonly uncompressedBytes: number;
    readonly compressedBytes: number;
    readonly sha256: string;
  };
}

/** Read the exact shared corpus bytes used by the CLI generator and verify their provenance. */
export async function readAgentDocsEmbeddedBundle(
  root: URL = new URL('../../', import.meta.url),
): Promise<AgentDocsEmbeddedBundle> {
  const cliManifest = JSON.parse(
    await Deno.readTextFile(new URL('packages/cli/deno.json', root)),
  ) as { readonly version: string };
  const provenance = JSON.parse(
    await Deno.readTextFile(new URL('.llm/assets/agent-docs/provenance.json', root)),
  ) as AgentDocsEmbeddedBundle['provenance'];
  if (provenance.version !== cliManifest.version) {
    throw new Error(
      `Agent docs prose ${provenance.version} does not match CLI ${cliManifest.version}`,
    );
  }
  const compressed = await Deno.readFile(new URL('.llm/assets/agent-docs/prose.json.gz', root));
  const copy = new Uint8Array(compressed);
  const stream = new Blob([copy.buffer]).stream().pipeThrough(new DecompressionStream('gzip'));
  const uncompressed = new Uint8Array(await new Response(stream).arrayBuffer());
  const digest = await crypto.subtle.digest('SHA-256', uncompressed.buffer);
  const hash = [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join(
    '',
  );
  if (hash !== provenance.sha256 || uncompressed.byteLength !== provenance.uncompressedBytes) {
    throw new Error('Agent docs canonical prose does not match provenance.json');
  }
  return { compressed, provenance };
}

async function renderAgentDocsEmbeddedContent(): Promise<string> {
  const { compressed, provenance } = await readAgentDocsEmbeddedBundle();
  const exportMap = await readPackageExportMap();
  return `// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run \`deno task gen:assets-barrel\`.

/** Gzip-compressed canonical offline prose bundle, encoded as base64 for JSR publication. */
export const EMBEDDED_AGENT_DOCS_GZIP_BASE64: string = ${JSON.stringify(encodeBase64(compressed))};

/** Release-build provenance for the embedded prose bundle. */
export const EMBEDDED_AGENT_DOCS_PROVENANCE = ${JSON.stringify(provenance)} as const;

/** Same-release package export subpaths used for exact installed-version API generation. */
export const EMBEDDED_AGENT_DOCS_PACKAGE_EXPORTS: Readonly<Record<string, readonly string[]>> = ${
    JSON.stringify(exportMap)
  };
`;
}

async function writeOrCheckGeneratedAsset(
  output: URL,
  expected: string,
  check: boolean,
): Promise<void> {
  if (check) {
    const actual = await Deno.readTextFile(output).catch(() => '');
    if (actual !== expected) {
      throw new Error(`${output.pathname} is stale; run deno task gen:assets-barrel`);
    }
    return;
  }
  await Deno.writeTextFile(output, expected);
}

if (import.meta.main) {
  if (Deno.args.includes('--help') || Deno.args.includes('-h')) {
    console.log(
      [
        'generate-cli-assets-barrel.ts — regenerate embedded-asset barrels',
        '(CLI, plugin, fresh-ui, service).',
        '',
        'Usage:',
        '  deno run --allow-read --allow-write --allow-run \\',
        '    .llm/tools/generate-cli-assets-barrel.ts',
        '',
        '--check compares every generated barrel without writing it.',
        'Without --check, rewrites the *.generated.ts barrels in place.',
      ].join('\n'),
    );
    Deno.exit(0);
  }
  const check = Deno.args.includes('--check');
  const unknownArgs = Deno.args.filter((arg) => arg !== '--check');
  if (unknownArgs.length > 0) throw new Error(`Unknown argument: ${unknownArgs[0]}`);

  await writeOrCheckGeneratedAsset(
    CLI_OUTPUT_URL,
    await formatTypeScript(await renderCliEmbeddedContent()),
    check,
  );
  await writeOrCheckGeneratedAsset(
    PLUGIN_OUTPUT_URL,
    await formatTypeScript(await renderPluginEmbeddedContent()),
    check,
  );
  await writeOrCheckGeneratedAsset(
    FRESH_UI_OUTPUT_URL,
    await formatTypeScript(await renderFreshUiRegistryContent()),
    check,
  );
  await writeOrCheckGeneratedAsset(
    SERVICE_OUTPUT_URL,
    await formatTypeScript(await renderServiceEmbeddedContent()),
    check,
  );
  await writeOrCheckGeneratedAsset(
    SKILL_OUTPUT_URL,
    await formatTypeScript(await renderSkillEmbeddedContent()),
    check,
  );
  await writeOrCheckGeneratedAsset(
    AGENT_TOOL_OUTPUT_URL,
    await formatTypeScript(await renderAgentToolEmbeddedContent()),
    check,
  );
  await writeOrCheckGeneratedAsset(
    AGENT_DOCS_OUTPUT_URL,
    await formatTypeScript(await renderAgentDocsEmbeddedContent()),
    check,
  );
}
