/** Generates registry-safe TypeScript constants for publish-time package assets. */

import { AGENT_DOCS_PAGE_CARRIER, readAgentDocsPages } from './docs/agent-docs-page-carrier.ts';
import { normalizeDocsSlug } from '../../packages/mcp/src/domain/docs/docs-corpus-port.ts';
import { rewriteNetScriptVersion } from './deps/bump-version.ts';

interface PackageConfig {
  readonly version?: unknown;
}

const ROOT = new URL('../../', import.meta.url);
const CHECK = Deno.args.includes('--check');
const stalePaths: string[] = [];

/** Golden-path prose embedded in the MCP package when no filesystem corpus resolves. */
export const MCP_EMBEDDED_DOC_PATHS = [
  'llms.txt',
  'pages/durable-workflows/how-to/bound-stream-retention/index.md',
  'pages/explanation/contracts/index.md',
  'pages/explanation/plugin-system/index.md',
  'pages/orchestration-runtime/how-to/author-a-plugin/index.md',
  'pages/data-persistence/how-to/use-a-second-database/index.md',
  'pages/services-sdk/services/index.md',
  'pages/web-layer/builders/index.md',
  'pages/web-layer/how-to/build-a-server-validated-form/index.md',
  'pages/web-layer/query/index.md',
  'pages/web-layer/route/index.md',
  'pages/tutorials/live-dashboard/03-sdk-cache-first-query/index.md',
  'pages/tutorials/live-dashboard/04-definePage-QueryIsland/index.md',
] as const;

/**
 * Maximum UTF-8 source bytes accepted for the generated MCP fallback prose.
 * 288 KiB: #1383 required the guarded plugin-service example on the embedded
 * plugin-system page (258 KiB), and the streams retention recipe is embedded
 * alone rather than the entire streams reference page.
 */
export const MCP_EMBEDDED_DOCS_MAX_BYTES = 294_912;

export const PUBLISH_ASSET_OUTPUTS: readonly string[] = [
  AGENT_DOCS_PAGE_CARRIER,
  'packages/cli/src/kernel/assets/llms-policy.generated.ts',
  '.llm/assets/agent-docs/provenance.json',
  'packages/cli/src/kernel/assets/agent-tools.generated.ts',
  'packages/cli/src/kernel/assets/agent-docs.generated.ts',
  'packages/cli/src/kernel/assets/embedded.generated.ts',
  'packages/cli/src/kernel/assets/skills.generated.ts',
  'packages/plugin/src/kernel/assets/embedded.generated.ts',
  'packages/fresh-ui/registry.generated.ts',
  'packages/service/src/primitives/scalar.generated.ts',
  'packages/mcp/src/publish-assets.generated.ts',
  'packages/cli/src/kernel/assets/publish-assets.generated.ts',
  'packages/fresh-ui/src/package-metadata.generated.ts',
  'packages/plugin-sagas-core/src/package-metadata.generated.ts',
  'packages/plugin-streams-core/src/package-metadata.generated.ts',
  'plugins/ai/src/package-metadata.generated.ts',
  'plugins/auth/src/package-metadata.generated.ts',
  'plugins/sagas/src/package-metadata.generated.ts',
  'plugins/streams/src/package-metadata.generated.ts',
  'plugins/triggers/src/package-metadata.generated.ts',
  'plugins/workers/src/package-metadata.generated.ts',
] as const;

interface AgentDocsProvenance {
  readonly schemaVersion: 1;
  readonly version: string;
  readonly sourceCommit: string;
  readonly extractionTimestamp: string;
  readonly files: readonly string[];
  readonly uncompressedBytes: number;
  readonly compressedBytes: number;
  readonly sha256: string;
}

interface AgentDocsPayload {
  readonly schemaVersion: 1;
  readonly files: Readonly<Record<string, string>>;
}

/** One generated fallback source and its stable filesystem-compatible slug. */
export interface GeneratedMcpEmbeddedDoc {
  readonly path: string;
  readonly slug: string;
  readonly source: string;
}

/** Release provenance emitted beside the selected fallback prose. */
export interface GeneratedMcpEmbeddedDocsProvenance {
  readonly schemaVersion: 1;
  readonly frameworkVersion: string;
  readonly sourceCommit: string;
  readonly paths: readonly string[];
  readonly sourceBytes: number;
  readonly documentCount: number;
  readonly sha256: string;
}

/** Selected MCP prose and reproducible provenance generated from the release docs artifact. */
export interface GeneratedMcpEmbeddedDocs {
  readonly documents: readonly GeneratedMcpEmbeddedDoc[];
  readonly provenance: GeneratedMcpEmbeddedDocsProvenance;
}

async function readVersion(path: string, root: URL = ROOT): Promise<string> {
  const config = JSON.parse(await Deno.readTextFile(new URL(path, root))) as PackageConfig;
  if (typeof config.version !== 'string' || !config.version.trim()) {
    throw new Error(`${path} requires a non-empty version`);
  }
  return config.version;
}

function header(): string {
  return `// @generated by .llm/tools/generate-publish-assets.ts
// Do not edit by hand. Run \`deno task gen:publish-assets\`.

`;
}

async function formatTypeScript(source: string): Promise<string> {
  const command = new Deno.Command('deno', {
    args: ['fmt', '--ext', 'ts', '-'],
    cwd: ROOT,
    stdin: 'piped',
    stdout: 'piped',
    stderr: 'piped',
  }).spawn();
  const writer = command.stdin.getWriter();
  await writer.write(new TextEncoder().encode(source));
  await writer.close();
  const { code, stdout, stderr } = await command.output();
  if (code !== 0) {
    throw new Error(`deno fmt failed: ${new TextDecoder().decode(stderr)}`);
  }
  return new TextDecoder().decode(stdout);
}

async function decompressGzip(compressed: Uint8Array): Promise<Uint8Array> {
  const copied = copiedBuffer(compressed);
  const stream = new Blob([copied]).stream().pipeThrough(new DecompressionStream('gzip'));
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

async function compressGzip(uncompressed: Uint8Array): Promise<Uint8Array> {
  const copied = copiedBuffer(uncompressed);
  const stream = new Blob([copied]).stream().pipeThrough(new CompressionStream('gzip'));
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

function bytesEqual(left: Uint8Array, right: Uint8Array): boolean {
  return left.byteLength === right.byteLength && left.every((byte, index) => byte === right[index]);
}

function recordStalePath(foundStalePaths: string[], path: string): void {
  if (!foundStalePaths.includes(path)) foundStalePaths.push(path);
}

function closeAgentDocsProvenance(
  value: unknown,
  overrides: Partial<
    Pick<AgentDocsProvenance, 'version' | 'uncompressedBytes' | 'compressedBytes' | 'sha256'>
  > = {},
): AgentDocsProvenance {
  if (
    typeof value !== 'object' || value === null || Array.isArray(value) ||
    Reflect.get(value, 'schemaVersion') !== 1 ||
    typeof Reflect.get(value, 'version') !== 'string' ||
    typeof Reflect.get(value, 'sourceCommit') !== 'string' ||
    typeof Reflect.get(value, 'extractionTimestamp') !== 'string' ||
    !Array.isArray(Reflect.get(value, 'files')) ||
    !(Reflect.get(value, 'files') as unknown[]).every((path) => typeof path === 'string') ||
    typeof Reflect.get(value, 'uncompressedBytes') !== 'number' ||
    typeof Reflect.get(value, 'compressedBytes') !== 'number' ||
    typeof Reflect.get(value, 'sha256') !== 'string'
  ) {
    throw new Error('agent docs provenance must contain the complete schema-version 1 field set');
  }
  return {
    schemaVersion: 1,
    version: overrides.version ?? String(Reflect.get(value, 'version')),
    sourceCommit: String(Reflect.get(value, 'sourceCommit')),
    extractionTimestamp: String(Reflect.get(value, 'extractionTimestamp')),
    files: [...Reflect.get(value, 'files') as string[]],
    uncompressedBytes: overrides.uncompressedBytes ??
      Number(Reflect.get(value, 'uncompressedBytes')),
    compressedBytes: overrides.compressedBytes ?? Number(Reflect.get(value, 'compressedBytes')),
    sha256: overrides.sha256 ?? String(Reflect.get(value, 'sha256')),
  };
}

async function write(
  path: string,
  source: string,
  root: URL = ROOT,
  check: boolean = CHECK,
  foundStalePaths: string[] = stalePaths,
): Promise<void> {
  const expected = await formatTypeScript(`${header()}${source}`);
  const url = new URL(path, root);
  if (check) {
    const actual = await Deno.readTextFile(url).catch(() => '');
    if (actual !== expected) foundStalePaths.push(path);
    return;
  }
  await Deno.writeTextFile(url, expected);
}

/** Refresh the release identity in the checked-in docs provenance before embedding it in the CLI. */
export async function refreshAgentDocsProvenance(
  root: URL = ROOT,
  check: boolean = CHECK,
): Promise<string> {
  const version = await readVersionFromRoot(root, 'packages/cli/deno.json');
  const path = '.llm/assets/agent-docs/provenance.json';
  const url = new URL(path, root);
  const parsed: unknown = JSON.parse(await Deno.readTextFile(url));
  if (
    typeof parsed !== 'object' || parsed === null || Reflect.get(parsed, 'schemaVersion') !== 1 ||
    typeof Reflect.get(parsed, 'version') !== 'string'
  ) throw new Error('Agent docs provenance must use schema version 1');
  const provenance = parsed as { readonly version: string };
  const legacy = Reflect.get(parsed as object, 'sha256');
  const expected = `${
    JSON.stringify(
      typeof legacy === 'string'
        ? closeAgentDocsProvenance(parsed, { version })
        : { schemaVersion: 1, version },
      null,
      2,
    )
  }\n`;
  if (check) {
    if (await Deno.readTextFile(url) !== expected) recordStalePath(stalePaths, path);
    return provenance.version;
  }
  await Deno.writeTextFile(url, expected);
  return provenance.version;
}

/**
 * Apply the legacy literal corpus rewrite for differential tests and recovery diagnostics.
 * Release writers must render the docs site instead: literal rewriting misses rendered version
 * prose and is intentionally absent from `generatePublishAssets`.
 */
export async function rebaseAgentDocsProse(
  oldVersion: string,
  root: URL = ROOT,
  check: boolean = CHECK,
  foundStalePaths: string[] = stalePaths,
): Promise<void> {
  const version = await readVersionFromRoot(root, 'packages/cli/deno.json');
  const prosePath = '.llm/assets/agent-docs/prose.json.gz';
  const provenancePath = '.llm/assets/agent-docs/provenance.json';
  const proseUrl = new URL(prosePath, root);
  const provenanceUrl = new URL(provenancePath, root);
  const compressed = await Deno.readFile(proseUrl);
  const uncompressed = await decompressGzip(compressed);
  const payload = JSON.parse(new TextDecoder().decode(uncompressed)) as AgentDocsPayload;
  if (payload.schemaVersion !== 1 || !payload.files || typeof payload.files !== 'object') {
    throw new Error('agent docs prose payload must use schema version 1');
  }
  const files = Object.fromEntries(
    Object.entries(payload.files).map(([path, source]) => [
      path,
      rewriteNetScriptVersion(source, oldVersion, version),
    ]),
  );
  const nextUncompressed = new TextEncoder().encode(JSON.stringify({ schemaVersion: 1, files }));
  const nextCompressed = bytesEqual(nextUncompressed, uncompressed)
    ? compressed
    : await compressGzip(nextUncompressed);
  const provenance = closeAgentDocsProvenance(
    JSON.parse(await Deno.readTextFile(provenanceUrl)) as unknown,
  );
  const nextProvenance = `${
    JSON.stringify(
      closeAgentDocsProvenance(provenance, {
        version,
        uncompressedBytes: nextUncompressed.byteLength,
        compressedBytes: nextCompressed.byteLength,
        sha256: hex(await crypto.subtle.digest('SHA-256', copiedBuffer(nextUncompressed))),
      }),
      null,
      2,
    )
  }\n`;

  if (check) {
    if (!bytesEqual(compressed, nextCompressed)) recordStalePath(foundStalePaths, prosePath);
    if (await Deno.readTextFile(provenanceUrl) !== nextProvenance) {
      recordStalePath(foundStalePaths, provenancePath);
    }
    return;
  }
  await Deno.writeFile(proseUrl, nextCompressed);
  await Deno.writeTextFile(provenanceUrl, nextProvenance);
}

async function readVersionFromRoot(root: URL, path: string): Promise<string> {
  const config = JSON.parse(await Deno.readTextFile(new URL(path, root))) as PackageConfig;
  if (typeof config.version !== 'string' || !config.version.trim()) {
    throw new Error(`${path} requires a non-empty version`);
  }
  return config.version;
}

/** Read and validate the bounded MCP prose selection from the release docs bundle. */
export async function buildMcpEmbeddedDocs(root: URL = ROOT): Promise<GeneratedMcpEmbeddedDocs> {
  const frameworkVersion = await readVersionFromRoot(root, 'packages/mcp/deno.json');
  const provenancePath = '.llm/assets/agent-docs/provenance.json';
  const releaseProvenance = JSON.parse(
    await Deno.readTextFile(new URL(provenancePath, root)),
  ) as AgentDocsProvenance;
  if (
    releaseProvenance.schemaVersion !== 1 || releaseProvenance.version !== frameworkVersion ||
    typeof releaseProvenance.version !== 'string'
  ) {
    throw new Error(`${provenancePath} must match MCP framework version ${frameworkVersion}`);
  }
  let payload: AgentDocsPayload;
  try {
    payload = {
      schemaVersion: 1,
      files: await readAgentDocsPages(new URL(AGENT_DOCS_PAGE_CARRIER, root), frameworkVersion),
    };
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
    const compressed = await Deno.readFile(new URL('.llm/assets/agent-docs/prose.json.gz', root));
    payload = JSON.parse(
      new TextDecoder().decode(await decompressGzip(compressed)),
    ) as AgentDocsPayload;
  }
  if (payload.schemaVersion !== 1 || !payload.files || typeof payload.files !== 'object') {
    throw new Error('agent docs prose payload must use schema version 1');
  }
  const documents = MCP_EMBEDDED_DOC_PATHS.map((path) => {
    const source = payload.files[path];
    if (typeof source !== 'string') throw new Error(`agent docs prose payload is missing ${path}`);
    return { path, slug: normalizeDocsSlug(path), source };
  });
  const canonical = documents.map(({ path, source }) => `${path}\0${source}`).join('\0');
  const sourceBytes = documents.reduce(
    (total, document) => total + new TextEncoder().encode(document.source).byteLength,
    0,
  );
  if (sourceBytes > MCP_EMBEDDED_DOCS_MAX_BYTES) {
    throw new Error(
      `MCP embedded docs are ${sourceBytes} bytes; budget is ${MCP_EMBEDDED_DOCS_MAX_BYTES}`,
    );
  }
  const canonicalBytes = new TextEncoder().encode(canonical);
  return {
    documents,
    provenance: {
      schemaVersion: 1,
      frameworkVersion,
      sourceCommit: 'content-addressed',
      paths: [...MCP_EMBEDDED_DOC_PATHS],
      sourceBytes,
      documentCount: documents.length,
      sha256: hex(await crypto.subtle.digest('SHA-256', copiedBuffer(canonicalBytes))),
    },
  };
}

export async function generateMcpAssets(
  root: URL = ROOT,
  check: boolean = CHECK,
  foundStalePaths: string[] = stalePaths,
): Promise<void> {
  const version = await readVersion('packages/mcp/deno.json', root);
  const readme = await Deno.readTextFile(new URL('packages/mcp/README.md', root));
  const current = await Deno.readTextFile(
    new URL('packages/mcp/src/publish-assets.generated.ts', root),
  ).catch(() => '');
  const previous = current.match(/MCP_PACKAGE_README_GZIP_BASE64: string =\s*("[^"]*"|'[^']*')/)
    ?.[1];
  let readmeCompressed: Uint8Array | undefined;
  if (previous) {
    try {
      const bytes = Uint8Array.fromBase64(previous.slice(1, -1));
      if (new TextDecoder().decode(await decompressGzip(bytes)) === readme) {
        readmeCompressed = bytes;
      }
    } catch { /* Regenerate a corrupt transport. */ }
  }
  readmeCompressed ??= await compressGzip(new TextEncoder().encode(readme));
  const embedded = await buildMcpEmbeddedDocs(root);
  await write(
    'packages/mcp/src/publish-assets.generated.ts',
    `/** Version of the published MCP package. */
export const MCP_PACKAGE_VERSION: string = ${JSON.stringify(version)};

/** Published MCP README embedded as the default documentation corpus. */
const MCP_PACKAGE_README_GZIP_BASE64: string = ${JSON.stringify(readmeCompressed.toBase64())};
export const MCP_PACKAGE_README: string = await new Response(new Blob([Uint8Array.fromBase64(MCP_PACKAGE_README_GZIP_BASE64).buffer]).stream().pipeThrough(new DecompressionStream('gzip'))).text();

/** Generated golden-path prose used when no project documentation corpus resolves. */
// deno-fmt-ignore
export const MCP_EMBEDDED_DOCS = [\n${
      embedded.documents.map((document) => `  ${JSON.stringify(document)},`).join('\n\n')
    }\n] as const;

/** Release identity, cardinality, size, and integrity of the generated fallback prose. */
export const MCP_EMBEDDED_DOCS_PROVENANCE: import('./infrastructure/release-embedded-docs-corpus.ts').ReleaseEmbeddedDocsProvenance = { schemaVersion: 1, frameworkVersion: MCP_PACKAGE_VERSION, sourceCommit: 'content-addressed',
  paths: MCP_EMBEDDED_DOCS.map((doc) => doc.path), sourceBytes: MCP_EMBEDDED_DOCS.reduce((sum, doc) => sum + new TextEncoder().encode(doc.source).byteLength, 0),
  documentCount: MCP_EMBEDDED_DOCS.length,
  sha256: new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(MCP_EMBEDDED_DOCS.map(({ path, source }) => \`\${path}\0\${source}\`).join('\0')))).toHex(),
} as const;
`,
    root,
    check,
    foundStalePaths,
  );
}

function hex(buffer: ArrayBuffer): string {
  return [...new Uint8Array(buffer)].map((byte) => byte.toString(16).padStart(2, '0')).join('');
}

function copiedBuffer(bytes: Uint8Array): ArrayBuffer {
  const copy = new Uint8Array(bytes.byteLength);
  copy.set(bytes);
  return copy.buffer;
}

async function generateCliAssets(): Promise<void> {
  const version = await readVersion('packages/cli/deno.json');
  const schema = await Deno.readTextFile(
    new URL('packages/cli/assets/schema/config-file.v1.json', ROOT),
  );
  await write(
    'packages/cli/src/kernel/assets/publish-assets.generated.ts',
    `/** Version of the published CLI package. */
export const CLI_PACKAGE_VERSION: string = ${JSON.stringify(version)};

/** Serialized Deno configuration schema copied into generated workspaces. */
export const DENO_CONFIG_SCHEMA_JSON: string = ${JSON.stringify(schema)};
`,
  );
}

async function generatePluginMetadata(): Promise<void> {
  for (const plugin of ['ai', 'auth', 'sagas', 'streams', 'triggers', 'workers']) {
    const version = await readVersion(`plugins/${plugin}/deno.json`);
    await write(
      `plugins/${plugin}/src/package-metadata.generated.ts`,
      `/** Version of the published plugin package. */
export const PLUGIN_PACKAGE_VERSION: string = ${JSON.stringify(version)};
`,
    );
  }
}

async function generateFreshUiMetadata(): Promise<void> {
  const version = await readVersion('packages/fresh-ui/deno.json');
  await write(
    'packages/fresh-ui/src/package-metadata.generated.ts',
    `/** Version of the published Fresh UI package. */
export const FRESH_UI_PACKAGE_VERSION: string = ${JSON.stringify(version)};
`,
  );
}

async function generateCorePackageMetadata(): Promise<void> {
  for (const packageName of ['plugin-sagas-core', 'plugin-streams-core']) {
    const version = await readVersion(`packages/${packageName}/deno.json`);
    await write(
      `packages/${packageName}/src/package-metadata.generated.ts`,
      `/** Version of the published core package. */
export const CORE_PACKAGE_VERSION: string = ${JSON.stringify(version)};
`,
    );
  }
}

/** Generation steps composed by the top-level publish-asset entrypoint. */
export interface PublishAssetGenerationSteps {
  readonly refreshProvenance: () => Promise<string | void>;
  readonly generateMcp: () => Promise<void>;
  readonly generateCli: () => Promise<void>;
  readonly generateFreshUi: () => Promise<void>;
  readonly generateCorePackages: () => Promise<void>;
  readonly generatePlugins: () => Promise<void>;
}

/** Generate every publish asset through the same orchestration used by the command entrypoint. */
export async function generatePublishAssets(
  steps: PublishAssetGenerationSteps = {
    refreshProvenance: () => refreshAgentDocsProvenance(),
    generateMcp: () => generateMcpAssets(),
    generateCli: () => generateCliAssets(),
    generateFreshUi: () => generateFreshUiMetadata(),
    generateCorePackages: () => generateCorePackageMetadata(),
    generatePlugins: () => generatePluginMetadata(),
  },
): Promise<void> {
  await steps.refreshProvenance();
  await Promise.all([
    steps.generateMcp(),
    steps.generateCli(),
    steps.generateFreshUi(),
    steps.generateCorePackages(),
    steps.generatePlugins(),
  ]);
}

if (import.meta.main) {
  const unknownArgs = Deno.args.filter((arg) => arg !== '--check');
  if (unknownArgs.length > 0) throw new Error(`Unknown argument: ${unknownArgs[0]}`);
  await generatePublishAssets();
  if (stalePaths.length > 0) {
    throw new Error(
      `publish assets are stale: ${
        stalePaths.sort().join(', ')
      }. Run deno task gen:publish-assets.`,
    );
  }
}
