/** Input for authoritative installed-plugin registry generation. */
export interface GenerateInstalledPluginRegistriesInput {
  readonly dryRun: boolean;
  readonly projectRoot: string;
}

/** One runtime registry declared and generated by an installed plugin. */
export interface GeneratedPluginRegistry {
  readonly path: string;
  readonly plugin: string;
  readonly registrableItems: number;
  /** Manifest-discovered project source files, present for read-only inspection. */
  readonly sourceFiles?: readonly string[];
}

/** Authoritative installed-plugin registry generation use case. */
export type GenerateInstalledPluginRegistries = (
  input: GenerateInstalledPluginRegistriesInput,
) => Promise<readonly GeneratedPluginRegistry[]>;

/** Failure raised when an installed runtime declares no registrable project items. */
export class EmptyPluginRegistryError extends Error {
  constructor(readonly plugin: string) {
    super(`Installed plugin "${plugin}" produced no registrable runtime items.`);
    this.name = 'EmptyPluginRegistryError';
  }
}
