import type { PluginSurfaceReport } from '../../../../kernel/domain/plugin-generated-surface.ts';
import { IoError, UsageError } from '../../../../kernel/domain/errors/cli-exit-error.ts';
import type { CliffyCommand } from '../../../../kernel/presentation/command-types.ts';
import { Command } from '@cliffy/command';
import type { EmitterPort, ExtractorPort, WalkerPort } from '@netscript/plugin/sdk';

import { CliCommand } from '../../../../kernel/application/abstracts/cli-command.ts';
import type { FileSystemPort } from '../../../../kernel/ports/file-system-port.ts';
import { outputText } from '../../../../kernel/presentation/output/default-output.ts';
import { type ProjectRootResolver, requireProjectRoot } from '../../../presentation/support.ts';
import type {
  GeneratedPluginRegistry,
  GenerateInstalledPluginRegistries,
} from './generate-installed-plugin-registries.ts';

interface GeneratePluginRegistriesCommandInput {
  readonly check?: boolean;
  readonly format?: string;
  readonly dryRun?: boolean;
  readonly projectRoot?: string;
  readonly verbose?: boolean;
}

/** Dependencies for the public plugin registry generation command. */
export interface GeneratePluginRegistriesCommandDependencies {
  /** Resolve the project root from flags or environment. */
  readonly resolveProjectRoot: ProjectRootResolver;
  /** Generate every registry declared by installed plugin runtime manifests. */
  readonly generate: GenerateInstalledPluginRegistries;
  /** Inspect generated bytes through a read-only rendering boundary. */
  readonly check?: (projectRoot: string) => Promise<PluginSurfaceReport>;
  /** Generic SDK walker retained for plugin item add/update commands. */
  readonly walker: WalkerPort;
  /** Generic SDK extractor retained for plugin item add/update commands. */
  readonly extractor: ExtractorPort;
  /** Generic SDK emitter retained for plugin item add/update commands. */
  readonly emitter: EmitterPort;
  /** Filesystem retained for plugin item add/update command emissions. */
  readonly fs: FileSystemPort;
  /** Print completion lines. */
  readonly print?: (message: string) => void;
}

/** Public `generate plugins` command definition owner. */
export class GeneratePluginRegistriesCommand extends CliCommand<CliffyCommand> {
  readonly id = 'public.generate.plugins';

  constructor(private readonly dependencies: GeneratePluginRegistriesCommandDependencies) {
    super();
  }

  define(): CliffyCommand {
    const print = this.dependencies.print ?? outputText;
    return new Command()
      .name('plugins')
      .description('Generate installed plugin runtime registries (authoritative)')
      .option('--check', 'Inspect generated ownership and bytes without project writes', {
        conflicts: ['dry-run'],
      })
      .option('--format <format:string>', 'Check report format: text or json', {
        depends: ['check'],
      })
      .option('--dry-run', 'Show what would be written without making changes', { default: false })
      .option('--project-root <path:string>', 'Project root directory')
      .option('--verbose', 'Show generated registry paths', { default: false })
      .action(async (options: GeneratePluginRegistriesCommandInput): Promise<void> => {
        if (options.format && !['text', 'json'].includes(options.format)) {
          throw new UsageError(2, 'Check format must be text or json.');
        }
        const projectRoot = await requireProjectRoot(
          this.dependencies.resolveProjectRoot,
          options.projectRoot,
        );
        if (options.check) {
          if (!this.dependencies.check) {
            throw new IoError(1, 'Plugin byte inspection is unavailable.');
          }
          const report = await this.dependencies.check(projectRoot);
          if (options.format === 'json') print(JSON.stringify(report, null, 2));
          else {
            for (const finding of report.drift) {
              print(
                `${finding.kind}: ${finding.path}${finding.message ? `: ${finding.message}` : ''}`,
              );
            }
            print(`Plugin surface ${report.status}: ${report.outputs.length} selected outputs.`);
          }
          if (report.exitCode !== 0) throw new IoError(1, `Plugin surface ${report.status}.`);
          return;
        }
        const generated = await this.dependencies.generate({
          dryRun: options.dryRun ?? false,
          projectRoot,
        });

        const verb = options.dryRun ? 'would write' : 'written';
        print(`Plugin registry generation complete: ${generated.length} ${verb}.`);
        if (options.verbose) {
          for (const registry of generated) print(registry.path);
        }
      });
  }
}

/** Create the public `generate plugins` command. */
export function createGeneratePluginRegistriesCommand(
  dependencies: GeneratePluginRegistriesCommandDependencies,
): CliffyCommand {
  return new GeneratePluginRegistriesCommand(dependencies).define();
}

export type { GeneratedPluginRegistry };
