/**
 * @module maintainer/adapters/packages-copier
 *
 * Copies `@netscript/*` monorepo packages into a scaffolded project when the
 * user initializes with `--import-mode=local`. Each package becomes a
 * workspace member at `packages/<name>/` and self-declares its own
 * dependencies via its own `deno.json` imports map.
 *
 * ## Why copy rather than relative-link?
 *
 * Deno 2.x workspace resolution requires every workspace member to live at or
 * below the workspace root. Referencing packages via relative paths that
 * escape the workspace (e.g. `../../packages/fresh/mod.ts`) works for direct
 * imports but breaks for transitive ones: Deno resolves those against the
 * workspace root's import map, not the imported package's own `deno.json`.
 *
 * Copying packages *into* the scaffold makes them first-class workspace
 * members whose own `deno.json` imports maps participate in resolution.
 * The generated root `deno.json` remains a workspace manifest, but it also
 * mirrors the producer catalog so copied package-level `catalog:` imports
 * resolve inside the consumer workspace.
 *
 * ## Filters
 *
 * Every file in the source package directory is copied except:
 * - `node_modules/` — regenerated by consumers
 * - `.deno/` — local Deno cache
 * - `__snapshots__/` — test snapshots
 * - `_fresh/` — Fresh build output
 * - files ending in `_test.ts` / `_test.tsx` / `.test.ts` / `.test.tsx`
 *
 * ## Failure modes
 *
 * Throws if the monorepo root is missing any required package directory —
 * this indicates the CLI is being run from a broken checkout and callers
 * should surface a clear error rather than continue with a half-copied
 * scaffold.
 */

import { ensureDir } from "@std/fs";
import { join, relative } from "@std/path";
import { SCAFFOLD_DIRS } from "../../kernel/constants/scaffold/scaffold-dirs.ts";
import {
  SCAFFOLD_ENGINE_WORKSPACE_PACKAGES,
  SCAFFOLD_WORKSPACE_PACKAGES,
} from "../../kernel/constants/scaffold/scaffold-workspace-packages.ts";
import { copyDirectoryFiltered } from "../../kernel/adapters/scaffold/directory-copier.ts";
import {
  readRootCatalog,
  rewriteCopiedDenoJsons,
} from "./plugin-import-rewriter.ts";
import type {
  CopyLocalPackagesOptions,
  CopyLocalPackagesResult,
  PackageCopierPort,
} from "../ports/package-copier-port.ts";

/** Directory names that must never be copied into a scaffold. */
const SKIP_DIRS: readonly string[] = [
  "node_modules",
  ".deno",
  "__snapshots__",
  "_fresh",
];

/** Test-file suffixes that are stripped from the copied package. */
const TEST_FILE_SUFFIXES: readonly string[] = [
  "_test.ts",
  "_test.tsx",
  ".test.ts",
  ".test.tsx",
];

const MYSQL_ADAPTER_PACKAGE = "prisma-adapter-mysql";
const SOURCE_ROOT_MARKER = ".netscript-source-root";

interface RootDenoJson {
  workspace?: unknown;
  catalog?: unknown;
}

interface PackageDenoJson {
  exports?: Record<string, string>;
}

/**
 * Copy every package listed in `SCAFFOLD_WORKSPACE_PACKAGES` from the monorepo
 * into `<targetPath>/packages/<name>/`.
 *
 * @throws If any source package directory is missing.
 */
export async function copyLocalPackages(
  options: CopyLocalPackagesOptions,
): Promise<CopyLocalPackagesResult> {
  const directoriesCreated: string[] = [];
  const filesCreated: string[] = [];

  const destPackagesRoot = join(options.targetPath, SCAFFOLD_DIRS.PACKAGES);
  await ensureDir(destPackagesRoot);
  directoriesCreated.push(destPackagesRoot);

  const enginePackages = (options.dbEngines ?? []).flatMap(
    (engine) => SCAFFOLD_ENGINE_WORKSPACE_PACKAGES[engine] ?? [],
  );
  const selectedPackages = options.packageNames ?? SCAFFOLD_WORKSPACE_PACKAGES;
  const allPackages = [...new Set([...selectedPackages, ...enginePackages])];
  const sourceCatalog = await readRootCatalog(options.sourceRoot);

  for (const pkg of allPackages) {
    const sourcePkgDir = join(options.sourceRoot, SCAFFOLD_DIRS.PACKAGES, pkg);
    const destPkgDir = join(destPackagesRoot, pkg);

    try {
      const stat = await Deno.stat(sourcePkgDir);
      if (!stat.isDirectory) {
        throw new Error(
          `Source path ${sourcePkgDir} is not a directory`,
        );
      }
    } catch (cause) {
      throw new Error(
        `Cannot copy @netscript/${pkg}: source ${sourcePkgDir} is missing. ` +
          `Are you running netscript init from inside a valid monorepo checkout?`,
        { cause },
      );
    }

    const copyResult = await copyDirectoryFiltered({
      source: sourcePkgDir,
      dest: destPkgDir,
      skipDirs: SKIP_DIRS,
      skipFileSuffixes: options.includeTests ? [] : TEST_FILE_SUFFIXES,
    });
    directoriesCreated.push(...copyResult.directoriesCreated);
    filesCreated.push(...copyResult.filesCreated);

    await rewriteCopiedDenoJsons({
      root: destPkgDir,
      projectName: "",
      importMode: "local",
      workspacePackageName: null,
      catalog: sourceCatalog,
    });
  }

  await updateRootWorkspaceConfig(
    options.targetPath,
    allPackages,
    sourceCatalog,
  );
  await Deno.writeTextFile(
    join(options.targetPath, SOURCE_ROOT_MARKER),
    options.sourceRoot + "\n",
  );

  if (!allPackages.includes(MYSQL_ADAPTER_PACKAGE)) {
    await pruneMysqlAdapterFromDatabasePackage(destPackagesRoot, filesCreated);
  }

  return {
    directoriesCreated,
    filesCreated,
    packagesCopied: allPackages.length,
  };
}

/** Create the maintainer package copier adapter. */
export function createPackageCopier(): PackageCopierPort {
  return { copyLocalPackages };
}

/** Unused; retained to expose {@link relative} for tests in future slices. */
export const _internal: Record<string, unknown> = { relative };

async function updateRootWorkspaceConfig(
  targetPath: string,
  packageNames: readonly string[],
  sourceCatalog?: Readonly<Record<string, string>>,
): Promise<void> {
  const denoJsonPath = join(targetPath, "deno.json");
  let root: RootDenoJson;
  try {
    root = JSON.parse(await Deno.readTextFile(denoJsonPath)) as RootDenoJson;
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      return;
    }
    throw error;
  }

  if (sourceCatalog) {
    root.catalog = sourceCatalog;
  }

  const existing = Array.isArray(root.workspace) ? root.workspace : [];
  const workspace = existing.filter((member): member is string =>
    typeof member === "string"
  );
  const next = new Set(workspace);
  for (const packageName of packageNames) {
    next.add(`./${SCAFFOLD_DIRS.PACKAGES}/${packageName}`);
  }

  root.workspace = [...next];
  await Deno.writeTextFile(denoJsonPath, JSON.stringify(root, null, 2) + "\n");
}

async function pruneMysqlAdapterFromDatabasePackage(
  destPackagesRoot: string,
  filesCreated: string[],
): Promise<void> {
  const adapterPath = join(
    destPackagesRoot,
    "database",
    "adapters",
    "mysql.adapter.ts",
  );
  try {
    await Deno.remove(adapterPath);
    removeCreatedFile(filesCreated, adapterPath);
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) {
      throw error;
    }
  }

  const denoJsonPath = join(destPackagesRoot, "database", "deno.json");
  const raw = JSON.parse(
    await Deno.readTextFile(denoJsonPath),
  ) as PackageDenoJson;
  if (raw.exports) {
    delete raw.exports["./adapters/mysql"];
  }
  await Deno.writeTextFile(denoJsonPath, JSON.stringify(raw, null, 2) + "\n");
}

function removeCreatedFile(filesCreated: string[], path: string): void {
  const index = filesCreated.indexOf(path);
  if (index >= 0) {
    filesCreated.splice(index, 1);
  }
}
