// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run `deno task gen:assets-barrel`.

import template_000 from './registry/components/ui/alert-styles.css' with { type: 'text' };
import template_001 from './registry/components/ui/alert.css' with { type: 'text' };
import template_002 from './registry/components/ui/alert.tsx' with { type: 'text' };
import template_003 from './registry/components/ui/badge.css' with { type: 'text' };
import template_004 from './registry/components/ui/badge.tsx' with { type: 'text' };
import template_005 from './registry/components/ui/breadcrumb.tsx' with { type: 'text' };
import template_006 from './registry/components/ui/button.css' with { type: 'text' };
import template_007 from './registry/components/ui/button.tsx' with { type: 'text' };
import template_008 from './registry/components/ui/card.css' with { type: 'text' };
import template_009 from './registry/components/ui/card.tsx' with { type: 'text' };
import template_010 from './registry/components/ui/checkbox.css' with { type: 'text' };
import template_011 from './registry/components/ui/checkbox.tsx' with { type: 'text' };
import template_012 from './registry/components/ui/choice-styles.css' with { type: 'text' };
import template_013 from './registry/components/ui/control-props.ts' with { type: 'text' };
import template_014 from './registry/components/ui/data-table.tsx' with { type: 'text' };
import template_015 from './registry/components/ui/detail-layout.tsx' with { type: 'text' };
import template_016 from './registry/components/ui/empty-state.tsx' with { type: 'text' };
import template_017 from './registry/components/ui/filter-form.tsx' with { type: 'text' };
import template_018 from './registry/components/ui/floating.css' with { type: 'text' };
import template_019 from './registry/components/ui/form-control-styles.css' with { type: 'text' };
import template_020 from './registry/components/ui/form-field.css' with { type: 'text' };
import template_021 from './registry/components/ui/form-field.tsx' with { type: 'text' };
import template_022 from './registry/components/ui/icon-button.tsx' with { type: 'text' };
import template_023 from './registry/components/ui/inline-notice.css' with { type: 'text' };
import template_024 from './registry/components/ui/inline-notice.tsx' with { type: 'text' };
import template_025 from './registry/components/ui/input.tsx' with { type: 'text' };
import template_026 from './registry/components/ui/label.css' with { type: 'text' };
import template_027 from './registry/components/ui/label.tsx' with { type: 'text' };
import template_028 from './registry/components/ui/page-header.tsx' with { type: 'text' };
import template_029 from './registry/components/ui/pagination.tsx' with { type: 'text' };
import template_030 from './registry/components/ui/panel.css' with { type: 'text' };
import template_031 from './registry/components/ui/panel.tsx' with { type: 'text' };
import template_032 from './registry/components/ui/progress.css' with { type: 'text' };
import template_033 from './registry/components/ui/progress.tsx' with { type: 'text' };
import template_034 from './registry/components/ui/responsive-table.css' with { type: 'text' };
import template_035 from './registry/components/ui/responsive-table.tsx' with { type: 'text' };
import template_036 from './registry/components/ui/section-divider.tsx' with { type: 'text' };
import template_037 from './registry/components/ui/select.tsx' with { type: 'text' };
import template_038 from './registry/components/ui/separator.css' with { type: 'text' };
import template_039 from './registry/components/ui/separator.tsx' with { type: 'text' };
import template_040 from './registry/components/ui/sheet.css' with { type: 'text' };
import template_041 from './registry/components/ui/sidebar-shell.tsx' with { type: 'text' };
import template_042 from './registry/components/ui/skeleton.css' with { type: 'text' };
import template_043 from './registry/components/ui/skeleton.tsx' with { type: 'text' };
import template_044 from './registry/components/ui/spinner.css' with { type: 'text' };
import template_045 from './registry/components/ui/spinner.tsx' with { type: 'text' };
import template_046 from './registry/components/ui/stats-grid.tsx' with { type: 'text' };
import template_047 from './registry/components/ui/surface-styles.css' with { type: 'text' };
import template_048 from './registry/components/ui/switch.css' with { type: 'text' };
import template_049 from './registry/components/ui/switch.tsx' with { type: 'text' };
import template_050 from './registry/components/ui/textarea.css' with { type: 'text' };
import template_051 from './registry/components/ui/textarea.tsx' with { type: 'text' };
import template_052 from './registry/components/ui/toast.css' with { type: 'text' };
import template_053 from './registry/islands/SidebarToggle.tsx' with { type: 'text' };
import template_054 from './registry/islands/ThemeToggle.tsx' with { type: 'text' };
import template_055 from './registry/islands/Toast.tsx' with { type: 'text' };
import template_056 from './registry/lib/cn.ts' with { type: 'text' };
import template_057 from './registry/lib/public-types.ts' with { type: 'text' };
import template_058 from './registry/lib/toast.ts' with { type: 'text' };
import template_059 from './registry/styles/layouts.css' with { type: 'text' };
import template_060 from './registry/theme/styles.css' with { type: 'text' };
import template_061 from './registry/theme/theme-bridge.css' with { type: 'text' };
import template_062 from './registry/theme/tokens.css' with { type: 'text' };
import template_063 from './registry/theme/tokens.json' with { type: 'text' };

/** Embedded text content for every file referenced by the Fresh UI registry manifest. */
export const FRESH_UI_REGISTRY_CONTENT: Record<string, string> = {
  'registry/components/ui/alert-styles.css': template_000,
  'registry/components/ui/alert.css': template_001,
  'registry/components/ui/alert.tsx': template_002,
  'registry/components/ui/badge.css': template_003,
  'registry/components/ui/badge.tsx': template_004,
  'registry/components/ui/breadcrumb.tsx': template_005,
  'registry/components/ui/button.css': template_006,
  'registry/components/ui/button.tsx': template_007,
  'registry/components/ui/card.css': template_008,
  'registry/components/ui/card.tsx': template_009,
  'registry/components/ui/checkbox.css': template_010,
  'registry/components/ui/checkbox.tsx': template_011,
  'registry/components/ui/choice-styles.css': template_012,
  'registry/components/ui/control-props.ts': template_013,
  'registry/components/ui/data-table.tsx': template_014,
  'registry/components/ui/detail-layout.tsx': template_015,
  'registry/components/ui/empty-state.tsx': template_016,
  'registry/components/ui/filter-form.tsx': template_017,
  'registry/components/ui/floating.css': template_018,
  'registry/components/ui/form-control-styles.css': template_019,
  'registry/components/ui/form-field.css': template_020,
  'registry/components/ui/form-field.tsx': template_021,
  'registry/components/ui/icon-button.tsx': template_022,
  'registry/components/ui/inline-notice.css': template_023,
  'registry/components/ui/inline-notice.tsx': template_024,
  'registry/components/ui/input.tsx': template_025,
  'registry/components/ui/label.css': template_026,
  'registry/components/ui/label.tsx': template_027,
  'registry/components/ui/page-header.tsx': template_028,
  'registry/components/ui/pagination.tsx': template_029,
  'registry/components/ui/panel.css': template_030,
  'registry/components/ui/panel.tsx': template_031,
  'registry/components/ui/progress.css': template_032,
  'registry/components/ui/progress.tsx': template_033,
  'registry/components/ui/responsive-table.css': template_034,
  'registry/components/ui/responsive-table.tsx': template_035,
  'registry/components/ui/section-divider.tsx': template_036,
  'registry/components/ui/select.tsx': template_037,
  'registry/components/ui/separator.css': template_038,
  'registry/components/ui/separator.tsx': template_039,
  'registry/components/ui/sheet.css': template_040,
  'registry/components/ui/sidebar-shell.tsx': template_041,
  'registry/components/ui/skeleton.css': template_042,
  'registry/components/ui/skeleton.tsx': template_043,
  'registry/components/ui/spinner.css': template_044,
  'registry/components/ui/spinner.tsx': template_045,
  'registry/components/ui/stats-grid.tsx': template_046,
  'registry/components/ui/surface-styles.css': template_047,
  'registry/components/ui/switch.css': template_048,
  'registry/components/ui/switch.tsx': template_049,
  'registry/components/ui/textarea.css': template_050,
  'registry/components/ui/textarea.tsx': template_051,
  'registry/components/ui/toast.css': template_052,
  'registry/islands/SidebarToggle.tsx': template_053,
  'registry/islands/ThemeToggle.tsx': template_054,
  'registry/islands/Toast.tsx': template_055,
  'registry/lib/cn.ts': template_056,
  'registry/lib/public-types.ts': template_057,
  'registry/lib/toast.ts': template_058,
  'registry/styles/layouts.css': template_059,
  'registry/theme/styles.css': template_060,
  'registry/theme/theme-bridge.css': template_061,
  'registry/theme/tokens.css': template_062,
  'registry/theme/tokens.json': template_063,
};
