import {
  type ProjectFileEntry,
  type ProjectFiles,
  renderRegistryModule,
} from '@netscript/plugin/cli';
import { inspectSagasProject } from './saga-inspector.ts';

/** Options for generating the static saga registry. */
export interface GenerateSagaRegistryOptions {
  /** Project-relative source roots to scan for saga definitions. */
  readonly roots?: readonly string[];
  /** Project-relative output file. */
  readonly registryPath?: string;
  /** Source file suffixes eligible for registry generation. */
  readonly fileSuffixes?: readonly string[];
  /** File names excluded from registry generation. */
  readonly exclude?: readonly string[];
}

/** Result returned after generating a static saga registry. */
export interface GenerateSagaRegistryResult {
  /** Generated registry path relative to the project root. */
  readonly registryPath: string;
  /** Saga source files included in the registry. */
  readonly sagas: readonly string[];
}

const DEFAULT_REGISTRY_PATH = '.netscript/generated/plugin-sagas/sagas.registry.ts';

/** Generate a static registry from fluent saga definition modules. */
export async function generateSagaRegistry(
  files: ProjectFiles,
  options: GenerateSagaRegistryOptions = {},
): Promise<GenerateSagaRegistryResult> {
  const registryPath = options.registryPath ?? DEFAULT_REGISTRY_PATH;
  const inspected = await inspectSagasProject(files, { roots: options.roots });
  const sourcePaths = inspected.entries.map((entry) => entry.sourcePath).filter((path) =>
    isIncludedSourcePath(path, options)
  );
  const sagaFiles = await toEntries(files, sourcePaths);
  const source = renderSagaRegistrySource(registryPath, sagaFiles);
  await files.writeTextFile(registryPath, source);
  return Object.freeze({
    registryPath,
    sagas: Object.freeze(sagaFiles.map((entry) => entry.relativePath)),
  });
}

function renderSagaRegistrySource(
  registryPath: string,
  sagas: readonly ProjectFileEntry[],
): string {
  return renderRegistryModule({
    registryPath,
    items: sagas,
    alias: (index) => `saga${index}`,
    renderImport: (alias, specifier) => `import * as ${alias} from ${quoteString(specifier)};`,
    renderEntry: (alias, saga) => {
      const path = quoteString(saga.relativePath);
      return [
        '  [',
        `    resolveSagaDefinition(${alias}, ${path}).id,`,
        `    resolveSagaDefinition(${alias}, ${path}),`,
        '  ],',
      ];
    },
    header: [
      '/**',
      ' * Saga Registry - AUTO-GENERATED',
      ' *',
      ' * DO NOT EDIT - regenerated by the sagas plugin CLI.',
      ' *',
      ' * @module',
      ' */',
      '',
      "import type { SagaDefinition } from '@netscript/plugin-sagas-core/domain';",
    ],
    body: (entries) => [
      'const entries: readonly [string, SagaDefinition][] = [',
      ...entries,
      '];',
      '',
      'export const sagaRegistry: ReadonlyMap<string, SagaDefinition> = new Map(entries);',
      'export const registry: ReadonlyMap<string, SagaDefinition> = sagaRegistry;',
      '',
      'function resolveSagaDefinition(module: Record<string, unknown>, path: string): SagaDefinition {',
      '  const candidate = module.default ?? module.saga ?? module.definition;',
      '  if (!isSagaDefinition(candidate)) {',
      '    throw new Error(`Saga module ${path} does not export a SagaDefinition.`);',
      '  }',
      '  return candidate;',
      '}',
      '',
      'function isSagaDefinition(candidate: unknown): candidate is SagaDefinition {',
      "  if (typeof candidate !== 'object' || candidate === null) {",
      '    return false;',
      '  }',
      '  const value = candidate as Record<string, unknown>;',
      "  return typeof value.id === 'string' &&",
      "    typeof value.durability === 'string' &&",
      "    typeof value.initialState === 'object' &&",
      '    value.initialState !== null &&',
      '    Array.isArray(value.handledMessageTypes) &&',
      '    value.handlers instanceof Map;',
      '}',
      '',
    ],
  });
}

async function toEntries(
  files: ProjectFiles,
  paths: readonly string[],
): Promise<readonly ProjectFileEntry[]> {
  const uniquePaths = Object.freeze([...new Set(paths)]);
  const entries = await Promise.all(uniquePaths.map(async (path) => {
    const content = await files.readTextFile(path);
    return content === undefined
      ? undefined
      : Object.freeze({ path: files.resolve(path), relativePath: path, size: content.length });
  }));
  return Object.freeze(entries.filter(isProjectFileEntry));
}

function isProjectFileEntry(entry: ProjectFileEntry | undefined): entry is ProjectFileEntry {
  return entry !== undefined;
}

function isIncludedSourcePath(path: string, options: GenerateSagaRegistryOptions): boolean {
  const fileName = basename(path);
  const suffixes = options.fileSuffixes;
  if (suffixes && !suffixes.some((suffix) => fileName.endsWith(suffix))) {
    return false;
  }
  return !(options.exclude ?? []).includes(fileName);
}

function basename(path: string): string {
  const normalized = path.replaceAll('\\', '/').replace(/\/+/g, '/');
  const index = normalized.lastIndexOf('/');
  return index < 0 ? normalized : normalized.slice(index + 1);
}

function quoteString(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}
