import type { RegistryManifest } from './schema.ts';

/**
 * Copy-based registry manifest for the published `@netscript/fresh-ui` foundation package.
 */
export const freshUiRegistryManifest = {
  name: 'fresh-ui-foundation',
  version: '0.1.0',
  packageName: '@netscript/fresh-ui',
  model: 'copy-based-registry',
  schemaVersion: 2,
  tokenSourceStrategy: 'style-dictionary-dtcg-source',
  items: [
    {
      name: 'cn',
      kind: 'lib',
      description: 'Shared class-name merge helper for copied registry components.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['lib', 'class-names', 'support'],
      files: [{ source: 'registry/lib/cn.ts', target: '@lib/cn.ts' }],
      dependencies: ['npm:clsx@^2.1.1', 'npm:tailwind-merge@^3.5.0'],
    },
    {
      name: 'public-types',
      kind: 'lib',
      description: 'Shared renderable and component result types for copied registry components.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['lib', 'types', 'support'],
      files: [{
        source: 'registry/lib/public-types.ts',
        target: '@lib/public-types.ts',
      }],
    },
    {
      name: 'control-props',
      kind: 'support',
      layer: 2,
      description: 'Control-prop narrowing helpers used by registry verification and form seams.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['forms', 'descriptors', 'support'],
      files: [{
        source: 'registry/components/ui/control-props.ts',
        target: '@ui/control-props.ts',
      }],
    },
    {
      name: 'form-control-styles',
      kind: 'style',
      layer: 2,
      description: 'Shared input, select, and textarea control CSS blocks.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['forms', 'styles', 'support'],
      files: [{
        source: 'registry/components/ui/form-control-styles.css',
        target: '@assets/ui/form-control-styles.css',
      }],
      registryDependencies: ['theme-seed'],
      css: [{ layer: 'components', content: "@import './ui/form-control-styles.css';" }],
    },
    {
      name: 'choice-styles',
      kind: 'style',
      layer: 2,
      description: 'Shared choice-control CSS blocks for checkbox and switch seams.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['forms', 'selection', 'styles', 'support'],
      files: [{
        source: 'registry/components/ui/choice-styles.css',
        target: '@assets/ui/choice-styles.css',
      }],
      registryDependencies: ['theme-seed'],
      css: [{ layer: 'components', content: "@import './ui/choice-styles.css';" }],
    },
    {
      name: 'surface-styles',
      kind: 'style',
      layer: 2,
      description: 'Shared card and panel surface CSS blocks.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['surface', 'styles', 'support'],
      files: [{
        source: 'registry/components/ui/surface-styles.css',
        target: '@assets/ui/surface-styles.css',
      }],
      registryDependencies: ['theme-seed'],
      css: [{ layer: 'components', content: "@import './ui/surface-styles.css';" }],
    },
    {
      name: 'sheet-styles',
      kind: 'style',
      layer: 2,
      description: 'Platform dialog sheet CSS blocks for package-owned sheet runtime.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['surface', 'sheet', 'styles', 'support'],
      files: [{
        source: 'registry/components/ui/sheet.css',
        target: '@assets/ui/sheet.css',
      }],
      registryDependencies: ['theme-seed'],
      css: [{ layer: 'components', content: "@import './ui/sheet.css';" }],
    },
    {
      name: 'alert-styles',
      kind: 'style',
      layer: 2,
      description: 'Shared alert and inline-notice feedback CSS blocks.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['feedback', 'styles', 'support'],
      files: [{
        source: 'registry/components/ui/alert-styles.css',
        target: '@assets/ui/alert-styles.css',
      }],
      registryDependencies: ['theme-seed'],
      css: [{ layer: 'components', content: "@import './ui/alert-styles.css';" }],
    },
    {
      name: 'theme-seed',
      kind: 'theme',
      description:
        'Initial token, component-class, and CSS-first layout-object seed sourced from the playground.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: [
        'theme',
        'tailwind-v4',
        'tokens',
        'style-dictionary-ready',
        'layout-objects',
        'dashboard-foundation',
      ],
      files: [
        { source: 'registry/theme/styles.css', target: '@assets/styles.css' },
        { source: 'registry/theme/tokens.css', target: '@assets/tokens.css' },
        {
          source: 'registry/theme/theme-bridge.css',
          target: '@assets/theme-bridge.css',
        },
        { source: 'registry/theme/tokens.json', target: '@assets/tokens.json' },
        { source: 'registry/theme/layouts.css', target: '@assets/layouts.css' },
      ],
      registryDependencies: ['cn', 'public-types'],
      cssVars: {
        theme: {
          '--ns-bg': 'var(--ns-gray-12)',
          '--ns-fg': 'var(--ns-gray-1)',
          '--ns-primary': 'var(--ns-copper-6)',
          '--ns-ring': 'var(--ns-copper-6)',
        },
        light: {
          '--ns-bg': 'var(--ns-gray-1)',
          '--ns-fg': 'var(--ns-gray-12)',
        },
      },
    },
    {
      name: 'button',
      kind: 'component',
      layer: 2,
      description: 'Generic action primitive using semantic theme classes.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['forms', 'actions', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/button.tsx',
          target: '@ui/button.tsx',
        },
        {
          source: 'registry/components/ui/button.css',
          target: '@assets/ui/button.css',
        },
      ],
      registryDependencies: ['theme-seed', 'spinner'],
      css: [{ layer: 'components', content: "@import './ui/button.css';" }],
    },
    {
      name: 'icon-button',
      kind: 'component',
      layer: 2,
      description: 'Accessible icon-only action button built on the shared Button seam.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['actions', 'primitive', 'icon'],
      files: [{
        source: 'registry/components/ui/icon-button.tsx',
        target: '@ui/icon-button.tsx',
      }],
      registryDependencies: ['theme-seed', 'button'],
    },
    {
      name: 'input',
      kind: 'component',
      layer: 2,
      description: 'Generic text input with token-driven error styling.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['forms', 'primitive'],
      files: [{
        source: 'registry/components/ui/input.tsx',
        target: '@ui/input.tsx',
      }],
      registryDependencies: ['theme-seed', 'form-control-styles'],
    },
    {
      name: 'textarea',
      kind: 'component',
      layer: 2,
      description: 'Generic multi-line text input with the shared field styling contract.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['forms', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/textarea.tsx',
          target: '@ui/textarea.tsx',
        },
        {
          source: 'registry/components/ui/textarea.css',
          target: '@assets/ui/textarea.css',
        },
      ],
      registryDependencies: ['theme-seed', 'form-control-styles'],
      css: [{ layer: 'components', content: "@import './ui/textarea.css';" }],
    },
    {
      name: 'checkbox',
      kind: 'component',
      layer: 2,
      description: 'CSS-first native checkbox seam with inline label and helper copy.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['forms', 'selection', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/checkbox.tsx',
          target: '@ui/checkbox.tsx',
        },
        {
          source: 'registry/components/ui/checkbox.css',
          target: '@assets/ui/checkbox.css',
        },
      ],
      registryDependencies: ['theme-seed', 'choice-styles'],
      css: [{ layer: 'components', content: "@import './ui/checkbox.css';" }],
    },
    {
      name: 'switch',
      kind: 'component',
      layer: 2,
      description: 'CSS-first native switch seam for binary dashboard settings.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['forms', 'selection', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/switch.tsx',
          target: '@ui/switch.tsx',
        },
        {
          source: 'registry/components/ui/switch.css',
          target: '@assets/ui/switch.css',
        },
      ],
      registryDependencies: ['theme-seed', 'choice-styles'],
      css: [{ layer: 'components', content: "@import './ui/switch.css';" }],
    },
    {
      name: 'label',
      kind: 'component',
      layer: 2,
      description: 'Accessible field label with required-state support.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['forms', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/label.tsx',
          target: '@ui/label.tsx',
        },
        {
          source: 'registry/components/ui/label.css',
          target: '@assets/ui/label.css',
        },
      ],
      registryDependencies: ['theme-seed'],
      css: [{ layer: 'components', content: "@import './ui/label.css';" }],
    },
    {
      name: 'select',
      kind: 'component',
      layer: 2,
      description: 'Native select wrapper with semantic token styling.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['forms', 'primitive'],
      files: [{
        source: 'registry/components/ui/select.tsx',
        target: '@ui/select.tsx',
      }],
      registryDependencies: ['theme-seed', 'form-control-styles'],
    },
    {
      name: 'form-field',
      kind: 'component',
      layer: 2,
      description: 'Composed field wrapper for labels, help text, and errors.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['forms', 'composed'],
      files: [
        {
          source: 'registry/components/ui/form-field.tsx',
          target: '@ui/form-field.tsx',
        },
        {
          source: 'registry/components/ui/form-field.css',
          target: '@assets/ui/form-field.css',
        },
      ],
      registryDependencies: ['theme-seed', 'label'],
      css: [{ layer: 'components', content: "@import './ui/form-field.css';" }],
    },
    {
      name: 'card',
      kind: 'component',
      layer: 2,
      description:
        'Primary content surface with header/body/footer sub-seams for dashboard composition.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['surface', 'container', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/card.tsx',
          target: '@ui/card.tsx',
        },
        {
          source: 'registry/components/ui/card.css',
          target: '@assets/ui/card.css',
        },
      ],
      registryDependencies: ['theme-seed', 'surface-styles'],
      css: [{ layer: 'components', content: "@import './ui/card.css';" }],
    },
    {
      name: 'panel',
      kind: 'component',
      layer: 2,
      description: 'Dense secondary surface for filters, rails, and grouped operational controls.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['surface', 'container', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/panel.tsx',
          target: '@ui/panel.tsx',
        },
        {
          source: 'registry/components/ui/panel.css',
          target: '@assets/ui/panel.css',
        },
      ],
      registryDependencies: ['theme-seed', 'surface-styles'],
      css: [{ layer: 'components', content: "@import './ui/panel.css';" }],
    },
    {
      name: 'badge',
      kind: 'component',
      layer: 2,
      description: 'Compact semantic status seam for tags, counts, and entity state labels.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['status', 'feedback', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/badge.tsx',
          target: '@ui/badge.tsx',
        },
        {
          source: 'registry/components/ui/badge.css',
          target: '@assets/ui/badge.css',
        },
      ],
      registryDependencies: ['theme-seed'],
      css: [{ layer: 'components', content: "@import './ui/badge.css';" }],
    },
    {
      name: 'separator',
      kind: 'component',
      layer: 2,
      description: 'Lightweight divider seam for cards, forms, panels, and toolbars.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['surface', 'layout', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/separator.tsx',
          target: '@ui/separator.tsx',
        },
        {
          source: 'registry/components/ui/separator.css',
          target: '@assets/ui/separator.css',
        },
      ],
      registryDependencies: ['theme-seed'],
      css: [{ layer: 'components', content: "@import './ui/separator.css';" }],
    },
    {
      name: 'alert',
      kind: 'component',
      layer: 2,
      description:
        'Persistent section-level feedback banner for success, warning, info, and error states.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['feedback', 'status', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/alert.tsx',
          target: '@ui/alert.tsx',
        },
        {
          source: 'registry/components/ui/alert.css',
          target: '@assets/ui/alert.css',
        },
      ],
      registryDependencies: ['theme-seed', 'alert-styles'],
      css: [{ layer: 'components', content: "@import './ui/alert.css';" }],
    },
    {
      name: 'inline-notice',
      kind: 'component',
      layer: 2,
      description: 'Compact contextual feedback seam for inline guidance inside forms and panels.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['feedback', 'status', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/inline-notice.tsx',
          target: '@ui/inline-notice.tsx',
        },
        {
          source: 'registry/components/ui/inline-notice.css',
          target: '@assets/ui/inline-notice.css',
        },
      ],
      registryDependencies: ['theme-seed', 'alert-styles'],
      css: [{ layer: 'components', content: "@import './ui/inline-notice.css';" }],
    },
    {
      name: 'spinner',
      kind: 'component',
      layer: 2,
      description: 'Small loading indicator for async actions and deferred regions.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['feedback', 'loading', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/spinner.tsx',
          target: '@ui/spinner.tsx',
        },
        {
          source: 'registry/components/ui/spinner.css',
          target: '@assets/ui/spinner.css',
        },
      ],
      registryDependencies: ['theme-seed'],
      css: [{ layer: 'components', content: "@import './ui/spinner.css';" }],
    },
    {
      name: 'progress',
      kind: 'component',
      layer: 2,
      description:
        'Determinate or indeterminate progress seam for jobs, uploads, and background work.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['feedback', 'loading', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/progress.tsx',
          target: '@ui/progress.tsx',
        },
        {
          source: 'registry/components/ui/progress.css',
          target: '@assets/ui/progress.css',
        },
      ],
      registryDependencies: ['theme-seed'],
      css: [{ layer: 'components', content: "@import './ui/progress.css';" }],
    },
    {
      name: 'skeleton',
      kind: 'component',
      layer: 2,
      description:
        'Generic dashboard loading scaffold for table, stats, detail, and form surfaces.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['feedback', 'loading', 'primitive'],
      files: [
        {
          source: 'registry/components/ui/skeleton.tsx',
          target: '@ui/skeleton.tsx',
        },
        {
          source: 'registry/components/ui/skeleton.css',
          target: '@assets/ui/skeleton.css',
        },
      ],
      registryDependencies: ['theme-seed'],
      css: [{ layer: 'components', content: "@import './ui/skeleton.css';" }],
    },
    {
      name: 'breadcrumb',
      kind: 'block',
      layer: 3,
      description: 'Accessible breadcrumb block for dashboard drill-down navigation.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['navigation', 'dashboard', 'block'],
      files: [{
        source: 'registry/components/ui/breadcrumb.tsx',
        target: '@ui/breadcrumb.tsx',
      }],
      registryDependencies: ['theme-seed'],
    },
    {
      name: 'sidebar-shell',
      kind: 'block',
      layer: 3,
      description:
        'Reusable dashboard sidebar shell that accepts app-owned IA, breadcrumbs, and topbar actions.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['layout', 'dashboard', 'shell', 'block'],
      files: [{
        source: 'registry/components/ui/sidebar-shell.tsx',
        target: '@ui/sidebar-shell.tsx',
      }],
      registryDependencies: ['theme-seed', 'breadcrumb'],
    },
    {
      name: 'page-header',
      kind: 'block',
      layer: 3,
      description:
        'Composed page-intro block with shared badge, action, and status-row layout seams.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['layout', 'header', 'block'],
      files: [{
        source: 'registry/components/ui/page-header.tsx',
        target: '@ui/page-header.tsx',
      }],
      registryDependencies: ['theme-seed'],
    },
    {
      name: 'filter-form',
      kind: 'block',
      layer: 3,
      description:
        'Card-backed filter block for search, faceting, and action rails above directory tables.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['forms', 'filters', 'block'],
      files: [{
        source: 'registry/components/ui/filter-form.tsx',
        target: '@ui/filter-form.tsx',
      }],
      registryDependencies: ['theme-seed', 'card'],
    },
    {
      name: 'stats-grid',
      kind: 'block',
      layer: 3,
      description:
        'Responsive summary-metric grid for dashboard overview and route-level status cards.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['stats', 'dashboard', 'block'],
      files: [{
        source: 'registry/components/ui/stats-grid.tsx',
        target: '@ui/stats-grid.tsx',
      }],
      registryDependencies: ['theme-seed', 'card'],
    },
    {
      name: 'detail-layout',
      kind: 'block',
      layer: 3,
      description:
        'Two-column detail block for record pages with a primary flow and supporting side rail.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['detail', 'layout', 'block'],
      files: [{
        source: 'registry/components/ui/detail-layout.tsx',
        target: '@ui/detail-layout.tsx',
      }],
      registryDependencies: ['theme-seed'],
    },
    {
      name: 'data-table',
      kind: 'block',
      layer: 3,
      description: 'Composed table/list block with a shared header, row body, and footer seam.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['table', 'list', 'block'],
      files: [{
        source: 'registry/components/ui/data-table.tsx',
        target: '@ui/data-table.tsx',
      }],
      registryDependencies: ['theme-seed', 'card'],
    },
    {
      name: 'pagination',
      kind: 'block',
      layer: 3,
      description: 'Shared pagination meta/actions block for directory and activity lists.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['pagination', 'navigation', 'block'],
      files: [{
        source: 'registry/components/ui/pagination.tsx',
        target: '@ui/pagination.tsx',
      }],
      registryDependencies: ['theme-seed'],
    },
    {
      name: 'empty-state',
      kind: 'block',
      layer: 3,
      description:
        'Shared empty-state callout block for list rails, table gaps, and detail sidebars.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['empty-state', 'feedback', 'block'],
      files: [{
        source: 'registry/components/ui/empty-state.tsx',
        target: '@ui/empty-state.tsx',
      }],
      registryDependencies: ['theme-seed'],
    },
    {
      name: 'section-divider',
      kind: 'block',
      layer: 3,
      description: 'Editorial section label + rule block for detail and form pages.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['section', 'editorial', 'block'],
      files: [{
        source: 'registry/components/ui/section-divider.tsx',
        target: '@ui/section-divider.tsx',
      }],
      registryDependencies: ['theme-seed'],
    },
    {
      name: 'theme-toggle',
      kind: 'island',
      layer: 2,
      description: 'Small, generic Fresh island for dark/light theme switching.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['theme', 'island'],
      files: [{
        source: 'registry/islands/ThemeToggle.tsx',
        target: '@islands/ThemeToggle.tsx',
      }],
      registryDependencies: ['theme-seed'],
    },
    {
      name: 'sidebar-toggle',
      kind: 'island',
      layer: 3,
      description: 'Responsive mobile drawer toggle island for sidebar-shell consumers.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['dashboard', 'navigation', 'island'],
      files: [{
        source: 'registry/islands/SidebarToggle.tsx',
        target: '@islands/SidebarToggle.tsx',
      }],
      registryDependencies: ['theme-seed', 'sidebar-shell', 'button'],
    },
    {
      name: 'toast-support',
      kind: 'support',
      description: 'Query-string helpers for redirect-flash toasts.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['toast', 'helpers'],
      files: [{ source: 'registry/lib/toast.ts', target: '@lib/ui/toast.ts' }],
    },
    {
      name: 'toast',
      kind: 'island',
      layer: 2,
      description: 'Global notification island for redirect-flash feedback.',
      copyOwnership: 'app-owned-after-copy',
      author: 'NetScript',
      tags: ['toast', 'feedback', 'island'],
      files: [
        {
          source: 'registry/islands/Toast.tsx',
          target: '@islands/Toast.tsx',
        },
        {
          source: 'registry/components/ui/toast.css',
          target: '@assets/ui/toast.css',
        },
      ],
      registryDependencies: ['theme-seed', 'toast-support'],
      css: [{ layer: 'components', content: "@import './ui/toast.css';" }],
    },
  ],
  collections: [
    {
      name: 'foundation',
      description:
        'Expanded enterprise dashboard foundation: theme seed, installable A seams, and the first feedback/theme islands.',
      items: [
        'theme-seed',
        'sheet-styles',
        'button',
        'icon-button',
        'input',
        'textarea',
        'checkbox',
        'switch',
        'label',
        'select',
        'form-field',
        'card',
        'panel',
        'badge',
        'separator',
        'alert',
        'inline-notice',
        'spinner',
        'progress',
        'skeleton',
        'breadcrumb',
        'sidebar-shell',
        'page-header',
        'filter-form',
        'stats-grid',
        'detail-layout',
        'data-table',
        'pagination',
        'empty-state',
        'section-divider',
        'sidebar-toggle',
        'theme-toggle',
        'toast-support',
        'toast',
      ],
    },
    {
      name: 'forms-core',
      description:
        'Core action and form-control seams for CRUD pages, settings, and operational forms.',
      items: [
        'theme-seed',
        'button',
        'icon-button',
        'input',
        'textarea',
        'checkbox',
        'switch',
        'label',
        'select',
        'form-field',
      ],
    },
    {
      name: 'surface-core',
      description:
        'Reusable dashboard surface seams for cards, rails, separators, and status labels.',
      items: ['theme-seed', 'card', 'panel', 'badge', 'separator'],
    },
    {
      name: 'feedback-core',
      description:
        'Reusable persistent and transient feedback seams, including loading affordances.',
      items: [
        'theme-seed',
        'alert',
        'inline-notice',
        'spinner',
        'progress',
        'skeleton',
        'toast-support',
        'toast',
      ],
    },
    {
      name: 'layout-foundations',
      description:
        'CSS-first B seams shipped through theme-seed today: Stack, Cluster, Grid, Toolbar, Section, Split, and ScrollRegion.',
      items: ['theme-seed'],
    },
    {
      name: 'dashboard-blocks',
      description:
        'Layer-3 dashboard blocks for shell, page-intro, tables, stats, detail rails, and empty states.',
      items: [
        'theme-seed',
        'breadcrumb',
        'sidebar-shell',
        'sidebar-toggle',
        'page-header',
        'filter-form',
        'stats-grid',
        'detail-layout',
        'data-table',
        'pagination',
        'empty-state',
        'section-divider',
      ],
    },
  ],
} satisfies RegistryManifest;
