import type { RegistryManifest } from './schema.ts';

/**
 * Copy-based registry manifest for the published `@netscript/fresh-ui` foundation package.
 */
export const freshUiRegistryManifest = {
  name: 'fresh-ui-foundation',
  version: '0.1.0',
  packageName: '@netscript/fresh-ui',
  model: 'copy-based-registry',
  tokenSourceStrategy: 'css-seed-artifact-now-style-dictionary-later',
  items: [
    {
      name: 'theme-seed',
      kind: 'theme',
      description: 'Initial token, component-class, and CSS-first layout-object seed sourced from the playground.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['theme', 'tailwind-v4', 'tokens', 'style-dictionary-ready', 'layout-objects', 'dashboard-foundation'],
      files: [
        { source: 'registry/theme/styles.css', destination: 'assets/styles.css' },
        { source: 'registry/theme/tokens.css', destination: 'assets/tokens.css' },
        { source: 'registry/theme/layouts.css', destination: 'assets/layouts.css' },
        {
          source: 'registry/theme/components/actions.css',
          destination: 'assets/components/actions.css',
        },
        {
          source: 'registry/theme/components/forms.css',
          destination: 'assets/components/forms.css',
        },
        {
          source: 'registry/theme/components/surfaces.css',
          destination: 'assets/components/surfaces.css',
        },
        {
          source: 'registry/theme/components/feedback.css',
          destination: 'assets/components/feedback.css',
        },
      ],
    },
    {
      name: 'button',
      kind: 'component',
      layer: 2,
      description: 'Generic action primitive using semantic theme classes.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['forms', 'actions', 'primitive'],
      files: [{ source: 'registry/components/ui/button.tsx', destination: 'components/ui/button.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'icon-button',
      kind: 'component',
      layer: 2,
      description: 'Accessible icon-only action button built on the shared Button seam.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['actions', 'primitive', 'icon'],
      files: [{ source: 'registry/components/ui/icon-button.tsx', destination: 'components/ui/icon-button.tsx' }],
      dependencies: [
        { kind: 'theme', name: 'theme-seed' },
        { kind: 'component', name: 'button' },
      ],
    },
    {
      name: 'input',
      kind: 'component',
      layer: 2,
      description: 'Generic text input with token-driven error styling.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['forms', 'primitive'],
      files: [{ source: 'registry/components/ui/input.tsx', destination: 'components/ui/input.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'textarea',
      kind: 'component',
      layer: 2,
      description: 'Generic multi-line text input with the shared field styling contract.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['forms', 'primitive'],
      files: [{ source: 'registry/components/ui/textarea.tsx', destination: 'components/ui/textarea.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'checkbox',
      kind: 'component',
      layer: 2,
      description: 'CSS-first native checkbox seam with inline label and helper copy.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['forms', 'selection', 'primitive'],
      files: [{ source: 'registry/components/ui/checkbox.tsx', destination: 'components/ui/checkbox.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'switch',
      kind: 'component',
      layer: 2,
      description: 'CSS-first native switch seam for binary dashboard settings.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['forms', 'selection', 'primitive'],
      files: [{ source: 'registry/components/ui/switch.tsx', destination: 'components/ui/switch.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'label',
      kind: 'component',
      layer: 2,
      description: 'Accessible field label with required-state support.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['forms', 'primitive'],
      files: [{ source: 'registry/components/ui/label.tsx', destination: 'components/ui/label.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'select',
      kind: 'component',
      layer: 2,
      description: 'Native select wrapper with semantic token styling.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['forms', 'primitive'],
      files: [{ source: 'registry/components/ui/select.tsx', destination: 'components/ui/select.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'form-field',
      kind: 'component',
      layer: 2,
      description: 'Composed field wrapper for labels, help text, and errors.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['forms', 'composed'],
      files: [
        { source: 'registry/components/ui/form-field.tsx', destination: 'components/ui/form-field.tsx' },
      ],
      dependencies: [
        { kind: 'theme', name: 'theme-seed' },
        { kind: 'component', name: 'label' },
      ],
    },
    {
      name: 'card',
      kind: 'component',
      layer: 2,
      description: 'Primary content surface with header/body/footer sub-seams for dashboard composition.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['surface', 'container', 'primitive'],
      files: [{ source: 'registry/components/ui/card.tsx', destination: 'components/ui/card.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'panel',
      kind: 'component',
      layer: 2,
      description: 'Dense secondary surface for filters, rails, and grouped operational controls.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['surface', 'container', 'primitive'],
      files: [{ source: 'registry/components/ui/panel.tsx', destination: 'components/ui/panel.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'badge',
      kind: 'component',
      layer: 2,
      description: 'Compact semantic status seam for tags, counts, and entity state labels.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['status', 'feedback', 'primitive'],
      files: [{ source: 'registry/components/ui/badge.tsx', destination: 'components/ui/badge.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'separator',
      kind: 'component',
      layer: 2,
      description: 'Lightweight divider seam for cards, forms, panels, and toolbars.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['surface', 'layout', 'primitive'],
      files: [{ source: 'registry/components/ui/separator.tsx', destination: 'components/ui/separator.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'alert',
      kind: 'component',
      layer: 2,
      description: 'Persistent section-level feedback banner for success, warning, info, and error states.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['feedback', 'status', 'primitive'],
      files: [{ source: 'registry/components/ui/alert.tsx', destination: 'components/ui/alert.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'inline-notice',
      kind: 'component',
      layer: 2,
      description: 'Compact contextual feedback seam for inline guidance inside forms and panels.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['feedback', 'status', 'primitive'],
      files: [{ source: 'registry/components/ui/inline-notice.tsx', destination: 'components/ui/inline-notice.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'spinner',
      kind: 'component',
      layer: 2,
      description: 'Small loading indicator for async actions and deferred regions.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['feedback', 'loading', 'primitive'],
      files: [{ source: 'registry/components/ui/spinner.tsx', destination: 'components/ui/spinner.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'progress',
      kind: 'component',
      layer: 2,
      description: 'Determinate or indeterminate progress seam for jobs, uploads, and background work.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['feedback', 'loading', 'primitive'],
      files: [{ source: 'registry/components/ui/progress.tsx', destination: 'components/ui/progress.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'skeleton',
      kind: 'component',
      layer: 2,
      description: 'Generic dashboard loading scaffold for table, stats, detail, and form surfaces.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['feedback', 'loading', 'primitive'],
      files: [{ source: 'registry/components/ui/skeleton.tsx', destination: 'components/ui/skeleton.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'breadcrumb',
      kind: 'component',
      layer: 3,
      description: 'Accessible breadcrumb block for dashboard drill-down navigation.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['navigation', 'dashboard', 'block'],
      files: [{ source: 'registry/components/ui/breadcrumb.tsx', destination: 'components/ui/breadcrumb.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'sidebar-shell',
      kind: 'component',
      layer: 3,
      description: 'Reusable dashboard sidebar shell that accepts app-owned IA, breadcrumbs, and topbar actions.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['layout', 'dashboard', 'shell', 'block'],
      files: [{ source: 'registry/components/ui/sidebar-shell.tsx', destination: 'components/ui/sidebar-shell.tsx' }],
      dependencies: [
        { kind: 'theme', name: 'theme-seed' },
        { kind: 'component', name: 'breadcrumb' },
      ],
    },
    {
      name: 'page-header',
      kind: 'component',
      layer: 3,
      description: 'Composed page-intro block with shared badge, action, and status-row layout seams.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['layout', 'header', 'block'],
      files: [{ source: 'registry/components/ui/page-header.tsx', destination: 'components/ui/page-header.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'filter-form',
      kind: 'component',
      layer: 3,
      description: 'Card-backed filter block for search, faceting, and action rails above directory tables.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['forms', 'filters', 'block'],
      files: [{ source: 'registry/components/ui/filter-form.tsx', destination: 'components/ui/filter-form.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'stats-grid',
      kind: 'component',
      layer: 3,
      description: 'Responsive summary-metric grid for dashboard overview and route-level status cards.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['stats', 'dashboard', 'block'],
      files: [{ source: 'registry/components/ui/stats-grid.tsx', destination: 'components/ui/stats-grid.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }, { kind: 'component', name: 'card' }],
    },
    {
      name: 'detail-layout',
      kind: 'component',
      layer: 3,
      description: 'Two-column detail block for record pages with a primary flow and supporting side rail.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['detail', 'layout', 'block'],
      files: [{ source: 'registry/components/ui/detail-layout.tsx', destination: 'components/ui/detail-layout.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'data-table',
      kind: 'component',
      layer: 3,
      description: 'Composed table/list block with a shared header, row body, and footer seam.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['table', 'list', 'block'],
      files: [{ source: 'registry/components/ui/data-table.tsx', destination: 'components/ui/data-table.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }, { kind: 'component', name: 'card' }],
    },
    {
      name: 'pagination',
      kind: 'component',
      layer: 3,
      description: 'Shared pagination meta/actions block for directory and activity lists.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['pagination', 'navigation', 'block'],
      files: [{ source: 'registry/components/ui/pagination.tsx', destination: 'components/ui/pagination.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'empty-state',
      kind: 'component',
      layer: 3,
      description: 'Shared empty-state callout block for list rails, table gaps, and detail sidebars.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['empty-state', 'feedback', 'block'],
      files: [{ source: 'registry/components/ui/empty-state.tsx', destination: 'components/ui/empty-state.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'section-divider',
      kind: 'component',
      layer: 3,
      description: 'Editorial section label + rule block for detail and form pages.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['section', 'editorial', 'block'],
      files: [{ source: 'registry/components/ui/section-divider.tsx', destination: 'components/ui/section-divider.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'theme-toggle',
      kind: 'island',
      layer: 2,
      description: 'Small, generic Fresh island for dark/light theme switching.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['theme', 'island'],
      files: [{ source: 'registry/islands/ThemeToggle.tsx', destination: 'islands/ThemeToggle.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }],
    },
    {
      name: 'sidebar-toggle',
      kind: 'island',
      layer: 3,
      description: 'Responsive mobile drawer toggle island for sidebar-shell consumers.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['dashboard', 'navigation', 'island'],
      files: [{ source: 'registry/islands/SidebarToggle.tsx', destination: 'islands/SidebarToggle.tsx' }],
      dependencies: [{ kind: 'theme', name: 'theme-seed' }, { kind: 'component', name: 'sidebar-shell' }],
    },
    {
      name: 'toast-support',
      kind: 'support',
      description: 'Query-string helpers for redirect-flash toasts.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['toast', 'helpers'],
      files: [{ source: 'registry/lib/toast.ts', destination: 'lib/ui/toast.ts' }],
    },
    {
      name: 'toast',
      kind: 'island',
      layer: 2,
      description: 'Global notification island for redirect-flash feedback.',
      copyOwnership: 'app-owned-after-copy',
      tags: ['toast', 'feedback', 'island'],
      files: [{ source: 'registry/islands/Toast.tsx', destination: 'islands/Toast.tsx' }],
      dependencies: [
        { kind: 'theme', name: 'theme-seed' },
        { kind: 'support', name: 'toast-support' },
      ],
    },
  ],
  collections: [
    {
      name: 'foundation',
      description: 'Expanded enterprise dashboard foundation: theme seed, installable A seams, and the first feedback/theme islands.',
      items: [
        'theme-seed',
        'button',
        'icon-button',
        'input',
        'textarea',
        'checkbox',
        'switch',
        'label',
        'select',
        'form-field',
        'card',
        'panel',
        'badge',
        'separator',
        'alert',
        'inline-notice',
        'spinner',
        'progress',
        'skeleton',
        'breadcrumb',
        'sidebar-shell',
        'page-header',
        'filter-form',
        'stats-grid',
        'detail-layout',
        'data-table',
        'pagination',
        'empty-state',
        'section-divider',
        'sidebar-toggle',
        'theme-toggle',
        'toast-support',
        'toast',
      ],
    },
    {
      name: 'forms-core',
      description: 'Core action and form-control seams for CRUD pages, settings, and operational forms.',
      items: ['theme-seed', 'button', 'icon-button', 'input', 'textarea', 'checkbox', 'switch', 'label', 'select', 'form-field'],
    },
    {
      name: 'surface-core',
      description: 'Reusable dashboard surface seams for cards, rails, separators, and status labels.',
      items: ['theme-seed', 'card', 'panel', 'badge', 'separator'],
    },
    {
      name: 'feedback-core',
      description: 'Reusable persistent and transient feedback seams, including loading affordances.',
      items: ['theme-seed', 'alert', 'inline-notice', 'spinner', 'progress', 'skeleton', 'toast-support', 'toast'],
    },
    {
      name: 'layout-foundations',
      description: 'CSS-first B seams shipped through theme-seed today: Stack, Cluster, Grid, Toolbar, Section, Split, and ScrollRegion.',
      items: ['theme-seed'],
    },
    {
      name: 'dashboard-blocks',
      description: 'Layer-3 dashboard blocks for shell, page-intro, tables, stats, detail rails, and empty states.',
      items: ['theme-seed', 'breadcrumb', 'sidebar-shell', 'sidebar-toggle', 'page-header', 'filter-form', 'stats-grid', 'detail-layout', 'data-table', 'pagination', 'empty-state', 'section-divider'],
    },
  ],
} satisfies RegistryManifest;
