/** Type-checked source stub for the generated workers runtime glue.
 *
 * @module
 */

import { defineStub, type StubSource } from '@netscript/plugin/adapter';

/** Workers background runtime glue stub. */
export const runtimeGlueStub: StubSource<never> = defineStub({
  source: [
    '/** Runtime glue emitted into generated projects for the workers background process.',
    ' *',
    ' * @module',
    ' */',
    '',
    "import type { StaticJobRegistry } from '@netscript/plugin-workers-core/runtime';",
    'import {',
    '  startCombinedProcess,',
    '  type StaticJobDefinitionRegistry,',
    "} from '@netscript/plugin-workers/runtime';",
    '',
    'if (import.meta.main) {',
    '  await startCombinedProcess(await loadGeneratedJobs());',
    '}',
    '',
    'async function loadGeneratedJobs(): Promise<',
    '  Readonly<{',
    '    definitions?: StaticJobDefinitionRegistry;',
    '    registry?: StaticJobRegistry;',
    '  }>',
    '> {',
    "  const registryUrl = projectFileUrl('.netscript/generated/plugin-workers/jobs.registry.ts');",
    '',
    '  try {',
    '    await Deno.stat(registryUrl);',
    '  } catch (error) {',
    '    if (error instanceof Deno.errors.NotFound) return {};',
    '    throw error;',
    '  }',
    '',
    '  const module = await import(registryUrl.href);',
    '  const definitions = isStaticJobDefinitionRegistry(module.jobDefinitions)',
    '    ? module.jobDefinitions',
    '    : isStaticJobDefinitionRegistry(module.definitions)',
    '    ? module.definitions',
    '    : undefined;',
    '  const registry = isStaticJobRegistry(module.registry) ? module.registry : undefined;',
    '',
    '  return { definitions, registry };',
    '}',
    '',
    'function isStaticJobDefinitionRegistry(value: unknown): value is StaticJobDefinitionRegistry {',
    '  return value instanceof Map;',
    '}',
    '',
    'function isStaticJobRegistry(value: unknown): value is StaticJobRegistry {',
    '  return value instanceof Map;',
    '}',
    '',
    'function projectFileUrl(relativePath: string): URL {',
    "  const root = Deno.cwd().replaceAll('\\\\', '/');",
    "  const normalizedRoot = root.endsWith('/') ? root : `${root}/`;",
    "  const base = normalizedRoot.startsWith('/')",
    '    ? `file://${normalizedRoot}`',
    '    : `file:///${normalizedRoot}`;',
    '  return new URL(relativePath, base);',
    '}',
    '',
  ].join('\n'),
  tokens: [],
});
