// @generated by .llm/tools/generate-publish-assets.ts
// Do not edit by hand. Run `deno task gen:publish-assets`.

/** Version of the published core package. */
export const CORE_PACKAGE_VERSION: string = '0.0.7-canary.7';
