/** Inline scripts used by scaffold runtime behavior gates. */

export const VALIDATE_AI_CHAT_ROUTE_SCRIPT = [
  'const projectRoot = Deno.args[0];',
  'if (!projectRoot) throw new Error("project root argument is required");',
  'const route = await import(`file://${projectRoot}/ai/routes/chat-stream.ts`);',
  'const composition = await import(`file://${projectRoot}/ai/ai.ts`);',
  'if (typeof route.handler !== "function") throw new Error("AI chat-stream handler is not exported");',
  'if (typeof route.aiRouter !== "object" || route.aiRouter === null) {',
  '  throw new Error("AI chat-stream route did not export a contract-bound aiRouter");',
  '}',
  'if (typeof route.aiRouteContract !== "object" || route.aiRouteContract === null) {',
  '  throw new Error("AI chat-stream route did not export aiContractV1 handle");',
  '}',
  'const handler = composition.ai().tools.resolveHandler("e2e-tool");',
  'if (typeof handler !== "function") throw new Error("plugin ai add tool did not self-wire e2e-tool");',
  'const result = await handler({ id: "e2e", name: "e2e-tool", arguments: JSON.stringify({ query: "ping" }), state: "input-complete" });',
  'if (!result || result.state === "error") throw new Error("self-wired e2e-tool was not callable");',
  'console.info("AI chat route contract import smoke passed");',
].join('\n');

export const PROBE_SERVICE_HEALTH_SCRIPT = [
  'const appHost = Deno.args[0];',
  'const resourceName = Deno.args[1] ?? "users";',
  'const database = Deno.args[2];',
  'if (!appHost) throw new Error("apphost argument is required");',
  'const command = new Deno.Command("aspire", {',
  '  args: ["describe", "--apphost", appHost, "--format", "Json"],',
  '  stdout: "piped",',
  '  stderr: "piped",',
  '});',
  'const output = await command.output();',
  'const stdout = new TextDecoder().decode(output.stdout);',
  'const stderr = new TextDecoder().decode(output.stderr);',
  'if (!output.success) {',
  '  throw new Error(`aspire describe failed with code ${output.code}: ${stderr || stdout}`);',
  '}',
  'const topology = JSON.parse(extractJson(stdout));',
  'const resource = findResource(topology, resourceName);',
  'if (!resource) {',
  '  throw new Error(`resource ${resourceName} was not present in aspire describe output`);',
  '}',
  'const urls = collectHttpUrls(resource);',
  'if (urls.length === 0) {',
  '  throw new Error(`resource ${resourceName} did not expose an HTTP endpoint in aspire describe output`);',
  '}',
  'const errors = [];',
  'for (const baseUrl of urls) {',
  '  const healthUrl = new URL("/health", baseUrl).toString();',
  '  const result = await probe(healthUrl);',
  '  if (result.ok && aggregateHealthMatches(result.body, database)) {',
  '    console.info(`service health probe passed: ${healthUrl} -> ${result.status}`);',
  '    Deno.exit(0);',
  '  }',
  '  errors.push(`${healthUrl} -> ${result.status}: ${result.body.slice(0, 200)}`);',
  '}',
  'throw new Error(`service health probe failed for ${resourceName}: ${errors.join("; ")}`);',
  '',
  'function aggregateHealthMatches(body, expectedDatabase) {',
  '  let health;',
  '  try {',
  '    health = JSON.parse(body);',
  '  } catch {',
  '    return false;',
  '  }',
  '  if (!isRecord(health) || health.status !== "healthy" || !Array.isArray(health.checks)) {',
  '    return false;',
  '  }',
  '  if (expectedDatabase === undefined) return true;',
  '  const databaseChecks = health.checks',
  '    .filter(isRecord)',
  '    .map((check) => check.name)',
  '    .filter((name) => typeof name === "string" && name.startsWith("database"));',
  '  const expectedNames = new Set(["database", `database:${expectedDatabase}`]);',
  '  return databaseChecks.length === 1 && expectedNames.has(databaseChecks[0]);',
  '}',
  '',
  'function extractJson(text) {',
  '  const trimmed = text.trim();',
  '  if (trimmed.startsWith("{") || trimmed.startsWith("[")) return trimmed;',
  '  const objectIndex = trimmed.indexOf("{");',
  '  const arrayIndex = trimmed.indexOf("[");',
  '  const indexes = [objectIndex, arrayIndex].filter((index) => index >= 0);',
  '  if (indexes.length === 0) throw new Error("aspire describe did not emit JSON");',
  '  return trimmed.slice(Math.min(...indexes));',
  '}',
  '',
  'function findResource(value, name) {',
  '  if (!isRecord(value)) return undefined;',
  '  if (resourceNameMatches(value, name)) return value;',
  '  for (const child of Object.values(value)) {',
  '    if (Array.isArray(child)) {',
  '      for (const item of child) {',
  '        const match = findResource(item, name);',
  '        if (match) return match;',
  '      }',
  '      continue;',
  '    }',
  '    const match = findResource(child, name);',
  '    if (match) return match;',
  '  }',
  '  return undefined;',
  '}',
  '',
  'function resourceNameMatches(value, name) {',
  '  for (const key of ["name", "displayName", "resourceName"]) {',
  '    const candidate = value[key];',
  '    if (typeof candidate === "string" && candidate.toLowerCase() === name.toLowerCase()) {',
  '      return true;',
  '    }',
  '  }',
  '  return false;',
  '}',
  '',
  'function collectHttpUrls(value) {',
  '  const urls = new Set();',
  '  collect(value, urls);',
  '  return [...urls];',
  '}',
  '',
  'function collect(value, urls) {',
  '  if (typeof value === "string") {',
  '    if (/^https?:\\/\\//i.test(value)) urls.add(value);',
  '    return;',
  '  }',
  '  if (Array.isArray(value)) {',
  '    for (const item of value) collect(item, urls);',
  '    return;',
  '  }',
  '  if (!isRecord(value)) return;',
  '  for (const child of Object.values(value)) collect(child, urls);',
  '}',
  '',
  'function isRecord(value) {',
  '  return typeof value === "object" && value !== null && !Array.isArray(value);',
  '}',
  '',
  'async function probe(url) {',
  '  for (let attempt = 1; attempt <= 30; attempt++) {',
  '    try {',
  '      const response = await fetch(url);',
  '      const body = await response.text();',
  '      if (response.ok) return { ok: true, status: response.status, body };',
  '      if (attempt === 30) return { ok: false, status: response.status, body: body.slice(0, 200) };',
  '    } catch (error) {',
  '      if (attempt === 30) {',
  '        return { ok: false, status: 0, body: error instanceof Error ? error.message : String(error) };',
  '      }',
  '    }',
  '    await new Promise((resolve) => setTimeout(resolve, 1_000));',
  '  }',
  '  return { ok: false, status: 0, body: "probe exhausted without a request" };',
  '}',
].join('\n');
