/** Inline scripts used by scaffold runtime lifecycle gates. */

import { KV_BACKGROUND_RUNTIME_RESOURCES } from '../../../../domain/cli-surface.ts';

export const ASPIRE_START_SCRIPT = [
  'const appHost = Deno.args[0];',
  'const projectRoot = Deno.args[1];',
  'if (!appHost) throw new Error("apphost argument is required");',
  'if (!projectRoot) throw new Error("project root argument is required");',
  'const configPath = `${projectRoot}/aspire.config.json`;',
  'const config = JSON.parse(await Deno.readTextFile(configPath));',
  'const environmentVariables = config.profiles?.https?.environmentVariables;',
  'if (!environmentVariables) throw new Error("aspire.config.json omitted profiles.https.environmentVariables");',
  'const dashboardAnonymousKey = "ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS";',
  'environmentVariables[dashboardAnonymousKey] = "false";',
  'await Deno.writeTextFile(configPath, `${JSON.stringify(config, null, 2)}\n`);',
  'const command = new Deno.Command("aspire", {',
  '  args: [',
  '    "start",',
  '    "--apphost",',
  '    appHost,',
  '    "--isolated",',
  '    "--non-interactive",',
  '    "--nologo",',
  '    "--format",',
  '    "Json",',
  '  ],',
  '  stdout: "piped",',
  '  stderr: "piped",',
  '});',
  'const output = await command.output();',
  'const stdout = new TextDecoder().decode(output.stdout);',
  'const stderr = new TextDecoder().decode(output.stderr);',
  'if (!output.success) {',
  '  throw new Error(`aspire start failed with code ${output.code}: ${stderr || stdout}`);',
  '}',
  'const metadata = JSON.parse(extractJson(stdout));',
  'if (!metadata.dashboardUrl) throw new Error("aspire start did not report dashboardUrl");',
  'const stateDir = `${projectRoot}/.netscript/e2e`;',
  'await Deno.mkdir(stateDir, { recursive: true });',
  'await Deno.writeTextFile(`${stateDir}/aspire-start.json`, JSON.stringify(metadata, null, 2));',
  'console.info(`Aspire dashboard: ${metadata.dashboardUrl}`);',
  'if (metadata.logFile) console.info(`Aspire log: ${metadata.logFile}`);',
  '',
  'function extractJson(text) {',
  '  const trimmed = text.trim();',
  '  const objectIndex = trimmed.indexOf("{");',
  '  if (objectIndex < 0) throw new Error("aspire start did not emit JSON");',
  '  return trimmed.slice(objectIndex);',
  '}',
].join('\n');

export const ASPIRE_RESTART_SCRIPT = [
  'const stop = await new Deno.Command("aspire", {',
  '  args: ["stop", "--apphost", Deno.args[0], "--non-interactive", "--nologo"],',
  '  stdout: "inherit",',
  '  stderr: "inherit",',
  '}).spawn().status;',
  'if (!stop.success) throw new Error(`aspire stop failed with code ${stop.code}`);',
  ASPIRE_START_SCRIPT,
].join('\n');

/**
 * Prefer the S8 typed migration command; retain the full restart for older/failing surfaces.
 *
 * A successful migrate must leave the AppHost resident, but the KV-backed background runtimes
 * it does not restart would keep processing against the pre-migration database — #1720's
 * "health-check execution has not completed yet". So the success path restarts only those
 * resources (`aspire resource <name> restart`), and the full AppHost restart stays strictly as
 * the fallback for surfaces that can run neither the typed command nor a targeted restart.
 */
export const ASPIRE_TYPED_DB_COMMAND_OR_RESTART_SCRIPT = [
  'const database = Deno.args[2];',
  'if (!database) throw new Error("database argument is required");',
  'const typed = await new Deno.Command("aspire", {',
  '  args: [',
  '    "resource", `${database}-cli`, "migrate", "--timeout", "60",',
  '    "--apphost", Deno.args[0], "--non-interactive", "--nologo",',
  '  ],',
  '  stdout: "inherit",',
  '  stderr: "inherit",',
  '}).spawn().status;',
  'if (typed.success) {',
  '  console.info(`typed ${database}-cli migrate completed; resident AppHost preserved`);',
  '  await restartBackgroundRuntimes();',
  '} else {',
  '  console.warn(`typed database command exited ${typed.code}; using restart fallback`);',
  ASPIRE_RESTART_SCRIPT,
  '}',
  '',
  'async function restartBackgroundRuntimes() {',
  `  const runtimes = ${JSON.stringify([...KV_BACKGROUND_RUNTIME_RESOURCES])};`,
  '  for (const resource of runtimes) {',
  '    const restart = await new Deno.Command("aspire", {',
  '      args: [',
  '        "resource", resource, "restart",',
  '        "--apphost", Deno.args[0], "--non-interactive", "--nologo",',
  '      ],',
  '      stdout: "inherit",',
  '      stderr: "inherit",',
  '    }).spawn().status;',
  '    if (!restart.success) {',
  '      console.warn(',
  '        `aspire resource ${resource} restart exited ${restart.code}; using restart fallback`,',
  '      );',
  ASPIRE_RESTART_SCRIPT,
  '      return;',
  '    }',
  '    console.info(`restarted ${resource}; background processors now observe the migrated database`);',
  '  }',
  '}',
].join('\n');

export const AUTH_SMOKE_ENV_SCRIPT = [
  'const projectRoot = Deno.args[0];',
  'const repoRoot = Deno.args[1];',
  'if (!projectRoot) throw new Error("project root argument is required");',
  'if (!repoRoot) throw new Error("repo root argument is required");',
  'const cli = `${repoRoot}/packages/cli/bin/netscript-dev.ts`;',
  'async function run(args: string[]): Promise<string> {',
  '  const result = await new Deno.Command("deno", { args: ["run", "-A", cli, ...args], cwd: projectRoot }).output();',
  '  const stdout = new TextDecoder().decode(result.stdout).trim();',
  '  const stderr = new TextDecoder().decode(result.stderr).trim();',
  '  if (!result.success) throw new Error(`auth CLI failed: ${args.join(" ")}: ${stderr}`);',
  '  return stdout;',
  '}',
  'await run(["plugin", "auth", "backend", "set", "kv-oauth", "--project-root", projectRoot]);',
  'const key = await run(["plugin", "auth", "secret", "generate", "kv-oauth-key"]);',
  'await run([',
  '  "plugin", "auth", "provider", "set", "--preset", "github",',
  '  "--client-id", "scaffold_runtime_smoke",',
  '  "--client-secret", "scaffold_runtime_smoke_secret",',
  '  "--redirect-uri", "http://localhost/api/v1/auth/callback",',
  '  "--kv-oauth-key", key, "--project-root", projectRoot,',
  ']);',
  'const configured = JSON.parse(await Deno.readTextFile(`${projectRoot}/appsettings.json`));',
  'if (configured.Auth?.Backend !== "kv-oauth") throw new Error("auth backend CLI did not persist appsettings");',
  'if (configured.NetScript?.Plugins?.auth?.Environment?.NETSCRIPT_AUTH_PROVIDER_ID !== "github") throw new Error("auth provider CLI did not persist plugin environment");',
].join('\n');
