/**
 * Type-safe plugin scaffold primitives for generated userland glue.
 *
 * This subpath is the author-facing scaffold surface. It re-exports the shared
 * item-scaffolder contracts and provides deterministic registry source
 * generators that operate on structured module entries instead of free-form
 * templates.
 *
 * @example
 * ```ts
 * import { defineRegistryModule, renderRegistrySource } from '@netscript/plugin/scaffold';
 *
 * const source = renderRegistrySource(defineRegistryModule({
 *   imports: [{ alias: 'job0', specifier: '../jobs/send-email.ts' }],
 *   exportName: 'jobRegistry',
 *   entries: ['job0'],
 * }));
 * ```
 *
 * @module
 */

export type { ItemScaffolder } from '../adapter/item/item-scaffolder.ts';
export type { ScaffoldArtifact, ScaffoldArtifactBody } from '../adapter/item/artifact.ts';
export { artifactText, textArtifact } from '../adapter/item/artifact.ts';
export type { StubSource, TokenValues } from '../adapter/item/substitute.ts';
export { defineStub, substituteTokens } from '../adapter/item/substitute.ts';

/** Import declaration emitted into a generated registry module. */
export interface RegistryImport {
  /** Local identifier used inside the generated registry. */
  readonly alias: string;
  /** Relative import specifier from the generated registry file. */
  readonly specifier: string;
}

/** Structured description of a generated registry module. */
export interface RegistryModule {
  /** Imports required by registry entries. */
  readonly imports: readonly RegistryImport[];
  /** Exported registry variable name. */
  readonly exportName: string;
  /** Entry expressions included in the exported array. */
  readonly entries: readonly string[];
  /** Optional module-level comment lines. */
  readonly header?: readonly string[];
}

/** Structured description of a generated runtime registry module. */
export interface RuntimeRegistryModule extends RegistryModule {
  /** Runtime start binding exported by the generated module. */
  readonly runtimeExportName: string;
  /** Registry expression passed to the runtime start binding. */
  readonly registryExpression: string;
}

/**
 * Preserve a registry module definition with literal field types.
 *
 * @param module - Structured registry module definition.
 * @returns The same definition, typed as a registry module.
 */
export function defineRegistryModule<TModule extends RegistryModule>(module: TModule): TModule {
  return module;
}

/**
 * Preserve a runtime registry module definition with literal field types.
 *
 * @param module - Structured runtime registry module definition.
 * @returns The same definition, typed as a runtime registry module.
 */
export function defineRuntimeRegistryModule<TModule extends RuntimeRegistryModule>(
  module: TModule,
): TModule {
  return module;
}

/**
 * Render a deterministic registry module from structured import and entry data.
 *
 * @param module - Registry module definition.
 * @returns TypeScript source for the generated registry.
 */
export function renderRegistrySource(module: RegistryModule): string {
  return [
    ...renderHeader(module.header),
    ...module.imports.map(renderImport),
    module.imports.length > 0 ? '' : undefined,
    `export const ${module.exportName} = [`,
    ...module.entries.map((entry) => `  ${entry},`),
    '] as const;',
    '',
  ].filter((line): line is string => line !== undefined).join('\n');
}

/**
 * Render a deterministic runtime registry module from structured source data.
 *
 * @param module - Runtime registry module definition.
 * @returns TypeScript source for the generated runtime registry.
 */
export function renderRuntimeRegistrySource(module: RuntimeRegistryModule): string {
  return [
    renderRegistrySource(module).trimEnd(),
    '',
    `export const ${module.runtimeExportName} = ${module.registryExpression};`,
    '',
  ].join('\n');
}

function renderHeader(header: readonly string[] | undefined): readonly string[] {
  if (header === undefined || header.length === 0) {
    return ['// <auto-generated />', ''];
  }
  return [...header, ''];
}

function renderImport(entry: RegistryImport): string {
  return `import * as ${entry.alias} from ${JSON.stringify(entry.specifier)};`;
}
