/**
 * @module
 *
 * Shared code-generation utilities for the CLI helpers generator.
 * Internal module — not exported from the package barrel.
 *
 * Provides DRY helpers for file headers, identifier normalization,
 * property quoting, and indentation used by all generator functions.
 */

/** Standard two-line header for all generated files. */
export function fileHeader(filename: string): string {
  return [
    `// ${filename} — GENERATED BY @netscript/cli. DO NOT EDIT.`,
    `// Re-run \`netscript generate\` to regenerate after config changes.`,
  ].join('\n');
}

/**
 * Converts a resource name to a valid TypeScript identifier.
 * Replaces hyphens with underscores: `"sample-api"` -> `"sample_api"`.
 *
 * @param name - Resource name from appsettings.json
 * @returns Valid TypeScript identifier
 */
export function safeIdentifier(name: string): string {
  return name.replace(/-/g, '_');
}

/**
 * Wraps a property key in quotes if it contains special characters.
 * Returns the key as-is if it's a valid unquoted identifier.
 *
 * @param name - Property key name
 * @returns Quoted or unquoted key suitable for object literals
 *
 * @example
 * ```ts
 * quoteProperty('users')       // 'users'
 * quoteProperty('sample-api') // "'sample-api'"
 * ```
 */
export function quoteProperty(name: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : `'${name}'`;
}

/**
 * Indents every line of text by the specified number of levels (2 spaces each).
 *
 * @param text - The text to indent
 * @param level - Number of indent levels (default: 1)
 * @returns Indented text
 */
export function indent(text: string, level: number = 1): string {
  const prefix = '  '.repeat(level);
  return text
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : prefix + line))
    .join('\n');
}

/**
 * Joins lines, filtering out falsy values, with newline separator.
 * Useful for conditionally including code blocks in generated output.
 *
 * @param lines - Lines to join (falsy values are filtered out)
 * @returns Joined string
 */
export function joinLines(
  ...lines: (string | false | null | undefined)[]
): string {
  return lines.filter(Boolean).join('\n');
}

/**
 * Checks whether a record has any entries.
 * Used to conditionally include sections in generated schemas.
 *
 * @param record - The record to check
 * @returns true if the record has at least one entry
 */
export function hasEntries(record: Record<string, unknown>): boolean {
  return Object.keys(record).length > 0;
}
