export type {
  MetricQueryFilter,
  ResourceQueryFilter,
  TelemetryAttributeValue,
  TelemetryLog,
  TelemetryMetric,
  TelemetryMetricPoint,
  TelemetryMetricType,
  TelemetryOtlpJson,
  TelemetryResource,
  TelemetrySpan,
  TelemetrySpanEvent,
  TelemetrySpanKind,
  TelemetrySpanLink,
  TelemetryTrace,
  TraceQueryFilter,
} from '../../domain/query.ts';
