/**
 * Public structural contracts for NetScript service builders and handlers.
 *
 * @module
 */

/** Router definition accepted by the service builder and handler factories. */
export type ServiceRouter = Record<string, unknown>;

/** Minimal mountable service application returned by `build()`. */
export interface ServiceApp {
  /** Handles a Web Platform request without starting a listener. */
  fetch(request: Request): Response | Promise<Response>;

  /** Executes an in-memory request against the service app. */
  request(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
}

/** Network address assigned to a running service listener. */
export interface RunningServiceAddress {
  /** Listener hostname. */
  hostname: string;

  /** Listener port. */
  port: number;

  /** Listener transport. */
  transport: 'tcp' | 'unix';
}

/** Running service handle returned by `serve()` and `defineService()`. */
export interface RunningService {
  /** Mountable service app backing the running listener. */
  app: ServiceApp;

  /** Address selected by Deno for the listener. */
  addr: RunningServiceAddress;

  /** Stops the listener and waits for shutdown to finish. */
  stop(): Promise<void>;
}

/** Options for starting a service listener. */
export interface ServeOptions {
  /** Preferred listener port; use `0` for an ephemeral port. */
  port?: number;

  /** External signal that stops the listener when aborted. */
  signal?: AbortSignal;
}

/** Result returned by oRPC-compatible fetch handlers. */
export interface FetchHandlerResult {
  /** Whether the handler matched the request path. */
  matched: boolean;

  /** Response generated by the handler. */
  response: Response;
}

/** Structural fetch handler used by RPC and OpenAPI service adapters. */
export interface FetchHandler {
  /** Handles a request with path prefix and service context options. */
  handle(
    request: Request,
    options: { prefix: `/${string}`; context?: Record<string, unknown> },
  ): Promise<FetchHandlerResult>;
}

/** Structural oRPC plugin accepted by service handler factories. */
export interface ServiceHandlerPlugin {
  /** Initializes the plugin against the handler runtime. */
  init?(options: unknown): void | Promise<void>;
}

/** Minimal request shape exposed to service middleware and handlers. */
export interface ServiceRequest {
  /** Raw Web Platform request. */
  raw: Request;

  /** Matched request path. */
  path: string;

  /** Reads a request header by name. */
  header(name: string): string | undefined;
}

/** Minimal context shape exposed to service middleware and handlers. */
export interface ServiceContext {
  /** Request wrapper for the current service call. */
  req: ServiceRequest;

  /** Creates a JSON response. */
  json(data: unknown, status?: number): Response;

  /** Creates an HTML response. */
  html(html: string, status?: number): Response;

  /** Creates a raw body response. */
  body(data: BodyInit | null, status?: number, headers?: HeadersInit): Response;

  /** Creates a response from an existing response or init object. */
  newResponse(data?: BodyInit | null, init?: Response | ResponseInit): Response;

  /** Reads request-scoped middleware state. */
  get(key: string): unknown;
}

/** Middleware function accepted by the service builder. */
export type ServiceMiddleware = (
  context: ServiceContext,
  next: () => Promise<void>,
) => Promise<Response | void>;

/** Service route handler accepted by the builder route API. */
export type ServiceHandler = (
  context: ServiceContext,
) => Response | Promise<Response>;

/** Error handler used by service applications. */
export type ServiceErrorHandler = (
  error: Error,
  context: ServiceContext,
) => Response | Promise<Response>;

/** CORS options supported by `withCors()`. */
export interface CorsOptions {
  /** Allowed origin value or matcher. */
  origin?:
    | string
    | string[]
    | ((origin: string, context: ServiceContext) => string | undefined);

  /** Allowed HTTP methods. */
  allowMethods?: string[];

  /** Allowed request headers. */
  allowHeaders?: string[];

  /** Exposed response headers. */
  exposeHeaders?: string[];

  /** Preflight cache duration in seconds. */
  maxAge?: number;

  /** Whether credentials are allowed. */
  credentials?: boolean;
}

/** Database client capable of a health-check query. */
export interface Database {
  /** Executes a raw SQL template query. */
  $queryRaw(query: TemplateStringsArray): Promise<unknown>;
}

/** Database context injected into service handler context. */
export type DbContext = Record<string, unknown>;

/** Creates per-request service handler context. */
export type ContextFactory = (
  context: ServiceContext,
) => Record<string, unknown>;
