/**
 * Public structural contracts for NetScript service builders and handlers.
 *
 * @module
 */

/** Router definition accepted by the service builder and handler factories. */
export type ServiceRouter = Record<string, unknown>;

/** Minimal mountable service application returned by `build()`. */
export interface ServiceApp {
  /** Handles a Web Platform request without starting a listener. */
  fetch(request: Request): Response | Promise<Response>;

  /** Executes an in-memory request against the service app. */
  request(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
}

/** Network address assigned to a running service listener. */
export interface RunningServiceAddress {
  /** Listener hostname. */
  hostname: string;

  /** Listener port. */
  port: number;

  /** Listener transport. */
  transport: 'tcp' | 'unix';
}

/** Running service handle returned by `serve()` and `defineService()`. */
export interface RunningService {
  /** Mountable service app backing the running listener. */
  app: ServiceApp;

  /** Address selected by Deno for the listener. */
  addr: RunningServiceAddress;

  /** Stops the listener and waits for shutdown to finish. */
  stop(): Promise<void>;
}

/**
 * Reason a service shutdown was triggered.
 *
 * @example
 * ```typescript
 * const reason: ShutdownReason = 'manual';
 * ```
 */
export type ShutdownReason = 'signal' | 'manual' | 'startup-failure';

/**
 * Context passed to shutdown hooks during graceful service drain.
 *
 * @example
 * ```typescript
 * createService(router, { name: 'users' })
 *   .onShutdown(({ reason, signal }) => {
 *     audit.record({ reason, signal });
 *   });
 * ```
 */
export interface ShutdownContext {
  /** Why shutdown was triggered. */
  readonly reason: ShutdownReason;

  /** OS signal that triggered shutdown, when reason is `signal`. */
  readonly signal?: Deno.Signal;
}

/**
 * Async teardown hook registered with `ServiceBuilder.onShutdown()`.
 *
 * @example
 * ```typescript
 * const closeDatabase: ShutdownHook = async () => {
 *   await db.$disconnect();
 * };
 * ```
 */
export type ShutdownHook = (
  context: ShutdownContext,
) => Promise<void> | void;

/**
 * Per-hook outcome captured during graceful drain.
 *
 * @example
 * ```typescript
 * const outcome: ShutdownHookOutcome = { ok: true };
 * ```
 */
export interface ShutdownHookOutcome {
  /** True when the hook completed without throwing. */
  readonly ok: boolean;

  /** Normalized failure message when the hook rejects or throws. */
  readonly error?: string;
}

/**
 * Result of a completed service shutdown.
 *
 * @example
 * ```typescript
 * const report: ShutdownReport = {
 *   reason: 'manual',
 *   timedOut: false,
 *   hooks: [{ ok: true }],
 * };
 * ```
 */
export interface ShutdownReport {
  /** Why shutdown was triggered. */
  readonly reason: ShutdownReason;

  /** True when the drain timeout elapsed before all work settled. */
  readonly timedOut: boolean;

  /** Per-hook outcomes in execution order. */
  readonly hooks: readonly ShutdownHookOutcome[];
}

/**
 * Options for starting a service listener.
 *
 * @example
 * ```typescript
 * const running = await createService(router, { name: 'users' })
 *   .withHealth()
 *   .serve({
 *     port: 3000,
 *     drainTimeoutMs: 10_000,
 *     handleSignals: true,
 *   });
 *
 * await running.stop();
 * ```
 */
export interface ServeOptions {
  /** Preferred listener port; use `0` for an ephemeral port. */
  port?: number;

  /** External signal that stops the listener when aborted. */
  signal?: AbortSignal;

  /** Max time to wait for in-flight requests and shutdown hooks. Defaults to `30_000`. */
  drainTimeoutMs?: number;

  /** Install SIGINT/SIGTERM or SIGBREAK handlers. Defaults to `true`. */
  handleSignals?: boolean;
}

/** Result returned by oRPC-compatible fetch handlers. */
export interface FetchHandlerResult {
  /** Whether the handler matched the request path. */
  matched: boolean;

  /** Response generated by the handler. */
  response: Response;
}

/** Structural fetch handler used by RPC and OpenAPI service adapters. */
export interface FetchHandler {
  /** Handles a request with path prefix and service context options. */
  handle(
    request: Request,
    options: { prefix: `/${string}`; context?: Record<string, unknown> },
  ): Promise<FetchHandlerResult>;
}

/** Structural oRPC plugin accepted by service handler factories. */
export interface ServiceHandlerPlugin {
  /** Initializes the plugin against the handler runtime. */
  init?(options: unknown): void | Promise<void>;
}

/** Minimal request shape exposed to service middleware and handlers. */
export interface ServiceRequest {
  /** Raw Web Platform request. */
  raw: Request;

  /** Matched request path. */
  path: string;

  /** Reads a request header by name. */
  header(name: string): string | undefined;
}

/** Minimal context shape exposed to service middleware and handlers. */
export interface ServiceContext {
  /** Request wrapper for the current service call. */
  req: ServiceRequest;

  /** Creates a JSON response. */
  json(data: unknown, status?: number): Response;

  /** Creates an HTML response. */
  html(html: string, status?: number): Response;

  /** Creates a raw body response. */
  body(data: BodyInit | null, status?: number, headers?: HeadersInit): Response;

  /** Creates a response from an existing response or init object. */
  newResponse(data?: BodyInit | null, init?: Response | ResponseInit): Response;

  /** Reads request-scoped middleware state. */
  get(key: string): unknown;
}

/** Middleware function accepted by the service builder. */
export interface ServiceMiddleware {
  (context: ServiceContext, next: () => Promise<void>): Promise<Response | void>;
  (context: unknown, next: () => Promise<void>): Promise<Response | void>;
}

/** Service route handler accepted by the builder route API. */
export interface ServiceHandler {
  (context: ServiceContext): Response | Promise<Response>;
  (context: unknown, next: unknown): Response | Promise<Response>;
}

/** Error handler used by service applications. */
export interface ServiceErrorHandler {
  (error: Error, context: ServiceContext): Response | Promise<Response>;
  (error: Error, context: unknown): Response | Promise<Response>;
}

/** CORS options supported by `withCors()`. */
export interface CorsOptions {
  /** Allowed origin value or matcher. */
  origin?:
    | string
    | string[]
    | ((origin: string, context: ServiceContext) => string | undefined);

  /** Allowed HTTP methods. */
  allowMethods?: string[];

  /** Allowed request headers. */
  allowHeaders?: string[];

  /** Exposed response headers. */
  exposeHeaders?: string[];

  /** Preflight cache duration in seconds. */
  maxAge?: number;

  /** Whether credentials are allowed. */
  credentials?: boolean;
}

/** Database client capable of a health-check query. */
export interface Database {
  /** Executes a raw SQL template query. */
  $queryRaw(query: TemplateStringsArray): Promise<unknown>;
}

/** Database context injected into service handler context. */
export type DbContext = Record<string, unknown>;

/** Creates per-request service handler context. */
export type ContextFactory = (
  context: ServiceContext,
) => Record<string, unknown>;
