import type { EmitterPort, RegistryEmission } from './ports/emitter-port.ts';
import type { ExtractedContribution } from './ports/extractor-port.ts';

/** Registry emitter that writes one generated TypeScript module per contribution axis. */
export class RegistryEmitter implements EmitterPort {
  async emit(
    contributions: readonly ExtractedContribution[],
  ): Promise<readonly RegistryEmission[]> {
    const groups = groupByAxis(contributions);
    return [...groups.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([axis, axisContributions]) => ({
        path: `.netscript/generated/${axis}.registry.ts`,
        text: emitAxisRegistry(axis, axisContributions),
      }));
  }
}

function groupByAxis(
  contributions: readonly ExtractedContribution[],
): Map<string, readonly ExtractedContribution[]> {
  const groups = new Map<string, ExtractedContribution[]>();
  for (const contribution of contributions) {
    const axis = normalizeAxis(contribution.axis);
    const values = groups.get(axis) ?? [];
    values.push(contribution);
    groups.set(axis, values);
  }
  return groups;
}

function emitAxisRegistry(
  axis: string,
  contributions: readonly ExtractedContribution[],
): string {
  const imports = contributions.map((contribution, index) => {
    const imported = localName(axis, index);
    const source = normalizeImportPath(contribution.file);
    return contribution.symbol === 'default'
      ? `import ${imported} from '${source}';`
      : `import { ${contribution.symbol} as ${imported} } from '${source}';`;
  });
  const entries = contributions.map((_, index) =>
    `  [String(${localName(axis, index)}.id), ${localName(axis, index)}],`
  );

  return [
    '/**',
    ` * ${toTitle(axis)} Registry - AUTO-GENERATED`,
    ' *',
    ' * DO NOT EDIT - regenerated by `netscript generate plugins`.',
    ' *',
    ' * @module',
    ' */',
    '',
    ...imports,
    '',
    'const entries = [',
    ...entries,
    '] as const;',
    '',
    'export const registry: ReadonlyMap<string, unknown> = new Map<string, unknown>(',
    '  entries.map(([id, value]): readonly [string, unknown] => [id, value]),',
    ');',
    '',
  ].join('\n');
}

function normalizeAxis(axis: string): string {
  return axis.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') ||
    'contributions';
}

function normalizeImportPath(path: string): string {
  const normalized = path.replace(/\\/g, '/');
  return normalized.startsWith('.') ? normalized : `../../${normalized}`;
}

function localName(axis: string, index: number): string {
  return `${axis.replace(/-([a-z0-9])/g, (_, value: string) => value.toUpperCase())}${index}`;
}

function toTitle(axis: string): string {
  return axis.split('-').filter(Boolean).map((part) =>
    `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`
  ).join(' ');
}
