/**
 * Package specifiers for scaffold import maps.
 */
export const SCAFFOLD_PACKAGES = {
  NETSCRIPT_CONFIG: '@netscript/config',
  NETSCRIPT_SERVICE: '@netscript/service',
  NETSCRIPT_PLUGIN: '@netscript/plugin',
  NETSCRIPT_CONTRACTS: '@netscript/contracts',
  NETSCRIPT_SDK: '@netscript/sdk',
  NETSCRIPT_LOGGER: '@netscript/logger',
  NETSCRIPT_LOGGER_MIDDLEWARE: '@netscript/logger/middleware',
  NETSCRIPT_LOGGER_ORPC: '@netscript/logger/orpc',
  NETSCRIPT_TELEMETRY: '@netscript/telemetry',
  NETSCRIPT_DATABASE: '@netscript/database',
  NETSCRIPT_DATABASE_SCRIPTS: '@netscript/database/scripts',
  NETSCRIPT_DATABASE_TRACING: '@netscript/database/tracing',
  NETSCRIPT_PLUGIN_AUTH_CORE: '@netscript/plugin-auth-core',
  NETSCRIPT_PLUGIN_AUTH_CORE_CONFIG: '@netscript/plugin-auth-core/config',
  NETSCRIPT_PLUGIN_AUTH_CORE_CONTRACTS_V1: '@netscript/plugin-auth-core/contracts/v1',
  NETSCRIPT_PLUGIN_AUTH_CORE_DOMAIN: '@netscript/plugin-auth-core/domain',
  NETSCRIPT_PLUGIN_AUTH_CORE_PORTS: '@netscript/plugin-auth-core/ports',
  NETSCRIPT_PLUGIN_AUTH_CORE_STREAMS: '@netscript/plugin-auth-core/streams',
  NETSCRIPT_PLUGIN_AUTH_CORE_TESTING: '@netscript/plugin-auth-core/testing',
  NETSCRIPT_AUTH_WORKOS: '@netscript/auth-workos',
  NETSCRIPT_AUTH_BETTER_AUTH: '@netscript/auth-better-auth',
  NETSCRIPT_AUTH_KV_OAUTH: '@netscript/auth-kv-oauth',
  NETSCRIPT_PLUGIN_WORKERS_RUNTIME: '@netscript/plugin-workers/runtime',
  NETSCRIPT_WORKERS: '@netscript/plugin-workers-core',
  NETSCRIPT_WORKERS_RUNTIME: '@netscript/plugin-workers-core/runtime',
  NETSCRIPT_WORKERS_SCHEMAS: '@netscript/plugin-workers-core/schemas',
  NETSCRIPT_PLUGIN_SAGAS_RUNTIME: '@netscript/plugin-sagas/runtime',
  NETSCRIPT_PLUGIN_SAGAS_CORE: '@netscript/plugin-sagas-core',
  NETSCRIPT_PLUGIN_SAGAS_CORE_DOMAIN: '@netscript/plugin-sagas-core/domain',
  NETSCRIPT_PLUGIN_TRIGGERS_RUNTIME: '@netscript/plugin-triggers/runtime',
  NETSCRIPT_PLUGIN_TRIGGERS_CORE: '@netscript/plugin-triggers-core',
  NETSCRIPT_PLUGIN_TRIGGERS_CORE_ADAPTERS: '@netscript/plugin-triggers-core/adapters',
  NETSCRIPT_PLUGIN_TRIGGERS_CORE_BUILDERS: '@netscript/plugin-triggers-core/builders',
  NETSCRIPT_PLUGIN_TRIGGERS_CORE_CONFIG: '@netscript/plugin-triggers-core/config',
  NETSCRIPT_PLUGIN_TRIGGERS_CORE_CONTRACTS_V1: '@netscript/plugin-triggers-core/contracts/v1',
  NETSCRIPT_PLUGIN_TRIGGERS_CORE_DOMAIN: '@netscript/plugin-triggers-core/domain',
  NETSCRIPT_PLUGIN_TRIGGERS_CORE_PORTS: '@netscript/plugin-triggers-core/ports',
  NETSCRIPT_PLUGIN_TRIGGERS_CORE_RUNTIME: '@netscript/plugin-triggers-core/runtime',
  NETSCRIPT_PRISMA_ADAPTER_MYSQL: '@netscript/prisma-adapter-mysql',
  NETSCRIPT_SDK_CLIENT: '@netscript/sdk/client',
  NETSCRIPT_SDK_QUERY: '@netscript/sdk/query',
  NETSCRIPT_SDK_QUERY_CLIENT: '@netscript/sdk/query-client',
  STD_PATH: '@std/path',
  STD_FS: '@std/fs',
  STD_ASSERT: '@std/assert',
  NETSCRIPT_ASPIRE: '@netscript/aspire',
  NETSCRIPT_FRESH: '@netscript/fresh',
  NETSCRIPT_FRESH_BUILDERS: '@netscript/fresh/builders',
  NETSCRIPT_FRESH_QUERY: '@netscript/fresh/query',
  NETSCRIPT_FRESH_ROUTE: '@netscript/fresh/route',
  NETSCRIPT_FRESH_SERVER: '@netscript/fresh/server',
  NETSCRIPT_FRESH_VITE: '@netscript/fresh/vite',
  NETSCRIPT_KV: '@netscript/kv',
  NETSCRIPT_FRESH_UI: '@netscript/fresh-ui',
  NETSCRIPT_FRESH_UI_INTERACTIVE: '@netscript/fresh-ui/interactive',
  ZOD: 'zod',
} as const;

export type ScaffoldPackageKey = keyof typeof SCAFFOLD_PACKAGES;
