// This file is seeded by netscript init and regenerated by @netscript/fresh/vite.

export const routePatterns = {
  $route: '/',
  dashboard: {
    $route: '/dashboard',
  },
  health: {
    $route: '/health',
  },
  examples: {
    $route: '/examples',
    crud: {
      $route: '/examples/crud',
    },
    telemetry: {
      $route: '/examples/telemetry',
    },
  },
  design: {
    $route: '/design',
    tokens: {
      $route: '/design/tokens',
    },
    components: {
      $route: '/design/components',
    },
    composition: {
      $route: '/design/composition',
    },
  },
} as const;
