// This file is seeded by netscript init and regenerated by @netscript/fresh/vite.

import { createRouteReference } from '@netscript/fresh/route';
import { routePatterns } from './manifest.ts';

export const routes = {
  $route: createRouteReference(routePatterns.$route, {
    id: 'home',
    kind: 'page',
  }),
  dashboard: {
    $route: createRouteReference(routePatterns.dashboard.$route, {
      id: 'dashboard',
      kind: 'page',
    }),
  },
  health: {
    $route: createRouteReference(routePatterns.health.$route, {
      id: 'health',
      kind: 'page',
    }),
  },
  examples: {
    $route: createRouteReference(routePatterns.examples.$route, {
      id: 'examples',
      kind: 'page',
    }),
    crud: createRouteReference(routePatterns.examples.crud.$route, {
      id: 'examples.crud',
      kind: 'page',
    }),
    telemetry: createRouteReference(routePatterns.examples.telemetry.$route, {
      id: 'examples.telemetry',
      kind: 'page',
    }),
  },
  design: {
    $route: createRouteReference(routePatterns.design.$route, {
      id: 'design',
      kind: 'page',
    }),
    tokens: createRouteReference(routePatterns.design.tokens.$route, {
      id: 'design.tokens',
      kind: 'page',
    }),
    components: createRouteReference(routePatterns.design.components.$route, {
      id: 'design.components',
      kind: 'page',
    }),
    composition: createRouteReference(routePatterns.design.composition.$route, {
      id: 'design.composition',
      kind: 'page',
    }),
  },
} as const;
