export {
  generatePluginContracts,
  generatePluginDbSchema,
  generatePluginDenoJson,
  generatePluginMod,
  generatePluginProcessorEntrypoint,
  generatePluginRouter,
  generatePluginSampleFiles,
  generatePluginService,
  generatePluginServiceContext,
  type PluginCodeOptions,
  type PluginDbSchemaOptions,
  type PluginManifestOptions,
  type PluginSampleFile,
  type PluginSampleOptions,
} from '../../../kernel/templates/plugins/plugin-generators.ts';
