/** AI MCP server scaffolding and registry emission. */

import { type ScaffoldArtifact, textArtifact } from '@netscript/plugin/adapter';

/** Supported generated MCP server configuration. */
export interface McpServerInput {
  readonly id: string;
  readonly transport: 'streamable-http' | 'stdio';
  readonly target: string;
  readonly authEnv?: string;
}

/** Emit one app-owned MCP server transport configuration. */
export function emitMcpServer(input: McpServerInput): ScaffoldArtifact {
  const auth = input.authEnv
    ? `,\n  auth: { mode: 'api-token', token: Deno.env.get(${
      JSON.stringify(input.authEnv)
    }) ?? '' }`
    : '';
  const endpoint = input.transport === 'stdio'
    ? `kind: 'stdio',\n  command: ${JSON.stringify(input.target)}`
    : `kind: 'streamable-http',\n  url: ${JSON.stringify(input.target)}${auth}`;
  return textArtifact(
    `ai/mcp/${input.id}.ts`,
    `/** MCP server ${JSON.stringify(input.id)}. Generated by plugin ai mcp add. */\n` +
      `import type { McpTransportConfig } from '@netscript/ai/mcp';\n\n` +
      `export const config: McpTransportConfig = {\n  ${endpoint},\n` +
      `  serverId: ${JSON.stringify(input.id)},\n};\n`,
  );
}

/** Emit the MCP registry consumed by the app AI composition root. */
export function emitMcpRegistry(ids: readonly string[]): ScaffoldArtifact {
  const imports = ids.map((id, index) => `import { config as server${index} } from './${id}.ts';`);
  const servers = ids.map((_id, index) => `server${index}`).join(', ');
  return textArtifact(
    'ai/mcp/registry.ts',
    `/** MCP registry. Generated by the AI plugin CLI. */\n` +
      `import { createMcpTransportPool, registerMcpTools } from '@netscript/ai/mcp';\n` +
      `import type { AiToolRegistry } from '@netscript/ai/tools';\n` +
      `${imports.join('\n')}\n\n` +
      `export const MCP_SERVER_IDS = ${JSON.stringify(ids)} as const;\n` +
      `const pool = createMcpTransportPool({ servers: [${servers}] });\n\n` +
      `/** Connect configured MCP servers and surface their tools in the AI registry. */\n` +
      `export async function initializeMcpTools(tools: AiToolRegistry): Promise<void> {\n` +
      `  if (MCP_SERVER_IDS.length === 0) return;\n` +
      `  await registerMcpTools(tools, pool);\n` +
      `}\n`,
  );
}
