import { assertEquals } from 'jsr:@std/assert@^1';
import type { ProjectFileEntry, ProjectFiles } from '@netscript/plugin/cli';
import { compileTriggerRegistry } from '../../src/cli/trigger-registry-compiler.ts';

/**
 * Golden byte-identity test for the triggers runtime registry compiler.
 *
 * Locks the exact emitted module so the thin-wrapper refactor over the shared
 * `@netscript/plugin/cli` registry emitter cannot drift a single byte.
 */
Deno.test('compileTriggerRegistry emits the golden trigger registry module', async () => {
  const files = new MemoryProjectFiles([
    'triggers/generic-webhook.ts',
    'triggers/file-watcher-diagnostics.ts',
    'triggers/_registry.ts',
    'triggers/mod.ts',
    'triggers/csv-import-trigger.ts',
    'triggers/nested/ignored.ts',
  ]);

  const result = await compileTriggerRegistry(files);

  assertEquals(result.registryPath, '.netscript/generated/plugin-triggers/triggers.registry.ts');
  assertEquals(result.triggerCount, 2);
  assertEquals(result.files, [
    'triggers/file-watcher-diagnostics.ts',
    'triggers/generic-webhook.ts',
  ]);

  const written = files.written.get('.netscript/generated/plugin-triggers/triggers.registry.ts');
  assertEquals(written, EXPECTED_TRIGGER_REGISTRY);
});

const EXPECTED_TRIGGER_REGISTRY = `/**
 * Trigger Registry - AUTO-GENERATED
 *
 * DO NOT EDIT - regenerated by the triggers plugin CLI.
 *
 * @module
 */

import type { TriggerDefinition } from '@netscript/plugin-triggers-core/domain';
import * as trigger0 from "../../../triggers/file-watcher-diagnostics.ts";
import * as trigger1 from "../../../triggers/generic-webhook.ts";

const definitions: readonly TriggerDefinition[] = [
  ...resolveTriggerDefinitions(trigger0, "triggers/file-watcher-diagnostics.ts"),
  ...resolveTriggerDefinitions(trigger1, "triggers/generic-webhook.ts"),
];

export const registry: ReadonlyMap<string, TriggerDefinition> = new Map<string, TriggerDefinition>(
  definitions.map((definition): readonly [string, TriggerDefinition] => [String(definition.id), definition]),
);

function resolveTriggerDefinitions(
  module: Record<string, unknown>,
  path: string,
): readonly TriggerDefinition[] {
  const candidates = [module.default, module.trigger, module.definition, ...Object.values(module)];
  const definitions = candidates.flatMap((candidate) =>
    Array.isArray(candidate) ? candidate : [candidate]
  ).filter(isTriggerDefinition);

  if (definitions.length === 0) {
    throw new Error(\`Trigger module \${path} does not export a TriggerDefinition.\`);
  }
  return definitions;
}

function isTriggerDefinition(candidate: unknown): candidate is TriggerDefinition {
  if (typeof candidate !== 'object' || candidate === null) {
    return false;
  }
  const value = candidate as Record<string, unknown>;
  return typeof value.id === 'string' &&
    typeof value.kind === 'string' &&
    typeof value.handler === 'function';
}
`;

/** In-memory {@linkcode ProjectFiles} fixture for deterministic golden tests. */
class MemoryProjectFiles implements ProjectFiles {
  readonly projectRoot = '/project';
  readonly written = new Map<string, string>();
  readonly #contents: Map<string, string>;

  constructor(paths: readonly string[]) {
    this.#contents = new Map(paths.map((path) => [path, 'export default {};']));
  }

  resolve(path: string): string {
    return `${this.projectRoot}/${path}`;
  }

  // deno-lint-ignore require-await
  async writeTextFile(path: string, content: string): Promise<void> {
    this.written.set(path, content);
  }

  // deno-lint-ignore require-await
  async readTextFile(path: string): Promise<string | undefined> {
    return this.#contents.get(path);
  }

  // deno-lint-ignore require-await
  async listFiles(path: string, extensions: readonly string[] = []): Promise<
    readonly ProjectFileEntry[]
  > {
    const prefix = `${path}/`;
    const entries: ProjectFileEntry[] = [];
    for (const [relativePath, content] of this.#contents) {
      if (!relativePath.startsWith(prefix)) continue;
      if (extensions.length && !extensions.some((ext) => relativePath.endsWith(ext))) continue;
      entries.push(
        Object.freeze({ path: this.resolve(relativePath), relativePath, size: content.length }),
      );
    }
    return Object.freeze(
      entries.sort((left, right) => left.relativePath.localeCompare(right.relativePath)),
    );
  }

  toImportUrl(path: string): string {
    return `file://${this.resolve(path)}`;
  }

  relative(path: string): string {
    return path.startsWith(`${this.projectRoot}/`) ? path.slice(this.projectRoot.length + 1) : path;
  }
}
