import { assertEquals } from 'jsr:@std/assert@^1';
import type { ProjectFileEntry, ProjectFiles } from '@netscript/plugin/cli';
import { generateSagaRegistry } from '../../src/cli/registry-generator.ts';

/**
 * Golden byte-identity test for the sagas static registry generator.
 *
 * Locks the exact emitted module so the thin-wrapper refactor over the shared
 * `@netscript/plugin/cli` registry emitter cannot drift a single byte.
 */
Deno.test('generateSagaRegistry emits the golden saga registry module', async () => {
  const files = new MemoryProjectFiles(
    new Map([
      ['sagas/user-registration-saga.ts', "export default defineSaga('user-registration');"],
      ['sagas/payment-saga.ts', "export const saga = defineSaga('payment');"],
      ['sagas/not-a-saga.ts', 'export const value = 1;'],
    ]),
  );

  const result = await generateSagaRegistry(files);

  assertEquals(result.registryPath, '.netscript/generated/plugin-sagas/sagas.registry.ts');
  assertEquals(result.sagas, [
    'sagas/payment-saga.ts',
    'sagas/user-registration-saga.ts',
  ]);

  const written = files.written.get('.netscript/generated/plugin-sagas/sagas.registry.ts');
  assertEquals(written, EXPECTED_SAGA_REGISTRY);
});

const EXPECTED_SAGA_REGISTRY = `/**
 * Saga Registry - AUTO-GENERATED
 *
 * DO NOT EDIT - regenerated by the sagas plugin CLI.
 *
 * @module
 */

import type { SagaDefinition } from '@netscript/plugin-sagas-core/domain';
import * as saga0 from '../../../sagas/payment-saga.ts';
import * as saga1 from '../../../sagas/user-registration-saga.ts';

const entries: readonly [string, SagaDefinition][] = [
  [
    resolveSagaDefinition(saga0, 'sagas/payment-saga.ts').id,
    resolveSagaDefinition(saga0, 'sagas/payment-saga.ts'),
  ],
  [
    resolveSagaDefinition(saga1, 'sagas/user-registration-saga.ts').id,
    resolveSagaDefinition(saga1, 'sagas/user-registration-saga.ts'),
  ],
];

export const sagaRegistry: ReadonlyMap<string, SagaDefinition> = new Map(entries);
export const registry: ReadonlyMap<string, SagaDefinition> = sagaRegistry;

function resolveSagaDefinition(module: Record<string, unknown>, path: string): SagaDefinition {
  const candidate = module.default ?? module.saga ?? module.definition;
  if (!isSagaDefinition(candidate)) {
    throw new Error(\`Saga module \${path} does not export a SagaDefinition.\`);
  }
  return candidate;
}

function isSagaDefinition(candidate: unknown): candidate is SagaDefinition {
  if (typeof candidate !== 'object' || candidate === null) {
    return false;
  }
  const value = candidate as Record<string, unknown>;
  return typeof value.id === 'string' &&
    typeof value.durability === 'string' &&
    typeof value.initialState === 'object' &&
    value.initialState !== null &&
    Array.isArray(value.handledMessageTypes) &&
    value.handlers instanceof Map;
}
`;

/** In-memory {@linkcode ProjectFiles} fixture for deterministic golden tests. */
class MemoryProjectFiles implements ProjectFiles {
  readonly projectRoot = '/project';
  readonly written = new Map<string, string>();
  readonly #contents: Map<string, string>;

  constructor(contents: Map<string, string>) {
    this.#contents = contents;
  }

  resolve(path: string): string {
    return `${this.projectRoot}/${path}`;
  }

  // deno-lint-ignore require-await
  async writeTextFile(path: string, content: string): Promise<void> {
    this.written.set(path, content);
  }

  // deno-lint-ignore require-await
  async readTextFile(path: string): Promise<string | undefined> {
    return this.#contents.get(path);
  }

  // deno-lint-ignore require-await
  async listFiles(path: string, extensions: readonly string[] = []): Promise<
    readonly ProjectFileEntry[]
  > {
    const prefix = `${path}/`;
    const entries: ProjectFileEntry[] = [];
    for (const [relativePath, content] of this.#contents) {
      if (!relativePath.startsWith(prefix)) continue;
      if (extensions.length && !extensions.some((ext) => relativePath.endsWith(ext))) continue;
      entries.push(
        Object.freeze({ path: this.resolve(relativePath), relativePath, size: content.length }),
      );
    }
    return Object.freeze(
      entries.sort((left, right) => left.relativePath.localeCompare(right.relativePath)),
    );
  }

  toImportUrl(path: string): string {
    return `file://${this.resolve(path)}`;
  }

  relative(path: string): string {
    return path.startsWith(`${this.projectRoot}/`) ? path.slice(this.projectRoot.length + 1) : path;
  }
}
