/** Type-checked source stub for the generated sagas runtime glue.
 *
 * @module
 */

import { defineStub, type StubSource } from '@netscript/plugin/adapter';

/** Sagas background runtime glue stub. */
export const runtimeGlueStub: StubSource<never> = defineStub({
  source: [
    '/** Runtime glue emitted into generated projects for the sagas background process.',
    ' *',
    ' * @module',
    ' */',
    '',
    "import '@netscript/kv/redis';",
    "import { startSagaRunner } from '@netscript/plugin-sagas/runtime';",
    '',
    'if (import.meta.main) {',
    '  const supervisor = await startSagaRunner({',
    "    registryModule: projectFileUrl('.netscript/generated/plugin-sagas/sagas.registry.ts').href,",
    '  });',
    "  const port = parsePort(Deno.env.get('PORT'));",
    '  const server = Deno.serve({ port }, (request) => {',
    "    if (new URL(request.url).pathname !== '/health') {",
    "      return new Response('Not Found', { status: 404 });",
    '    }',
    '    const snapshot = supervisor.snapshot();',
    "    return Response.json(snapshot, { status: snapshot.status === 'running' ? 200 : 503 });",
    '  });',
    '  const signal = await waitForShutdownSignal();',
    '  await supervisor.stop(`signal:${signal}`);',
    '  await server.shutdown();',
    '}',
    '',
    'function parsePort(value: string | undefined): number {',
    "  const port = Number(value ?? '0');",
    '  if (!Number.isSafeInteger(port) || port < 0 || port > 65_535) {',
    '    throw new Error(`Invalid saga health port: ${value}`);',
    '  }',
    '  return port;',
    '}',
    '',
    'function waitForShutdownSignal(): Promise<Deno.Signal> {',
    "  const signals: readonly Deno.Signal[] = Deno.build.os === 'windows'",
    "    ? ['SIGINT', 'SIGBREAK']",
    "    : ['SIGINT', 'SIGTERM'];",
    '  return new Promise((resolve) => {',
    '    const listeners = new Map<Deno.Signal, () => void>();',
    '    const cleanup = () => {',
    '      for (const [signal, listener] of listeners) {',
    '        Deno.removeSignalListener(signal, listener);',
    '      }',
    '    };',
    '    for (const signal of signals) {',
    '      const listener = () => {',
    '        cleanup();',
    '        resolve(signal);',
    '      };',
    '      listeners.set(signal, listener);',
    '      Deno.addSignalListener(signal, listener);',
    '    }',
    '  });',
    '}',
    '',
    'function projectFileUrl(relativePath: string): URL {',
    "  const root = Deno.cwd().replaceAll('\\\\', '/');",
    "  const normalizedRoot = root.endsWith('/') ? root : `${root}/`;",
    "  const base = normalizedRoot.startsWith('/')",
    '    ? `file://${normalizedRoot}`',
    '    : `file:///${normalizedRoot}`;',
    '  return new URL(relativePath, base);',
    '}',
    '',
  ].join('\n'),
  tokens: [],
});
