import { exists } from 'jsr:@std/fs@^1';
import { dirname, join, relative } from 'jsr:@std/path@^1';

export const OFFICIAL_SAMPLE_CONFIG_MARKER =
  '// <auto-generated by netscript official plugin copier>';

interface CopiedOfficialState {
  readonly hasWorkers: boolean;
  readonly hasSagas: boolean;
  readonly hasTriggers: boolean;
}

export async function writeOfficialSampleConfiguration(options: {
  readonly projectRoot: string;
  readonly force: boolean;
}): Promise<readonly string[]> {
  const created: string[] = [];
  const state = await discoverCopiedOfficialState(options.projectRoot);
  const configPath = join(options.projectRoot, 'config', 'official-plugins', 'mod.ts');

  if (
    await writeOwnedGeneratedFile(
      configPath,
      generateOfficialSamplesConfig(state),
      options.force,
    )
  ) {
    created.push(configPath);
  }

  created.push(...await writeOfficialSampleWorkerJobs(options.projectRoot, state, options.force));
  created.push(...await writeOfficialRuntimeConfig(options.projectRoot, state, options.force));
  return created.map((path) => relative(options.projectRoot, path).replaceAll('\\', '/'));
}

async function discoverCopiedOfficialState(projectRoot: string): Promise<CopiedOfficialState> {
  const hasWorkers = await exists(join(projectRoot, 'workers'), { isDirectory: true });
  const hasSagas = await exists(join(projectRoot, 'sagas'), { isDirectory: true });
  const hasTriggers = await exists(join(projectRoot, 'triggers'), { isDirectory: true });
  return { hasWorkers, hasSagas, hasTriggers };
}

async function writeOfficialSampleWorkerJobs(
  projectRoot: string,
  state: CopiedOfficialState,
  force: boolean,
): Promise<readonly string[]> {
  if (!state.hasWorkers || !state.hasSagas) {
    return [];
  }

  const targetPath = join(
    projectRoot,
    'plugins',
    'workers',
    'jobs',
    'create-user-settings.ts',
  );
  if (
    await writeOwnedGeneratedFile(
      targetPath,
      generateCreateUserSettingsJob(),
      force,
    )
  ) {
    return [targetPath];
  }

  return [];
}

async function writeOfficialRuntimeConfig(
  projectRoot: string,
  state: CopiedOfficialState,
  force: boolean,
): Promise<readonly string[]> {
  const written: string[] = [];
  if (state.hasWorkers) {
    written.push(
      ...await writeRuntimeTopic(projectRoot, 'workers', 'tasks', {
        tasks: [
          {
            id: 'validate-data',
            name: 'Data Validation',
            description: 'Validates webhook payloads in scaffold smoke tests',
            runtime: 'deno',
            entrypoint: './tasks/validate-data.ts',
            enabled: true,
            timeout: 30_000,
          },
          {
            id: 'system-diagnostics',
            name: 'System Diagnostics',
            description: 'Runs a local diagnostics task for file trigger validation',
            runtime: 'powershell',
            entrypoint: './tasks/system-diagnostics.ps1',
            enabled: true,
            timeout: 30_000,
          },
        ],
      }, force),
    );
  }

  if (state.hasSagas) {
    written.push(
      ...await writeRuntimeTopic(projectRoot, 'sagas', 'sagas', {
        overrides: [
          {
            id: 'UserRegistrationSaga',
            enabled: true,
            concurrency: 5,
            timeout: 60_000,
          },
        ],
      }, force),
    );
  }

  if (state.hasTriggers) {
    written.push(
      ...await writeRuntimeTopic(projectRoot, 'triggers', 'triggers', {
        overrides: [
          { id: 'generic-inbound-webhook', enabled: true },
          { id: 'webhook-validate-data', enabled: true },
          {
            id: 'file-watcher-diagnostics',
            enabled: true,
            paths: ['.data/incoming/diagnostics'],
          },
          { id: 'product-import-trigger', enabled: false },
          { id: 'export-notify-webhook', enabled: false },
          { id: 'payment-status-webhook', enabled: false },
        ],
      }, force),
    );
  }

  return written;
}

async function writeRuntimeTopic(
  projectRoot: string,
  workspace: 'workers' | 'sagas' | 'triggers',
  topic: 'tasks' | 'sagas' | 'triggers',
  value: Record<string, unknown>,
  force: boolean,
): Promise<readonly string[]> {
  const runtimeRoot = join(projectRoot, workspace, 'runtime');
  const currentPath = join(runtimeRoot, 'current');
  const topicPath = join(runtimeRoot, topic, 'v1.0.0.json');
  const pointer = {
    generatedBy: OFFICIAL_SAMPLE_CONFIG_MARKER,
    version: '1.0.0',
    [topic]: `${topic}/v1.0.0.json`,
  };
  const written: string[] = [];

  if (await writeOwnedGeneratedFile(currentPath, JSON.stringify(pointer, null, 2) + '\n', force)) {
    written.push(currentPath);
  }
  if (
    await writeOwnedGeneratedFile(
      topicPath,
      JSON.stringify(
        {
          $schema: '../schema.json',
          generatedBy: OFFICIAL_SAMPLE_CONFIG_MARKER,
          version: '1.0.0',
          ...value,
        },
        null,
        2,
      ) + '\n',
      force,
    )
  ) {
    written.push(topicPath);
  }

  return written;
}

async function writeOwnedGeneratedFile(
  path: string,
  content: string,
  force: boolean,
): Promise<boolean> {
  await Deno.mkdir(dirname(path), { recursive: true });

  if (await exists(path) && !force) {
    const current = await Deno.readTextFile(path);
    if (!current.includes(OFFICIAL_SAMPLE_CONFIG_MARKER)) {
      return false;
    }
  }

  await Deno.writeTextFile(path, content);
  return true;
}

function generateOfficialSamplesConfig(state: CopiedOfficialState): string {
  return `${OFFICIAL_SAMPLE_CONFIG_MARKER}
import { defineSagas } from '@netscript/config';
import { defineTriggers } from '@netscript/plugin-triggers-core/config';
import { defineWorkers } from '@netscript/plugin-workers-core/config';
import type { RuntimeConfigSection } from '@netscript/config';

export const workers = defineWorkers({
  jobsDir: './workers/jobs',
  tasksDir: './workers/tasks',
  queueProvider: 'auto',
  queueName: 'jobs',
  concurrency: 2,
  enabled: ${state.hasWorkers},
  groups: [
${workerGroups(state).join(',\n')}
  ],
});

export const sagas = defineSagas({
  sagasDir: './sagas',
  transportProvider: 'auto',
  storeProvider: 'postgres',
  enabled: ${state.hasSagas},
  concurrency: 5,
  groups: ${state.hasSagas ? sagaGroups() : '[]'},
});

export const triggers = defineTriggers({
  triggersDir: './triggers',
  enabled: ${state.hasTriggers},
  groups: ${state.hasTriggers ? triggerGroups() : '[]'},
  webhooks: {
    enabled: ${state.hasTriggers},
    basePath: '/api/v1/webhooks',
    rateLimitPerMinute: 60,
  },
});

export const runtimeConfig: RuntimeConfigSection = {
  paths: {
    workers: {
      schemaPath: './workers/runtime/schema.json',
      configDir: './workers/runtime',
    },
    sagas: {
      schemaPath: './sagas/runtime/schema.json',
      configDir: './sagas/runtime',
    },
    triggers: {
      schemaPath: './triggers/runtime/schema.json',
      configDir: './triggers/runtime',
    },
  },
};
`;
}

function workerGroups(state: CopiedOfficialState): readonly string[] {
  return [
    ...(state.hasTriggers ? [webhookWorkerGroup()] : []),
    ...(state.hasSagas ? [sagaWorkerGroup()] : []),
  ];
}

function webhookWorkerGroup(): string {
  return `    {
      topic: 'webhooks',
      scaling: { mode: 'combined', concurrency: 10 },
      retention: { kvDays: 7, dbDays: 90 },
      jobs: [
        {
          id: 'process-webhook-payload',
          name: 'Process Webhook Payload',
          description: 'Generic webhook payload processor for scaffold smoke tests',
          entrypoint: './process-webhook-payload.ts',
          timeout: 30_000,
          tags: ['webhook', 'generic', 'dev'],
        },
      ],
    }`;
}

function sagaWorkerGroup(): string {
  return `    {
      topic: 'sagas',
      scaling: { mode: 'combined', concurrency: 10 },
      retention: { kvDays: 7, dbDays: 30 },
      jobs: [
        {
          id: 'send-welcome-email',
          name: 'Send Welcome Email',
          description: 'Sends welcome email for the UserRegistrationSaga sample',
          entrypoint: './send-welcome-email.ts',
          timeout: 60_000,
          maxRetries: 3,
          tags: ['user', 'email', 'saga', 'onboarding'],
        },
        {
          id: 'create-user-settings',
          name: 'Create User Settings',
          description: 'Completes the UserRegistrationSaga sample onboarding flow',
          entrypoint: '../../plugins/workers/jobs/create-user-settings.ts',
          timeout: 30_000,
          maxRetries: 2,
          tags: ['user', 'settings', 'saga', 'onboarding'],
        },
      ],
    }`;
}

function sagaGroups(): string {
  return `[
    {
      topic: 'users',
      scaling: { mode: 'combined', concurrency: 5 },
      retention: { activeDays: 7, completedDays: 3, archiveToDb: true },
      sagas: [
        {
          id: 'UserRegistrationSaga',
          name: 'User Registration Saga',
          description: 'Welcome email and onboarding workflow sample',
          entrypoint: './user-registration-saga.ts',
          enabled: true,
          tags: ['user', 'onboarding', 'sample'],
        },
      ],
    },
  ]`;
}

function triggerGroups(): string {
  return `[
    {
      topic: 'webhooks',
      scaling: { concurrency: 10 },
      retention: { kvDays: 7, dbDays: 90 },
      triggers: [
        {
          id: 'generic-inbound-webhook',
          name: 'Generic Inbound Webhook',
          kind: 'webhook',
          enabled: true,
          entrypoint: './generic-webhook.ts',
          tags: ['webhook', 'generic', 'dev'],
        },
        {
          id: 'webhook-validate-data',
          name: 'Webhook Validate Data',
          kind: 'webhook',
          enabled: true,
          entrypoint: './webhook-validate-data.ts',
          tags: ['webhook', 'runtime-task', 'validate-data'],
        },
      ],
    },
    {
      topic: 'runtime-tasks',
      scaling: { concurrency: 2 },
      retention: { kvDays: 7, dbDays: 90 },
      triggers: [
        {
          id: 'file-watcher-diagnostics',
          name: 'File Watcher Diagnostics',
          kind: 'file-watch',
          enabled: true,
          entrypoint: './file-watcher-diagnostics.ts',
          tags: ['file-watcher', 'runtime-task', 'system-diagnostics'],
        },
      ],
    },
  ]`;
}

function generateCreateUserSettingsJob(): string {
  return `${OFFICIAL_SAMPLE_CONFIG_MARKER}
import { createSagaPublisher } from '@netscript/plugin-sagas/runtime';
import { createSuccessResult, defineJobHandler } from '@netscript/plugin-workers-core';
import { z } from 'zod';
import type { UserRegistrationMessage } from '../../../workers/saga-message-types.ts';

const CreateUserSettingsPayloadSchema = z.object({
  userId: z.string().min(1, 'userId is required'),
});

const sagaPublisher = createSagaPublisher<UserRegistrationMessage>();

const handler = defineJobHandler(async (ctx) => {
  const { userId } = CreateUserSettingsPayloadSchema.parse(ctx.payload ?? {});
  console.info('Creating scaffold sample settings', { userId });

  await sagaPublisher.publish({
    type: 'UserSettingsCreated',
    payload: { userId },
  });

  return createSuccessResult({
    userId,
    settingsCreated: true,
    source: 'scaffold-sample',
  });
});

export default Object.assign(handler, { id: 'create-user-settings' });
`;
}
