// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run `deno task gen:assets-barrel`.

export { EMBEDDED_AGENT_DOCS_PAGES } from './agent-docs-prose.generated.ts';

/** Release identity; entry integrity and aggregate counts are derived from page rows. */
export const EMBEDDED_AGENT_DOCS_PROVENANCE = { schemaVersion: 1, version: '0.0.7' } as const;

/** Same-release package export subpaths used for exact installed-version API generation. */
// deno-fmt-ignore
export const EMBEDDED_AGENT_DOCS_PACKAGE_EXPORTS: Readonly<Record<string, readonly string[]>> = {
  "@netscript/ai": [".","./agent","./anthropic","./contracts","./mcp","./ollama","./openai-compatible","./openai-embeddings","./openrouter","./ports","./skills","./testing","./tools"],

  "@netscript/aspire": [".","./adapters","./application","./config","./constants","./public","./schema","./testing","./types"],

  "@netscript/auth-better-auth": ["."],

  "@netscript/auth-kv-oauth": [".","./backend","./cookies","./crypto","./errors","./flow","./providers","./store","./subject"],

  "@netscript/auth-workos": ["."],

  "@netscript/cli": [".","./scaffolding","./testing"],

  "@netscript/config": [".","./merge","./paths","./schema/plugins"],

  "@netscript/contracts": [".","./commands","./crud","./query","./transform"],

  "@netscript/cron": [".","./adapters","./ports","./testing"],

  "@netscript/database": [".","./adapters","./adapters/mssql","./adapters/mysql","./adapters/postgres","./commands","./commands/postgres","./connection-strings/postgres","./extensions","./ports","./scripts","./testing","./tracing"],

  "@netscript/fresh": [".","./ai","./ai/sandbox","./builders","./defer","./defer/island","./desktop","./error","./form","./interactive","./navigation","./query","./route","./server","./streams","./testing","./vite"],

  "@netscript/fresh-ui": [".","./ai/render-ui","./desktop","./interactive","./primitives","./registry"],

  "@netscript/kv": [".","./kvdex","./redis","./testing"],

  "@netscript/logger": [".","./middleware","./orpc"],

  "@netscript/mcp": [".","./cli","./openapi-projection"],

  "@netscript/plugin": [".","./abstracts","./adapter","./cli","./config","./contract-base","./loader","./protocol","./scaffold","./sdk","./service","./templates","./testing"],

  "@netscript/plugin-ai": [".","./adapter","./adapter-cli","./contracts","./plugin","./public","./scaffold"],

  "@netscript/plugin-ai-core": [".","./contracts/v1"],

  "@netscript/plugin-auth": [".","./adapter-cli","./authenticator","./contracts","./plugin","./public","./scaffold","./services","./streams","./streams/server"],

  "@netscript/plugin-auth-core": [".","./authenticator","./config","./contracts/v1","./domain","./ports","./presets","./sdk","./streams","./telemetry","./testing"],

  "@netscript/plugin-sagas": [".","./adapter-cli","./aspire","./cli","./contracts","./doctor","./e2e","./plugin","./public","./runtime","./scaffold","./services","./streams","./streams/server"],

  "@netscript/plugin-sagas-core": [".","./abstracts","./adapters","./agent","./builders","./config","./contracts/v1","./domain","./integration/commands","./integration/publisher","./integration/workers","./middleware","./ports","./presets","./runtime","./stores","./streams","./telemetry","./testing","./transports"],

  "@netscript/plugin-streams": [".","./adapter-cli","./aspire","./cli","./e2e","./scaffold","./services"],

  "@netscript/plugin-streams-core": [".","./admin","./integration/commands","./sse","./telemetry","./testing"],

  "@netscript/plugin-triggers": [".","./adapter-cli","./aspire","./cli","./plugin","./public","./runtime","./scaffold","./services","./streams","./streams/server"],

  "@netscript/plugin-triggers-core": [".","./adapters","./builders","./config","./contracts/v1","./domain","./ports","./public","./runtime","./stores","./telemetry","./testing"],

  "@netscript/plugin-workers": [".","./adapter-cli","./aspire","./cli","./contracts","./doctor","./jobs/health-check.ts","./runtime","./scaffold","./services","./streams","./streams/server","./worker"],

  "@netscript/plugin-workers-core": [".","./abstracts","./builders","./config","./contracts/v1","./executor","./integration/commands","./presets","./registry","./runtime","./schemas","./shutdown","./state","./stores","./streams","./telemetry","./testing","./workflow"],

  "@netscript/prisma-adapter-mysql": ["."],

  "@netscript/queue": [".","./adapters/amqp","./adapters/deno-kv","./adapters/kv-dead-letter-store","./adapters/kv-polling","./adapters/postgres","./adapters/postgres-dead-letter-store","./adapters/redis","./adapters/redis-dead-letter-store","./errors","./ports","./testing","./validation"],

  "@netscript/runtime-config": ["."],

  "@netscript/sdk": [".","./auto-update","./cache","./client","./collections","./desktop","./discovery","./ports","./presets","./query","./query-client","./streams","./streams/consumer","./telemetry"],

  "@netscript/service": [".","./auth","./commands","./commands/relay","./commands/testing","./internal-credential","./rpc-path"],

  "@netscript/telemetry": [".","./ai","./attributes","./commands","./config","./context","./hono","./instrumentation","./orpc","./otel","./query","./registry","./testing","./tracer"],

  "@netscript/watchers": ["."],
};
