// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run `deno task gen:assets-barrel`.

import type { TemplateKey } from './manifest.ts';
import template_000 from './app/client.ts.template' with { type: 'text' };
import template_001 from './app/assets/design.css.template' with { type: 'text' };
import template_002 from './app/components/ui/mod.ts.template' with { type: 'text' };
import template_003 from './app/routes/(design)/design/(_islands)/FloatingSurfaceDemo.tsx.template' with { type: 'text' };
import template_004 from './app/routes/(design)/design/(_islands)/TokenClipboard.tsx.template' with { type: 'text' };
import template_005 from './app/routes/(design)/design/(_shared)/registry.ts.template' with { type: 'text' };
import template_006 from './app/routes/(design)/design/(_shared)/tokens.ts.template' with { type: 'text' };
import template_007 from './app/lib/example-service.ts.template' with { type: 'text' };
import template_008 from './app/main.ts.template' with { type: 'text' };
import template_009 from './app/router.ts.template' with { type: 'text' };
import template_010 from './app/routes/(_components)/health-view.tsx.template' with { type: 'text' };
import template_011 from './app/routes/(_components)/dashboard-view.tsx.template' with { type: 'text' };
import template_012 from './app/routes/(_components)/home-view.tsx.template' with { type: 'text' };
import template_013 from './app/routes/(_shared)/health.ts.template' with { type: 'text' };
import template_014 from './app/routes/_app.tsx.template' with { type: 'text' };
import template_015 from './app/routes/_layout.tsx.template' with { type: 'text' };
import template_016 from './app/routes/(design)/design/components.tsx.template' with { type: 'text' };
import template_017 from './app/routes/(design)/design/(_components)/components-view.tsx.template' with { type: 'text' };
import template_018 from './app/routes/(design)/design/composition.tsx.template' with { type: 'text' };
import template_019 from './app/routes/(design)/design/(_components)/composition-view.tsx.template' with { type: 'text' };
import template_020 from './app/routes/(design)/design/index.tsx.template' with { type: 'text' };
import template_021 from './app/routes/(design)/design/_layout.tsx.template' with { type: 'text' };
import template_022 from './app/routes/(design)/design/tokens.tsx.template' with { type: 'text' };
import template_023 from './app/routes/(design)/design/(_components)/tokens-view.tsx.template' with { type: 'text' };
import template_024 from './app/routes/examples/(_components)/examples-view.tsx.template' with { type: 'text' };
import template_025 from './app/routes/examples/(_components)/crud-view.tsx.template' with { type: 'text' };
import template_026 from './app/routes/examples/(_components)/hero.tsx.template' with { type: 'text' };
import template_027 from './app/routes/examples/(_components)/lab-panel.tsx.template' with { type: 'text' };
import template_028 from './app/routes/examples/(_components)/notes-card.tsx.template' with { type: 'text' };
import template_029 from './app/routes/examples/(_components)/page-layout.tsx.template' with { type: 'text' };
import template_030 from './app/routes/examples/(_components)/summary-card.tsx.template' with { type: 'text' };
import template_031 from './app/routes/examples/(_components)/summary-panel.tsx.template' with { type: 'text' };
import template_032 from './app/routes/examples/(_islands)/ServiceShowcaseLab.tsx.template' with { type: 'text' };
import template_033 from './app/routes/examples/(_shared)/service-showcase.ts.template' with { type: 'text' };
import template_034 from './app/routes/examples/index.tsx.template' with { type: 'text' };
import template_035 from './app/routes/examples/crud.tsx.template' with { type: 'text' };
import template_036 from './app/routes/examples/service/index.layout.tsx.template' with { type: 'text' };
import template_037 from './app/routes/examples/service/index.tsx.template' with { type: 'text' };
import template_038 from './app/routes/examples/telemetry/(_components)/telemetry-view.tsx.template' with { type: 'text' };
import template_039 from './app/routes/examples/telemetry/(_shared)/telemetry-trace.ts.template' with { type: 'text' };
import template_040 from './app/routes/examples/telemetry/index.tsx.template' with { type: 'text' };
import template_041 from './app/routes/health.tsx.template' with { type: 'text' };
import template_042 from './app/routes/index.tsx.template' with { type: 'text' };
import template_043 from './app/routes/dashboard.tsx.template' with { type: 'text' };
import template_044 from './app/routes/partials/examples/service-summary.tsx.template' with { type: 'text' };
import template_045 from './app/utils.ts.template' with { type: 'text' };
import template_046 from './app/vite.config.ts.template' with { type: 'text' };
import template_047 from './aspire/AppHost.csproj.template' with { type: 'text' };
import template_048 from './aspire/Extensions.cs.template' with { type: 'text' };
import template_049 from './aspire/NetScriptTelemetryDefaults.cs.template' with { type: 'text' };
import template_050 from './aspire/Program.cs.template' with { type: 'text' };
import template_051 from './aspire/ServiceDefaults.csproj.template' with { type: 'text' };
import template_052 from './aspire/helpers/_aspire-compat.ts.template' with { type: 'text' };
import template_053 from './aspire/helpers/apphost.ts.template' with { type: 'text' };
import template_054 from './aspire/helpers/configure-dashboard.ts.template' with { type: 'text' };
import template_055 from './aspire/launchSettings.json.template' with { type: 'text' };
import template_056 from './database/connection-helpers.ts.template' with { type: 'text' };
import template_057 from './database/schema.prisma.template' with { type: 'text' };
import template_058 from './database/scripts/fix-zod-imports.ts.template' with { type: 'text' };
import template_059 from './database/scripts/generate-zod.ts.template' with { type: 'text' };
import template_060 from './database/scripts/migrate.ts.template' with { type: 'text' };
import template_061 from './database/scripts/patch-prisma-client.ts.template' with { type: 'text' };
import template_062 from './database/seed.ts.template' with { type: 'text' };
import template_063 from './database/zod-generator.config.json.template' with { type: 'text' };
import template_064 from './generated/aspire/helpers/generate-db-cli-mode-1.ts.template' with { type: 'text' };
import template_065 from './generated/aspire/helpers/generate-index-1.ts.template' with { type: 'text' };
import template_066 from './generated/aspire/helpers/generate-register-apps-1.ts.template' with { type: 'text' };
import template_067 from './generated/aspire/helpers/generate-register-background-1.ts.template' with { type: 'text' };
import template_068 from './generated/aspire/helpers/generate-register-infrastructure-1.ts.template' with { type: 'text' };
import template_069 from './generated/aspire/helpers/generate-register-plugins-1.ts.template' with { type: 'text' };
import template_070 from './generated/aspire/helpers/generate-register-services-1.ts.template' with { type: 'text' };
import template_071 from './generated/aspire/helpers/generate-register-tools-1.ts.template' with { type: 'text' };
import template_072 from './generated/database/generate-engine-mod-1.ts.template' with { type: 'text' };
import template_073 from './generated/database/generate-prisma-config-1.ts.template' with { type: 'text' };
import template_074 from './generated/plugins/generate-plugin-contracts-1.ts.template' with { type: 'text' };
import template_075 from './generated/plugins/generate-plugin-db-schema-1.ts.template' with { type: 'text' };
import template_076 from './generated/plugins/generate-plugin-samples-1.ts.template' with { type: 'text' };
import template_077 from './generated/plugins/generate-plugin-samples-2.ts.template' with { type: 'text' };
import template_078 from './generated/plugins/generate-plugin-samples-3.ts.template' with { type: 'text' };
import template_079 from './generated/plugins/generate-plugin-service-1.ts.template' with { type: 'text' };
import template_080 from './generated/plugins/generate-plugin-service-2.ts.template' with { type: 'text' };
import template_081 from './generated/plugins/generate-plugin-service-3.ts.template' with { type: 'text' };
import template_082 from './generated/workspace/netscript-config-1.ts.template' with { type: 'text' };
import template_083 from './plugins/service-context.ts.template' with { type: 'text' };
import template_084 from './service/contract.ts.template' with { type: 'text' };
import template_085 from './service/main.ts.template' with { type: 'text' };
import template_086 from './service/router.ts.template' with { type: 'text' };
import template_087 from './service/routers/health.ts.template' with { type: 'text' };
import template_088 from './service/routers/v1.ts.template' with { type: 'text' };
import template_089 from './windows/env.template' with { type: 'text' };
import template_090 from './workspace/contracts/mod.ts.template' with { type: 'text' };
import template_091 from './workspace/contracts/v1-aggregate.ts.template' with { type: 'text' };
import template_092 from './workspace/contracts/v1-empty.ts.template' with { type: 'text' };
import template_093 from './workspace/gitignore.template' with { type: 'text' };
import template_094 from './workspace/plugins/mod.ts.template' with { type: 'text' };

/** Embedded text content for every checked-in CLI template asset. */
export const EMBEDDED_TEMPLATE_CONTENT: Record<TemplateKey, string> = {
  "app/client.ts.template": template_000,
  "app/assets/design.css.template": template_001,
  "app/components/ui/mod.ts.template": template_002,
  "app/routes/(design)/design/(_islands)/FloatingSurfaceDemo.tsx.template": template_003,
  "app/routes/(design)/design/(_islands)/TokenClipboard.tsx.template": template_004,
  "app/routes/(design)/design/(_shared)/registry.ts.template": template_005,
  "app/routes/(design)/design/(_shared)/tokens.ts.template": template_006,
  "app/lib/example-service.ts.template": template_007,
  "app/main.ts.template": template_008,
  "app/router.ts.template": template_009,
  "app/routes/(_components)/health-view.tsx.template": template_010,
  "app/routes/(_components)/dashboard-view.tsx.template": template_011,
  "app/routes/(_components)/home-view.tsx.template": template_012,
  "app/routes/(_shared)/health.ts.template": template_013,
  "app/routes/_app.tsx.template": template_014,
  "app/routes/_layout.tsx.template": template_015,
  "app/routes/(design)/design/components.tsx.template": template_016,
  "app/routes/(design)/design/(_components)/components-view.tsx.template": template_017,
  "app/routes/(design)/design/composition.tsx.template": template_018,
  "app/routes/(design)/design/(_components)/composition-view.tsx.template": template_019,
  "app/routes/(design)/design/index.tsx.template": template_020,
  "app/routes/(design)/design/_layout.tsx.template": template_021,
  "app/routes/(design)/design/tokens.tsx.template": template_022,
  "app/routes/(design)/design/(_components)/tokens-view.tsx.template": template_023,
  "app/routes/examples/(_components)/examples-view.tsx.template": template_024,
  "app/routes/examples/(_components)/crud-view.tsx.template": template_025,
  "app/routes/examples/(_components)/hero.tsx.template": template_026,
  "app/routes/examples/(_components)/lab-panel.tsx.template": template_027,
  "app/routes/examples/(_components)/notes-card.tsx.template": template_028,
  "app/routes/examples/(_components)/page-layout.tsx.template": template_029,
  "app/routes/examples/(_components)/summary-card.tsx.template": template_030,
  "app/routes/examples/(_components)/summary-panel.tsx.template": template_031,
  "app/routes/examples/(_islands)/ServiceShowcaseLab.tsx.template": template_032,
  "app/routes/examples/(_shared)/service-showcase.ts.template": template_033,
  "app/routes/examples/index.tsx.template": template_034,
  "app/routes/examples/crud.tsx.template": template_035,
  "app/routes/examples/service/index.layout.tsx.template": template_036,
  "app/routes/examples/service/index.tsx.template": template_037,
  "app/routes/examples/telemetry/(_components)/telemetry-view.tsx.template": template_038,
  "app/routes/examples/telemetry/(_shared)/telemetry-trace.ts.template": template_039,
  "app/routes/examples/telemetry/index.tsx.template": template_040,
  "app/routes/health.tsx.template": template_041,
  "app/routes/index.tsx.template": template_042,
  "app/routes/dashboard.tsx.template": template_043,
  "app/routes/partials/examples/service-summary.tsx.template": template_044,
  "app/utils.ts.template": template_045,
  "app/vite.config.ts.template": template_046,
  "aspire/AppHost.csproj.template": template_047,
  "aspire/Extensions.cs.template": template_048,
  "aspire/NetScriptTelemetryDefaults.cs.template": template_049,
  "aspire/Program.cs.template": template_050,
  "aspire/ServiceDefaults.csproj.template": template_051,
  "aspire/helpers/_aspire-compat.ts.template": template_052,
  "aspire/helpers/apphost.ts.template": template_053,
  "aspire/helpers/configure-dashboard.ts.template": template_054,
  "aspire/launchSettings.json.template": template_055,
  "database/connection-helpers.ts.template": template_056,
  "database/schema.prisma.template": template_057,
  "database/scripts/fix-zod-imports.ts.template": template_058,
  "database/scripts/generate-zod.ts.template": template_059,
  "database/scripts/migrate.ts.template": template_060,
  "database/scripts/patch-prisma-client.ts.template": template_061,
  "database/seed.ts.template": template_062,
  "database/zod-generator.config.json.template": template_063,
  "generated/aspire/helpers/generate-db-cli-mode-1.ts.template": template_064,
  "generated/aspire/helpers/generate-index-1.ts.template": template_065,
  "generated/aspire/helpers/generate-register-apps-1.ts.template": template_066,
  "generated/aspire/helpers/generate-register-background-1.ts.template": template_067,
  "generated/aspire/helpers/generate-register-infrastructure-1.ts.template": template_068,
  "generated/aspire/helpers/generate-register-plugins-1.ts.template": template_069,
  "generated/aspire/helpers/generate-register-services-1.ts.template": template_070,
  "generated/aspire/helpers/generate-register-tools-1.ts.template": template_071,
  "generated/database/generate-engine-mod-1.ts.template": template_072,
  "generated/database/generate-prisma-config-1.ts.template": template_073,
  "generated/plugins/generate-plugin-contracts-1.ts.template": template_074,
  "generated/plugins/generate-plugin-db-schema-1.ts.template": template_075,
  "generated/plugins/generate-plugin-samples-1.ts.template": template_076,
  "generated/plugins/generate-plugin-samples-2.ts.template": template_077,
  "generated/plugins/generate-plugin-samples-3.ts.template": template_078,
  "generated/plugins/generate-plugin-service-1.ts.template": template_079,
  "generated/plugins/generate-plugin-service-2.ts.template": template_080,
  "generated/plugins/generate-plugin-service-3.ts.template": template_081,
  "generated/workspace/netscript-config-1.ts.template": template_082,
  "plugins/service-context.ts.template": template_083,
  "service/contract.ts.template": template_084,
  "service/main.ts.template": template_085,
  "service/router.ts.template": template_086,
  "service/routers/health.ts.template": template_087,
  "service/routers/v1.ts.template": template_088,
  "windows/env.template": template_089,
  "workspace/contracts/mod.ts.template": template_090,
  "workspace/contracts/v1-aggregate.ts.template": template_091,
  "workspace/contracts/v1-empty.ts.template": template_092,
  "workspace/gitignore.template": template_093,
  "workspace/plugins/mod.ts.template": template_094,
};
