export function registryGeneratorFixture(): string {
  return `import { join } from 'jsr:@std/path@^1';

const projectRoot = Deno.args[Deno.args.indexOf('--project-root') + 1] ?? Deno.cwd();
const jobsDir = join(projectRoot, 'workers', 'jobs');
const files = ['health-check.ts', 'example-job.ts'];
try {
  await Deno.stat(join(projectRoot, 'sagas'));
  files.push('send-welcome-email.ts', 'process-payment-webhook.ts');
} catch {
  // optional
}
try {
  await Deno.stat(join(projectRoot, 'plugins', 'triggers'));
  files.push('process-webhook-payload.ts');
} catch {
  // optional
}
const imports = [];
const handlerEntries = [];
const handlerTypes = [];
const definitionEntries = [];
const registryEntries = [];
for (const file of files) {
  try {
    await Deno.stat(join(jobsDir, file));
  } catch {
    continue;
  }
  const id = file.replace(/\\.ts$/, '');
  const name = id.replace(/-/g, '');
  imports.push(\`import \${name} from '../../../workers/jobs/\${file}';\`);
  handlerEntries.push(\`  [\${name}.id]: \${name},\`);
  handlerTypes.push(\`  & Readonly<Record<typeof \${name}.id, typeof \${name}>>\`);
  registryEntries.push(\`  [\${name}.id, \${name}],\`);
  definitionEntries.push(
    \`  [\${name}.id]: createLocalJobDefinition(\${name}.id, './\${file}', \${name}),\`,
  );
}
await Deno.mkdir(join(projectRoot, '.netscript', 'generated', 'plugin-workers'), { recursive: true });
await Deno.writeTextFile(join(projectRoot, '.netscript', 'generated', 'plugin-workers', 'job-registry.ts'), [
  "import type { JobPayloadMap, RegisterJobInput, StaticJobRegistry } from '@netscript/plugin-workers-core/runtime';",
  ...imports,
  '',
  'type SchemaBackedJobHandler =',
  '  & ((...args: never[]) => unknown)',
  '  & Readonly<{ id: string; payloadSchema: unknown }>;',
  '',
  'export type GeneratedJobHandlerRegistry =',
  ...handlerTypes,
  ';',
  '',
  'export const jobHandlersById: GeneratedJobHandlerRegistry = Object.freeze({',
  ...handlerEntries,
  '});',
  '',
  'type StaticJobHandler = StaticJobRegistry extends ReadonlyMap<string, infer THandler>',
  '  ? THandler',
  '  : never;',
  '',
  'export const registry: StaticJobRegistry = new Map<string, StaticJobHandler>([',
  ...registryEntries,
  ']);',
  '',
  'type GeneratedJobDefinition<TId extends string, THandler extends SchemaBackedJobHandler> =',
  '  Readonly<RegisterJobInput & {',
  '    readonly id: TId;',
  '    readonly handler: THandler;',
  '    readonly payloadSchema: THandler["payloadSchema"];',
  '  }>;',
  '',
  'export type GeneratedJobDefinitionRegistry = Readonly<{',
  '  [TId in keyof GeneratedJobHandlerRegistry]: GeneratedJobDefinition<',
  '    TId & string,',
  '    GeneratedJobHandlerRegistry[TId]',
  '  >;',
  '}>;',
  '',
  'export type GeneratedJobPayloadMap = JobPayloadMap<GeneratedJobDefinitionRegistry>;',
  '',
  'export const jobDefinitionsById: GeneratedJobDefinitionRegistry = Object.freeze({',
  ...definitionEntries,
  '});',
  '',
  'const jobDefinitionEntries: readonly [string, RegisterJobInput][] =',
  '  Object.entries(jobDefinitionsById).map(([id, definition]) => [id, toRegisterJobInput(definition)]);',
  '',
  'export const jobDefinitions: ReadonlyMap<string, RegisterJobInput> = new Map(jobDefinitionEntries);',
  'export const definitions: ReadonlyMap<string, RegisterJobInput> = jobDefinitions;',
  '',
  'function createLocalJobDefinition<TId extends string, THandler extends SchemaBackedJobHandler>(',
  '  id: TId,',
  '  entrypoint: string,',
  '  handler: THandler,',
  '): GeneratedJobDefinition<TId, THandler> {',
  '  return {',
  '    id,',
  '    name: id.split("-").map((part) => part.slice(0, 1).toUpperCase() + part.slice(1)).join(" "),',
  '    entrypoint,',
  '    topic: "default",',
  '    source: "local",',
  '    executionType: "deno",',
  '    timezone: "UTC",',
  '    timeout: 300000,',
  '    maxRetries: 3,',
  '    retryDelay: 1000,',
  '    maxConcurrency: 1,',
  '    priority: 50,',
  '    enabled: true,',
  '    persist: true,',
  '    tags: [],',
  '    handler,',
  '    payloadSchema: handler.payloadSchema,',
  '  };',
  '}',
  '',
  'function toRegisterJobInput(definition: RegisterJobInput): RegisterJobInput {',
  '  const { handler: _handler, payloadSchema: _payloadSchema, ...registration } = definition;',
  '  return registration;',
  '}',
  '',
].join('\\n'));
const officialSamplesArg = Deno.args[Deno.args.indexOf('--official-samples') + 1];
if (officialSamplesArg !== 'false') {
  const hasSagas = await existsDir(join(projectRoot, 'sagas'));
  const hasTriggers = await existsDir(join(projectRoot, 'triggers'));
  await Deno.mkdir(join(projectRoot, 'config', 'official-plugins'), { recursive: true });
  await Deno.writeTextFile(
    join(projectRoot, 'config', 'official-plugins', 'mod.ts'),
    [
      '// <auto-generated by netscript official plugin copier>',
      "import { defineSagas } from '@netscript/config';",
      "import { defineTriggers } from '@netscript/plugin-triggers-core/config';",
      "import { defineWorkers } from '@netscript/plugin-workers-core/config';",
      "import type { RuntimeConfigSection } from '@netscript/config';",
      '',
      'export const workers = defineWorkers({',
      "  jobsDir: './workers/jobs',",
      "  tasksDir: './workers/tasks',",
      '  enabled: true,',
      '  groups: [',
      ...(hasTriggers ? ["    { topic: 'webhooks', jobs: [{ id: 'process-webhook-payload', name: 'Process Webhook Payload', entrypoint: './process-webhook-payload.ts' }] },"] : []),
      ...(hasSagas ? ["    { topic: 'sagas', jobs: [{ id: 'send-welcome-email', name: 'Send Welcome Email', entrypoint: './send-welcome-email.ts' }] },"] : []),
      '  ],',
      '});',
      "export const sagas = defineSagas({ enabled: " + String(hasSagas) + ", groups: " + (hasSagas ? "[{ topic: 'users', sagas: [{ id: 'UserRegistrationSaga' }] }]" : '[]') + ' });',
      "export const triggers = defineTriggers({ enabled: " + String(hasTriggers) + ", groups: " + (hasTriggers ? "[{ topic: 'webhooks', triggers: [{ id: 'webhook-validate-data' }] }]" : '[]') + ' });',
      'export const runtimeConfig: RuntimeConfigSection = { paths: { workers: { schemaPath: "./workers/runtime/schema.json", configDir: "./workers/runtime" }, sagas: { schemaPath: "./sagas/runtime/schema.json", configDir: "./sagas/runtime" }, triggers: { schemaPath: "./triggers/runtime/schema.json", configDir: "./triggers/runtime" } } };',
      '',
    ].join('\\n'),
  );
  await writeJson(join(projectRoot, 'workers', 'runtime', 'tasks', 'v1.0.0.json'), {
    tasks: [{ id: 'validate-data' }, { id: 'system-diagnostics' }],
  });
  if (hasTriggers) {
    await writeJson(join(projectRoot, 'triggers', 'runtime', 'triggers', 'v1.0.0.json'), {
      overrides: [{ id: 'file-watcher-diagnostics', paths: ['.data/incoming/diagnostics'] }],
    });
  }
}

async function existsDir(path) {
  try {
    return (await Deno.stat(path)).isDirectory;
  } catch {
    return false;
  }
}

async function writeJson(path, value) {
  await Deno.mkdir(join(path, '..'), { recursive: true });
  await Deno.writeTextFile(path, JSON.stringify(value, null, 2) + '\\n');
}

`;
}
