export const GATE_CATALOG = {
  'gates-test': ['deno', 'task', 'gates:test'],
  'milestone-cluster-test': ['deno', 'task', 'harness:milestone:test'],
  'agentic-lifecycle-test': [
    'deno',
    'test',
    '--allow-read',
    '--allow-env',
    '.github/scripts/phase-eval-status.test.ts',
    '.github/scripts/openhands-comment-trigger.test.ts',
    '.llm/tools/agentic/openhands/phase-eval-workflow_test.ts',
    '.llm/tools/agentic/github/gh-pr_test.ts',
    '.llm/tools/agentic/lib/agentic-lib_test.ts',
  ],
  'harness-tooling-check': [
    'deno',
    'check',
    '.llm/tools/gates/run-gate.ts',
    '.llm/tools/gates/command-lifecycle_test.ts',
    '.llm/tools/gates/evidence-set_test.ts',
    '.llm/tools/gates/process-runner_test.ts',
    '.llm/tools/gates/receipt-store_test.ts',
    '.llm/tools/run-deno-test.ts',
    '.llm/tools/harness/render-milestone-status.ts',
    '.llm/tools/harness/validate-milestone-cluster.ts',
    '.llm/tools/agentic/github/gh-pr.ts',
  ],
  'check-test-job': ['deno', 'task', 'check'],
  'quality-job': ['deno', 'task', 'ci:quality'],
  check: ['deno', 'task', 'check'],
  lint: ['deno', 'task', 'lint'],
  'fmt-check': ['deno', 'task', 'fmt:check'],
  'doc-lint': ['deno', 'task', 'doc:lint'],
  'quality-gate': ['deno', 'task', 'quality:gate'],
  test: ['deno', 'task', 'test'],
  'quality-scan': ['deno', 'task', 'quality:scan'],
  'quality-scan-repo': ['deno', 'task', 'quality:scan:repo'],
  'arch-check': ['deno', 'task', 'arch:check'],
  'allowance-budget': [
    'deno',
    'run',
    '--allow-run',
    '.llm/tools/quality/check-allowance-budget-diff.ts',
  ],
  'fresh-ui-lock-regression': [
    'deno',
    'test',
    '--no-lock',
    '--allow-read',
    '--allow-write',
    '--allow-run',
    '.llm/tools/validation/fresh-ui-quality_test.ts',
  ],
  'public-doc-lint': ['deno', 'doc', '--lint'],
  'fresh-browser': ['deno', 'task', 'test:browser'],
  'docs-source-format': ['deno', 'task', 'check:source-format'],
  'docs-source-format-test': ['deno', 'task', 'test:source-format'],
  'docs-tagline': ['deno', 'task', 'docs:tagline:check'],
  'docs-accuracy': ['deno', 'task', 'docs:accuracy'],
  'agent-docs-prose': ['deno', 'task', 'check:agent-docs-prose'],
  'assets-barrel': ['deno', 'task', 'check:assets-barrel'],
  'publish-assets': ['deno', 'task', 'check:publish-assets'],
  'emitted-samples': ['deno', 'task', 'check:emitted-samples'],
  'netscript-jsr-specifiers': ['deno', 'task', 'check:netscript-jsr-specifiers'],
  'scaffold-versions': ['deno', 'task', 'check:scaffold-versions'],
  'aspire-version-parity': ['deno', 'task', 'check:aspire-version-parity'],
  'publish-dry-run': ['deno', 'task', 'publish:dry-run'],
  'audit-critical': ['deno', 'task', 'audit:critical'],
  'clean-worktree': [
    'deno',
    'run',
    '--allow-run=git',
    '.llm/tools/gates/verify-clean-worktree.ts',
  ],
} as const;

export type GateName = keyof typeof GATE_CATALOG;

export function gateArgv(name: string, args: string[] = []): string[] {
  if (!(name in GATE_CATALOG)) throw new Error(`Unknown gate '${name}'`);
  return [...GATE_CATALOG[name as GateName], ...args];
}
