/**
 * Structural TanStack Query utility types derived from service contracts.
 *
 * @module
 */

import type {
  ContractLike,
  ContractProcedureLike,
  ProcedureInputFromNode,
  ProcedureOutputFromNode,
  ServiceClientMethod,
  ServiceRequestRest,
} from './service-client.ts';

/** Operation kinds accepted by service query utility keys. */
export type ServiceOperationType = 'query' | 'streamed' | 'live' | 'infinite' | 'mutation';

/** Serializable streamed-query key options. */
export interface ServiceStreamedKeyOptions {
  /** How streamed chunks are handled when the query refetches. */
  refetchMode?: 'append' | 'reset' | 'replace';
  /** Maximum chunks retained by the query result. */
  maxChunks?: number;
}

/** Deep partial input used by matching-key helpers. */
export type ServicePartialInput<TInput> = unknown extends TInput ? unknown
  : TInput extends readonly (infer TItem)[] ? readonly ServicePartialInput<TItem>[]
  : TInput extends object ? { readonly [K in keyof TInput]?: ServicePartialInput<TInput[K]> }
  : TInput;

/** Client context forwarded by SDK-created service query utilities. */
export type ServiceQueryClientContext<
  TContext extends object = Record<never, never>,
> = TContext;

/** Partial matching-key options accepted at router or procedure levels. */
export interface ServiceOperationKeyOptions<
  TInput,
  TType extends ServiceOperationType = ServiceOperationType,
> {
  /** Operation kind to include in the partial key. */
  type?: TType;
  /** Partial input included in non-mutation matching keys. */
  input?: TType extends 'mutation' ? never : ServicePartialInput<TInput>;
  /** Streamed-query options included in streamed matching keys. */
  fnOptions?: TType extends 'streamed' ? ServiceStreamedKeyOptions : never;
}

/** Partial matching key generated by service query utilities. */
export type ServiceOperationKey<
  TInput,
  TType extends ServiceOperationType = ServiceOperationType,
> = [
  path: readonly string[],
  options: ServiceOperationKeyOptions<TInput, TType>,
];

/** Query-key options for a single service procedure. */
export type ServiceQueryKeyOptions<
  TInput,
  TContext extends object = Record<never, never>,
> =
  & (undefined extends TInput ? {
      /** Procedure input included in the full query key. */
      input?: TInput;
    }
    : {
      /** Procedure input included in the full query key. */
      input: TInput;
    })
  & {
    /** Additional key segments appended to the generated key. */
    queryKey?: readonly unknown[];
  }
  & NonNullable<ServiceRequestRest<TContext>[0]>;

/** Query options accepted by a service procedure utility. */
export type ServiceProcedureQueryOptions<
  TInput,
  TContext extends object = Record<never, never>,
> = ServiceQueryKeyOptions<TInput, TContext> & {
  /** Whether the query should run. */
  enabled?: boolean;
  /** Cache freshness window in milliseconds. */
  staleTime?: number;
};

/** Query options returned by a service procedure utility. */
export interface ServiceProcedureQueryResult<TOutput> {
  /** Full query key tagged by the utility implementation. */
  readonly queryKey: readonly unknown[];
  /** Query function that invokes the service procedure. */
  readonly queryFn: (context: never) => Promise<TOutput> | TOutput;
  /** Whether the query should run. */
  readonly enabled?: boolean;
  /** Cache freshness window in milliseconds. */
  readonly staleTime?: number;
}

/** Infinite-query options accepted by a service procedure utility. */
export type ServiceProcedureInfiniteOptions<
  TInput,
  TPageParam = unknown,
  TContext extends object = Record<never, never>,
> =
  & {
    /** Input factory for each page parameter. */
    input: (pageParam: TPageParam) => TInput;
    /** Initial page parameter passed to the first query function call. */
    initialPageParam: TPageParam;
    /** Additional key segments appended to the generated key. */
    queryKey?: readonly unknown[];
    /** Whether the query should run. */
    enabled?: boolean;
  }
  & NonNullable<ServiceRequestRest<TContext>[0]>;

/** Infinite-query options returned by a service procedure utility. */
export interface ServiceProcedureInfiniteResult<TOutput, TPageParam = unknown> {
  /** Full infinite-query key tagged by the utility implementation. */
  readonly queryKey?: readonly unknown[];
  /** Query function that invokes the service procedure for a page. */
  readonly queryFn: (context: never) => Promise<TOutput> | TOutput;
  /** Whether the query should run. */
  readonly enabled?: boolean;
}

/** Mutation options accepted by a service procedure utility. */
export type ServiceProcedureMutationOptions<
  TInput,
  TOutput,
  TMutationContext = unknown,
  TContext extends object = Record<never, never>,
> =
  & {
    /** Optional mutation key override. */
    mutationKey?: readonly unknown[];
    /** Success callback from TanStack Query mutation options. */
    onSuccess?: (data: TOutput, variables: TInput, context: TMutationContext) => void;
    /** Error callback from TanStack Query mutation options. */
    onError?: (error: unknown, variables: TInput, context: TMutationContext | undefined) => void;
    /** Settled callback from TanStack Query mutation options. */
    onSettled?: (
      data: TOutput | undefined,
      error: unknown | null,
      variables: TInput,
      context: TMutationContext | undefined,
    ) => void;
  }
  & NonNullable<ServiceRequestRest<TContext>[0]>;

/** Mutation options returned by a service procedure utility. */
export interface ServiceProcedureMutationResult<TInput, TOutput, TMutationContext = unknown> {
  /** Full mutation key tagged by the utility implementation. */
  readonly mutationKey?: readonly unknown[];
  /** Mutation function that invokes the service procedure. */
  readonly mutationFn?: (input: TInput, context: never) => Promise<TOutput> | TOutput;
}

/** Streamed-query options accepted by a service procedure utility. */
export type ServiceProcedureStreamedOptions<
  TInput,
  TContext extends object = Record<never, never>,
> = ServiceProcedureQueryOptions<TInput, TContext> & {
  /** Streamed-query function options. */
  queryFnOptions?: ServiceStreamedKeyOptions;
};

/** Live-query options returned by a service procedure utility. */
export type ServiceProcedureLiveResult<TOutput> = ServiceProcedureQueryResult<
  TOutput extends AsyncIterable<infer TChunk> ? TChunk : never
>;

/** Streamed-query options returned by a service procedure utility. */
export type ServiceProcedureStreamedResult<TOutput> = ServiceProcedureQueryResult<
  TOutput extends AsyncIterable<infer TChunk> ? TChunk[] : never
>;

/** Optional or required single-option tuple based on procedure input optionality. */
export type ServiceOptionalInputRest<TInput, TOptions> = undefined extends TInput
  ? Record<never, never> extends TOptions ? [options?: TOptions]
  : [options: TOptions]
  : [options: TOptions];

/** TanStack Query utilities for one service procedure. */
export interface ServiceProcedureQueryUtils<
  TInput,
  TOutput,
  TContext extends object = Record<never, never>,
> {
  /** Direct service-client method for the procedure. */
  readonly call: ServiceClientMethod<TInput, TOutput, Error, TContext>;
  /** Generate a partial matching key for this procedure. */
  key<TType extends ServiceOperationType>(
    options?: ServiceOperationKeyOptions<TInput, TType>,
  ): ServiceOperationKey<TInput, TType>;
  /** Generate a full query key for this procedure. */
  queryKey(
    ...options: ServiceOptionalInputRest<TInput, ServiceQueryKeyOptions<TInput, TContext>>
  ): readonly unknown[];
  /** Generate TanStack Query options for this procedure. */
  queryOptions(
    ...options: ServiceOptionalInputRest<
      TInput,
      ServiceProcedureQueryOptions<TInput, TContext>
    >
  ): ServiceProcedureQueryResult<TOutput>;
  /** Generate a full streamed-query key for this procedure. */
  experimental_streamedKey(
    ...options: ServiceOptionalInputRest<
      TInput,
      ServiceProcedureStreamedOptions<TInput, TContext>
    >
  ): readonly unknown[];
  /** Generate TanStack streamed-query options for this procedure. */
  experimental_streamedOptions(
    ...options: ServiceOptionalInputRest<
      TInput,
      ServiceProcedureStreamedOptions<TInput, TContext>
    >
  ): ServiceProcedureStreamedResult<TOutput>;
  /** Generate a full live-query key for this procedure. */
  experimental_liveKey(
    ...options: ServiceOptionalInputRest<TInput, ServiceQueryKeyOptions<TInput, TContext>>
  ): readonly unknown[];
  /** Generate TanStack live-query options for this procedure. */
  experimental_liveOptions(
    ...options: ServiceOptionalInputRest<
      TInput,
      ServiceProcedureQueryOptions<TInput, TContext>
    >
  ): ServiceProcedureLiveResult<TOutput>;
  /** Generate a full infinite-query key for this procedure. */
  infiniteKey<TPageParam>(
    options: ServiceProcedureInfiniteOptions<TInput, TPageParam, TContext>,
  ): readonly unknown[];
  /** Generate TanStack infinite-query options for this procedure. */
  infiniteOptions<TPageParam>(
    options: ServiceProcedureInfiniteOptions<TInput, TPageParam, TContext>,
  ): ServiceProcedureInfiniteResult<TOutput, TPageParam>;
  /** Generate a full mutation key for this procedure. */
  mutationKey(options?: { mutationKey?: readonly unknown[] }): readonly unknown[];
  /** Generate TanStack mutation options for this procedure. */
  mutationOptions<TMutationContext = unknown>(
    ...options: ServiceRequestRest<TContext> extends [options?: infer TOptions] ? [
        options?:
          & ServiceProcedureMutationOptions<
            TInput,
            TOutput,
            TMutationContext,
            TContext
          >
          & TOptions,
      ]
      : [
        options: ServiceProcedureMutationOptions<TInput, TOutput, TMutationContext, TContext>,
      ]
  ): ServiceProcedureMutationResult<TInput, TOutput, TMutationContext>;
}

/** TanStack Query utilities derived from a service contract. */
export type ServiceQueryUtils<
  TContract extends ContractLike,
  TContext extends object = Record<never, never>,
> = TContract extends ContractProcedureLike ? ServiceProcedureQueryUtils<
    ProcedureInputFromNode<TContract>,
    ProcedureOutputFromNode<TContract>,
    TContext
  >
  :
    & {
      /** Generate a partial matching key for this router branch. */
      key<TType extends ServiceOperationType>(
        options?: ServiceOperationKeyOptions<unknown, TType>,
      ): ServiceOperationKey<unknown, TType>;
    }
    & {
      [K in keyof TContract]: TContract[K] extends ContractLike
        ? ServiceQueryUtils<TContract[K], TContext>
        : never;
    };
