/**
 * @module templates/aspire/helpers/generators-test-support
 */

import type {
  AppEntry,
  BackgroundProcessorEntry,
  CacheEntry,
  DatabaseEntry,
  DenoDefaults,
  NetScriptConfig,
  PluginEntry,
  ServiceEntry,
  ToolEntry,
} from '@netscript/aspire/types';

/** Standard header substring present in all generated files. */
export const FILE_HEADER = 'GENERATED BY @netscript/cli';

export const MINIMAL_DENO_DEFAULTS: DenoDefaults = {
  Permissions: ['--allow-net', '--allow-env', '--allow-read', '--allow-sys'],
  WatchMode: true,
};

// --- Service Fixtures ---

export const MINIMAL_SERVICE: ServiceEntry = {
  Enabled: true,
  Runtime: 'deno',
  Port: 3000,
  Entrypoint: 'src/main.ts',
};

export const SERVICE_WITH_REFS: ServiceEntry = {
  Enabled: true,
  Runtime: 'deno',
  Port: 3001,
  Entrypoint: 'src/main.ts',
  Workdir: 'services/orders',
  ServiceReferences: ['users'],
};

export const SERVICE_WITH_PLUGIN_REFS: ServiceEntry = {
  Enabled: true,
  Runtime: 'deno',
  Port: 3002,
  Entrypoint: 'src/main.ts',
  Workdir: 'services/reporting',
  PluginReferences: ['workers-api'],
};

// --- Plugin Fixtures ---

export const MINIMAL_PLUGIN: PluginEntry = {
  Enabled: true,
  Runtime: 'deno',
  Port: 4400,
  Entrypoint: 'src/main.ts',
  RequiresKv: false,
  RequiresDb: true,
};

export const PLUGIN_WITH_REFS: PluginEntry = {
  Enabled: true,
  Runtime: 'deno',
  Port: 4401,
  Entrypoint: 'src/main.ts',
  RequiresKv: false,
  RequiresDb: false,
  PluginReferences: ['auth'],
  ServiceReferences: ['users'],
};

// --- Database Fixtures ---

export const MINIMAL_DATABASE: DatabaseEntry = {
  Enabled: true,
  Engine: 'Postgres',
  Mode: 'Container',
  Persistent: false,
};

export const DATABASE_WITH_OPTIONS: DatabaseEntry = {
  Enabled: true,
  Engine: 'Postgres',
  Mode: 'Container',
  Persistent: true,
  DataPath: '.data/postgres',
  DatabaseName: 'app_db',
};

export const DATABASE_EXTERNAL: DatabaseEntry = {
  Enabled: true,
  Engine: 'Postgres',
  Mode: 'External',
  Persistent: false,
};

// --- Cache Fixtures ---

export const MINIMAL_CACHE: CacheEntry = {
  Enabled: true,
  Engine: 'Garnet',
  Mode: 'Container',
};

// --- Background Processor Fixtures ---

export const MINIMAL_BACKGROUND: BackgroundProcessorEntry = {
  Enabled: true,
  Runtime: 'deno',
  Entrypoint: 'bin/combined.ts',
  Telemetry: true,
  WatchMode: false,
  RequiresDb: false,
  RequiresKv: false,
};

export const BACKGROUND_NO_TELEMETRY: BackgroundProcessorEntry = {
  Enabled: true,
  Runtime: 'deno',
  Entrypoint: 'bin/combined.ts',
  Telemetry: false,
  WatchMode: false,
  RequiresDb: false,
  RequiresKv: false,
};

export const BACKGROUND_WITH_CONCURRENCY: BackgroundProcessorEntry = {
  Enabled: true,
  Runtime: 'deno',
  Entrypoint: 'bin/combined.ts',
  Telemetry: true,
  WatchMode: false,
  RequiresDb: true,
  RequiresKv: false,
  Concurrency: 4,
  ConcurrencyEnvVar: 'WORKERS_CONCURRENCY',
};

// --- App Fixtures ---

export const MINIMAL_APP: AppEntry = {
  Enabled: true,
  Runtime: 'deno',
  Type: 'app',
  WatchMode: false,
  RequiresKv: false,
  Port: 8000,
};

export const APP_WITH_REFS: AppEntry = {
  Enabled: true,
  Runtime: 'deno',
  Type: 'app',
  WatchMode: false,
  RequiresKv: false,
  Port: 8001,
  ServiceReferences: ['users'],
};

/** Desktop app fixture that exercises the public Aspire consumer contract. */
export const DESKTOP_APP: AppEntry = {
  Enabled: true,
  Runtime: 'deno',
  Type: 'desktop',
  WatchMode: false,
  Prebuild: 'build',
  TaskName: 'desktop:predev',
  PackageTaskName: 'desktop:package',
  RequiresKv: false,
  Port: 8999,
  ServiceReferences: ['users'],
  PluginReferences: ['workers-api'],
};

// --- Tool Fixtures ---

export const MINIMAL_TOOL: ToolEntry = {
  Enabled: true,
  TaskName: 'studio',
  Database: 'main',
};

// --- Full Config Fixtures (for pipeline tests) ---

export const POPULATED_CONFIG: NetScriptConfig = {
  Name: 'test-app',
  Version: '1.0.0',
  Otel: { HttpEndpoint: 'http://localhost:4318', Protocol: 'http/protobuf' },
  Defaults: { Deno: MINIMAL_DENO_DEFAULTS },
  Services: { users: MINIMAL_SERVICE },
  Apps: { frontend: MINIMAL_APP },
  Plugins: { auth: MINIMAL_PLUGIN },
  BackgroundProcessors: { workers: MINIMAL_BACKGROUND },
  Databases: { main: MINIMAL_DATABASE },
  Cache: { kv: MINIMAL_CACHE },
  Tools: { 'prisma-studio': MINIMAL_TOOL },
};

export const EMPTY_CONFIG: NetScriptConfig = {
  Name: 'test-app',
  Version: '1.0.0',
  Otel: { HttpEndpoint: 'http://localhost:4318', Protocol: 'http/protobuf' },
  Defaults: { Deno: { Permissions: ['--allow-net'], WatchMode: false } },
  Services: {},
  Apps: {},
  Plugins: {},
  BackgroundProcessors: {},
  Databases: {},
  Cache: {},
  Tools: {},
};
