/**
 * ClosureBuilder port: produce the full CSS closure the canvas needs.
 *
 * eis-chat's hard-won rule was "ship the compiled Tailwind closure, never a
 * hand-flattened subset" — because its components referenced Tailwind
 * `*-ns-*` utilities that only exist after a build. Today's fresh-ui
 * registry has **zero Tailwind utility classes** (verified: semantic `ns-*`
 * classes with paired per-component CSS only), so the complete closure is a
 * deterministic concatenation:
 *
 *   fonts → tokens.css → base rules → layouts.css → per-unit component CSS
 *
 * The only Tailwind-entangled file is `theme/styles.css` (an `@import
 * 'tailwindcss'` entry with `@apply` rules); its `@layer base` intent is
 * re-expressed below as plain CSS against `--ns-*` vars. `theme-bridge.css`
 * (a Tailwind v4 `@theme inline` bridge for consumer apps) is deliberately
 * omitted — it defines utilities-facing aliases, not rendered styles.
 */
import type { RegistryUnit, SyncConfig } from './types.ts';
import { fwd } from './config.ts';

/**
 * `theme/styles.css` `@layer base`, hand-mapped from `@apply` to vars.
 * Kept intentionally small: html/body ground, heading rhythm, media reset.
 */
const BASE_RULES = `/* base rules (mapped from fresh-ui theme/styles.css @layer base) */
html {
  background: var(--ns-bg);
  color: var(--ns-fg);
  min-height: 100%;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
body {
  margin: 0;
  background: var(--ns-bg);
  color: var(--ns-fg);
  font-family: var(--ns-font-sans);
  font-size: var(--ns-text-base, 1rem);
  line-height: var(--ns-leading-normal, 1.5);
  min-height: 100vh;
  transition: background-color 0.2s ease, color 0.2s ease;
}
a, button { touch-action: manipulation; }
h1, h2, h3, h4 {
  letter-spacing: -0.02em;
  line-height: 1.25;
  text-wrap: balance;
}
code, pre, kbd, samp { font-family: var(--ns-font-mono); }
img, svg, video { max-width: 100%; height: auto; }
`;

export interface ClosureResult {
  /** the full `_ds_bundle.css` content */
  css: string;
  /** ordered registry paths folded into the closure */
  parts: string[];
}

export interface ClosureBuilder {
  build(units: RegistryUnit[]): Promise<ClosureResult>;
}

export class RegistryConcatClosureBuilder implements ClosureBuilder {
  constructor(private readonly cfg: SyncConfig) {}

  async build(units: RegistryUnit[]): Promise<ClosureResult> {
    const root = `${this.cfg.repoRoot}/${fwd(this.cfg.registry.root)}`;
    const parts: string[] = [];
    const chunks: string[] = [
      '/* NS One canvas closure — generated by tools/design-sync (do not edit) */',
    ];

    const tokensPath = 'registry/theme/tokens.css';
    chunks.push(`/* == ${tokensPath} == */`, await Deno.readTextFile(`${root}/${tokensPath}`));
    parts.push(tokensPath);

    chunks.push('/* == base == */', BASE_RULES);

    const layoutsPath = 'registry/styles/layouts.css';
    chunks.push(`/* == ${layoutsPath} == */`, await Deno.readTextFile(`${root}/${layoutsPath}`));
    parts.push(layoutsPath);

    const seen = new Set<string>([tokensPath, layoutsPath]);
    for (const unit of units) {
      if (unit.excluded) continue;
      for (const src of unit.sources) {
        if (!src.registryPath.endsWith('.css') || seen.has(src.registryPath)) continue;
        // theme entries handled above; the Tailwind entry + bridge are omitted by design
        if (
          src.registryPath === 'registry/theme/styles.css' ||
          src.registryPath === 'registry/theme/theme-bridge.css'
        ) {
          seen.add(src.registryPath);
          continue;
        }
        seen.add(src.registryPath);
        chunks.push(`/* == ${src.registryPath} (${unit.item.name}) == */`, src.content);
        parts.push(src.registryPath);
      }
    }

    return { css: `${chunks.join('\n\n')}\n`, parts };
  }
}
