// @generated by .llm/tools/generate-cli-assets-barrel.ts
// Do not edit by hand. Run `deno task gen:assets-barrel`.

import type { PluginSkeletonTemplatePath } from './template-registry.ts';
import template_000 from '../../templates/skeleton/README.md.template' with { type: 'text' };
import template_001 from '../../templates/skeleton/deno.json.template' with { type: 'text' };
import template_002 from '../../templates/skeleton/mod.ts.template' with { type: 'text' };
import template_003 from '../../templates/skeleton/src/public/mod.ts.template' with {
  type: 'text',
};
import template_004 from '../../templates/skeleton/src/cli/{{plugin-name}}-cli.ts.template' with {
  type: 'text',
};
import template_005 from '../../templates/skeleton/src/cli/composition/main.ts.template' with {
  type: 'text',
};
import template_006 from '../../templates/skeleton/src/aspire/{{plugin-name}}-contribution.ts.template' with {
  type: 'text',
};
import template_007 from '../../templates/skeleton/src/aspire/mod.ts.template' with {
  type: 'text',
};
import template_008 from '../../templates/skeleton/src/e2e/mod.ts.template' with { type: 'text' };
import template_009 from '../../templates/skeleton/src/scaffolding/mod.ts.template' with {
  type: 'text',
};
import template_010 from '../../templates/skeleton/src/testing/mod.ts.template' with {
  type: 'text',
};
import template_011 from '../../templates/skeleton/docs/architecture.md.template' with {
  type: 'text',
};
import template_012 from '../../templates/skeleton/tests/_fixtures/readme-examples_test.ts.template' with {
  type: 'text',
};

/** Embedded text content for every default plugin skeleton template asset. */
export const PLUGIN_SKELETON_TEMPLATE_CONTENT: Record<PluginSkeletonTemplatePath, string> = {
  'README.md.template': template_000,
  'deno.json.template': template_001,
  'mod.ts.template': template_002,
  'src/public/mod.ts.template': template_003,
  'src/cli/{{plugin-name}}-cli.ts.template': template_004,
  'src/cli/composition/main.ts.template': template_005,
  'src/aspire/{{plugin-name}}-contribution.ts.template': template_006,
  'src/aspire/mod.ts.template': template_007,
  'src/e2e/mod.ts.template': template_008,
  'src/scaffolding/mod.ts.template': template_009,
  'src/testing/mod.ts.template': template_010,
  'docs/architecture.md.template': template_011,
  'tests/_fixtures/readme-examples_test.ts.template': template_012,
};
