import { assertEquals } from '@std/assert';
import {
  defineRegistryModule,
  defineRuntimeRegistryModule,
  renderRegistrySource,
  renderRuntimeRegistrySource,
} from '../../src/scaffold/mod.ts';

Deno.test('renderRegistrySource emits deterministic registry source', () => {
  const module = defineRegistryModule({
    imports: [{ alias: 'job0', specifier: '../jobs/send-email.ts' }],
    exportName: 'jobRegistry',
    entries: ['job0'],
  });

  assertEquals(
    renderRegistrySource(module),
    [
      '// <auto-generated />',
      '',
      'import * as job0 from "../jobs/send-email.ts";',
      '',
      'export const jobRegistry = [',
      '  job0,',
      '] as const;',
      '',
    ].join('\n'),
  );
});

Deno.test('renderRuntimeRegistrySource emits registry and runtime binding', () => {
  const module = defineRuntimeRegistryModule({
    imports: [],
    exportName: 'triggerRegistry',
    entries: [],
    runtimeExportName: 'runtimeRegistry',
    registryExpression: 'triggerRegistry',
  });

  assertEquals(
    renderRuntimeRegistrySource(module),
    [
      '// <auto-generated />',
      '',
      'export const triggerRegistry = [',
      '] as const;',
      '',
      'export const runtimeRegistry = triggerRegistry;',
      '',
    ].join('\n'),
  );
});
