import { assertEquals } from '@std/assert';
import type {
  ComponentLike,
  DefinedPartialRoute,
  DefinePartialOptions,
  DefineStatsPartialOptions,
  EmptyRecord,
  InferDefinePageLayerLoaderProps,
  PageBuilder,
  PageBuildOptions,
  PageCacheEntry,
  PageContext,
  PageDeferPolicyInput,
  PageDeferPolicyProfile,
  PageDefinition,
  PageErrorPrimitives,
  PageFormConfig,
  PageFormHandlerContext,
  PageHandlers,
  PageHeaderResolver,
  PageHooks,
  PageLayerConfig,
  PageLayerDelivery,
  PageLayerLoader,
  PageLayerMap,
  PageLayout,
  PageLayoutContext,
  PageLinkProps,
  PageMetaDescriptor,
  PageMetaResolver,
  PageMethod,
  PageMethodHandler,
  PagePairedRouteHrefInput,
  PagePairedRouteTarget,
  PagePartialLinkProps,
  PagePathParamInput,
  PagePathSchema,
  PageRenderable,
  PageRenderContext,
  PageRequestContext,
  PageResourceFactory,
  PageRouteGetLinkPropsInput,
  PageRouteHrefInput,
  PageRouteLinkComponentProps,
  PageRouteNavigation,
  PageRoutePath,
  PageRouteReference,
  PageRouteSearch,
  PageRouteTarget,
  PageSchemaParseFailure,
  PageSchemaParseResult,
  PageSchemaParseSuccess,
  PageSearchParamInput,
  PageSearchParamValue,
  PageSearchSchema,
  PageSlot,
  PageSlots,
  PageTelemetryConfig,
  RoutedPageDefinition,
  RuntimeFormState,
  SchemaInput,
  SchemaOutput,
  Simplify,
  UnknownRecord,
} from '../mod.ts';
import type {
  AnyDefinePageTypeState,
  DefinePageBuilder,
  DefinePageBuildOptions,
  DefinePageBuildResult,
  DefinePageBuildResultFor,
  DefinePageContract,
  DefinePageDefinition,
  DefinePageDefinitionFor,
  DefinePageFormConfigFor,
  DefinePageHandlers,
  DefinePageHandlersFor,
  DefinePageHeaderResolverFor,
  DefinePageHooks,
  DefinePageLayerConfig,
  DefinePageLayerConfigFor,
  DefinePageLayerContext,
  DefinePageLayerContextBase,
  DefinePageLayerDataOf,
  DefinePageLayerLoader,
  DefinePageLayerLoaderFor,
  DefinePageLayerMap,
  DefinePageLayerProps,
  DefinePageLayout,
  DefinePageLayoutContext,
  DefinePageLayoutContextBase,
  DefinePageLayoutFor,
  DefinePageMetaResolver,
  DefinePageMetaResolverFor,
  DefinePageMethod,
  DefinePageMethodHandler,
  DefinePageMethodHandlerFor,
  DefinePageRenderContext,
  DefinePageRequestContext,
  DefinePageResourceFactory,
  DefinePageResourceFactoryFor,
  DefinePageResourcesOf,
  DefinePageRootBuilder,
  DefinePageRootTypeState,
  DefinePageRoutedDefinition,
  DefinePageRoutedDefinitionFor,
  DefinePageRouteFor,
  DefinePageRouteNav,
  DefinePageRouteNavFor,
  DefinePageRuntimeContextBase,
  DefinePageSearchOf,
  DefinePageSlot,
  DefinePageSlots,
  DefinePageSlotsFor,
  DefinePageStateOf,
  DefinePageTelemetryConfig,
  DefinePageTypeCarrier,
  DefinePageTypeState,
  DefinePageWithForm,
  DefinePageWithLayer,
  DefinePageWithParams,
  DefinePageWithPathParams,
  DefinePageWithResource,
  DefinePageWithResources,
  DefinePageWithRoute,
  DefinePageWithSearchParams,
  EmptyRecord as DefinePageEmptyRecord,
  HasPathParams,
  InferDefinePageContext,
  InferDefinePageHasRoute,
  InferDefinePageLayerData,
  InferDefinePageLayerLoaderProps as DefinePageInferLayerLoaderProps,
  InferDefinePageLayerProps,
  InferDefinePageLayoutContext,
  InferDefinePageLayoutProps,
  InferDefinePageLayoutSlots,
  InferDefinePagePath,
  InferDefinePageResource,
  InferDefinePageResources,
  InferDefinePageSearch,
  InferDefinePageState,
  InferDefinePageTypes,
  InferSchemaOutput,
  NormalizeDefinePageTypeState,
  PaginationSearchSchemaOptions,
  PaginationSearchState,
  PathParamInput,
  PathParamSchema,
  ResolveDefinePageLayerLoaderOutput,
  ResolveSchemaOutput,
  SchemaLike,
  SchemaParseFailure,
  SchemaParseResult,
  SchemaParseSuccess,
  SearchParamInput,
  SearchParamSchema,
  SearchParamValue,
  Simplify as DefinePageSimplify,
  UnknownRecord as DefinePageUnknownRecord,
  ValidatedRouteHref,
} from './mod.ts';
import type {
  ResolveDefinePageLayerLoaderOutput as TypesResolveDefinePageLayerLoaderOutput,
} from './types.ts';

type AnyLoader = () => Promise<{ readonly id: string }>;
type AnyTypes = DefinePageRootTypeState;
type AnyTarget = {
  readonly routePattern: string;
  readonly $types?: {
    readonly path: object;
    readonly search: object;
  };
};
type AnyDefinition = DefinePageDefinitionFor<AnyTypes>;
type AnyLayerMap = DefinePageLayerMap;
type AnyRenderable = PageRenderable;
type AnyFormState = RuntimeFormState<Record<string, string>>;
type BuildersModule = typeof import('../mod.ts');
type DefinePageModule = typeof import('./mod.ts');

type BuildersSurfaceSnapshot = [
  ComponentLike<{ readonly children?: AnyRenderable }>,
  DefinedPartialRoute<object>,
  DefinePartialOptions<object, object>,
  DefineStatsPartialOptions<object, object>,
  EmptyRecord,
  InferDefinePageLayerLoaderProps<AnyLoader>,
  PageBuildOptions,
  PageBuilder,
  PageCacheEntry<string>,
  PageContext,
  PageDeferPolicyInput,
  PageDeferPolicyProfile,
  PageDefinition,
  PageErrorPrimitives,
  PageFormConfig<Record<string, string>, UnknownRecord>,
  PageFormHandlerContext<Record<string, string>>,
  PageHandlers,
  PageHeaderResolver,
  PageHooks<PageDefinition>,
  PageLayerConfig,
  PageLayerDelivery,
  PageLayerLoader,
  PageLayerMap,
  PageLayout,
  PageLayoutContext,
  PageLinkProps,
  PageMetaDescriptor,
  PageMetaResolver,
  PageMethod,
  PageMethodHandler,
  PagePairedRouteHrefInput<EmptyRecord, EmptyRecord, EmptyRecord, EmptyRecord>,
  PagePairedRouteTarget,
  PagePartialLinkProps,
  PagePathParamInput,
  PagePathSchema,
  PageRenderContext,
  PageRenderable,
  PageRequestContext,
  PageResourceFactory,
  PageRouteGetLinkPropsInput<EmptyRecord, EmptyRecord>,
  PageRouteHrefInput<EmptyRecord, EmptyRecord>,
  PageRouteLinkComponentProps<EmptyRecord, EmptyRecord>,
  PageRouteNavigation,
  PageRoutePath<PageRouteTarget>,
  PageRouteReference,
  PageRouteSearch<PageRouteTarget>,
  PageRouteTarget,
  PageSchemaParseFailure,
  PageSchemaParseResult<string>,
  PageSchemaParseSuccess<string>,
  PageSearchParamInput,
  PageSearchParamValue,
  PageSearchSchema,
  SchemaInput<PagePathSchema, EmptyRecord>,
  PageSlot<PageLayerMap[string]>,
  PageSlots<PageLayerMap>,
  PageTelemetryConfig,
  RoutedPageDefinition,
  RuntimeFormState<Record<string, string>>,
  SchemaOutput<PagePathSchema, EmptyRecord>,
  Simplify<{ readonly value: string }>,
  UnknownRecord,
];

type DefinePageSurfaceSnapshot = [
  AnyDefinePageTypeState,
  DefinePageBuildOptions,
  DefinePageBuildResult<{ readonly routePattern: string }, AnyTypes>,
  DefinePageBuildResultFor<{ readonly routePattern: string }, AnyTypes>,
  DefinePageBuilder<AnyTypes, false>,
  DefinePageContract<AnyTypes>,
  DefinePageDefinition,
  DefinePageDefinitionFor<AnyTypes>,
  DefinePageFormConfigFor<AnyTypes, false, never, string>,
  DefinePageHandlers,
  DefinePageHandlersFor<AnyTypes>,
  DefinePageHeaderResolverFor<AnyTypes>,
  DefinePageHooks<AnyDefinition>,
  DefinePageLayerConfig,
  DefinePageLayerConfigFor<AnyTypes, AnyLayerMap[string], false>,
  DefinePageLayerContext,
  DefinePageLayerContextBase<AnyTypes, false>,
  DefinePageLayerDataOf<AnyTypes>,
  DefinePageLayerLoader,
  DefinePageLayerLoaderFor<AnyTypes, AnyLayerMap[string], false>,
  DefinePageLayerMap,
  DefinePageLayerProps,
  DefinePageLayout,
  DefinePageLayoutContext,
  DefinePageLayoutContextBase<AnyTypes, false>,
  DefinePageLayoutFor<AnyTypes, false>,
  DefinePageMetaResolver,
  DefinePageMetaResolverFor<AnyTypes, false>,
  DefinePageMethod,
  DefinePageMethodHandler,
  DefinePageMethodHandlerFor<AnyTypes, false>,
  DefinePageRenderContext,
  DefinePageRequestContext,
  DefinePageResourceFactory,
  DefinePageResourceFactoryFor<AnyTypes, string, false>,
  DefinePageResourcesOf<AnyTypes>,
  DefinePageRootBuilder,
  DefinePageRootTypeState,
  DefinePageRouteFor<AnyTypes>,
  DefinePageRouteNav,
  DefinePageRouteNavFor<AnyTypes>,
  DefinePageRoutedDefinition,
  DefinePageRoutedDefinitionFor<AnyTypes>,
  DefinePageRuntimeContextBase<AnyTypes, false>,
  DefinePageSearchOf<AnyTypes>,
  DefinePageSlot<AnyLayerMap[string]>,
  DefinePageSlots<AnyLayerMap>,
  DefinePageSlotsFor<AnyTypes>,
  DefinePageStateOf<AnyTypes>,
  DefinePageTelemetryConfig,
  DefinePageTypeCarrier,
  DefinePageTypeState,
  DefinePageWithForm<AnyTypes, 'form', never>,
  DefinePageWithLayer<AnyTypes, 'layer', AnyLayerMap[string]>,
  DefinePageWithParams<AnyTypes, PathParamSchema, SearchParamSchema>,
  DefinePageWithPathParams<AnyTypes, PathParamSchema>,
  DefinePageWithResource<AnyTypes, 'resource', string>,
  DefinePageWithResources<AnyTypes, { readonly resource: () => string }>,
  DefinePageWithRoute<AnyTypes, AnyTarget>,
  DefinePageWithSearchParams<AnyTypes, SearchParamSchema>,
  DefinePageEmptyRecord,
  HasPathParams<DefinePageEmptyRecord>,
  InferDefinePageContext<AnyDefinition>,
  InferDefinePageHasRoute<AnyDefinition>,
  InferDefinePageLayerData<AnyDefinition>,
  DefinePageInferLayerLoaderProps<AnyLoader>,
  InferDefinePageLayerProps<AnyDefinition, never>,
  InferDefinePageLayoutContext<AnyDefinition>,
  InferDefinePageLayoutProps<AnyDefinition>,
  InferDefinePageLayoutSlots<AnyDefinition>,
  InferDefinePagePath<AnyDefinition>,
  InferDefinePageResource<AnyDefinition, never>,
  InferDefinePageResources<AnyDefinition>,
  InferDefinePageSearch<AnyDefinition>,
  InferDefinePageState<AnyDefinition>,
  InferDefinePageTypes<AnyDefinition>,
  InferSchemaOutput<PathParamSchema>,
  NormalizeDefinePageTypeState,
  PaginationSearchSchemaOptions,
  PaginationSearchState,
  PathParamInput,
  PathParamSchema,
  ResolveDefinePageLayerLoaderOutput<Awaited<ReturnType<AnyLoader>>>,
  ResolveSchemaOutput<DefinePageEmptyRecord, PathParamSchema>,
  SchemaLike,
  SchemaParseFailure,
  SchemaParseResult<string>,
  SchemaParseSuccess<string>,
  SearchParamInput,
  SearchParamSchema,
  SearchParamValue,
  DefinePageSimplify<{ readonly value: string }>,
  DefinePageUnknownRecord,
  ValidatedRouteHref,
  TypesResolveDefinePageLayerLoaderOutput<Awaited<ReturnType<AnyLoader>>>,
  AnyFormState,
  BuildersSurfaceSnapshot,
];

type BuildersValueSurfaceSnapshot = [
  BuildersModule['definePage'],
  BuildersModule['definePartial'],
  BuildersModule['defineStatsPartial'],
];

type DefinePageValueSurfaceSnapshot = [
  DefinePageModule['PaginationSearchSchema'],
  DefinePageModule['createDefinePageHooks'],
  DefinePageModule['definePage'],
  DefinePageModule['fallback'],
  DefinePageModule['paginationSearchSchema'],
  DefinePageModule['searchParamsToInput'],
  DefinePageModule['usePagePath'],
  DefinePageModule['usePageRoute'],
  DefinePageModule['usePageSearch'],
];

Deno.test('type surface snapshot compiles', () => {
  const snapshot:
    | BuildersValueSurfaceSnapshot
    | DefinePageValueSurfaceSnapshot
    | DefinePageSurfaceSnapshot
    | null = null;
  assertEquals(snapshot, null);
});
