/** Canonical page transport shared by the repository generators, never a second stored corpus. */
import {
  agentDocsFullCorpus,
  type AgentDocsPage,
  decodeAgentDocsPages,
} from '../../../packages/cli/src/kernel/assets/agent-docs-transport.ts';

export const AGENT_DOCS_PAGE_CARRIER =
  'packages/cli/src/kernel/assets/agent-docs-prose.generated.ts';

/** Render sorted pages with local integrity metadata; aggregates are derived by consumers. */
export async function renderAgentDocsPages(
  files: Readonly<Record<string, string>>,
  existingSource: string = '',
): Promise<string> {
  const existing = new Map<string, AgentDocsPage>();
  if (existingSource) {
    for (const row of parseAgentDocsPages(existingSource)) {
      // Integrity is checked before reuse; corrupt rows are regenerated rather than preserved.
      try {
        const decoded = await decodeAgentDocsPages([row]);
        if (decoded[row[0]] === files[row[0]]) existing.set(row[0], row);
      } catch { /* Regenerate a corrupt row. */ }
    }
  }
  const rows: string[] = [];
  for (const path of Object.keys(files).sort()) {
    if (path === 'llms-full.txt') continue;
    const previous = existing.get(path);
    if (previous) {
      rows.push(`  ${JSON.stringify(previous)},`);
      continue;
    }
    const bytes = new TextEncoder().encode(files[path]);
    const compressed = new Uint8Array(
      await new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('gzip')))
        .arrayBuffer(),
    );
    const hash = new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)).toHex();
    rows.push(`  ${JSON.stringify([path, compressed.toBase64(), hash, bytes.byteLength])},`);
  }
  return `// @generated by .llm/tools/docs/build-agent-docs-bundle.ts\n// Do not edit by hand. Run \`deno task gen:agent-docs-prose\`.\nimport type { AgentDocsPage } from './agent-docs-transport.ts';\n\n/** Independently compressed source pages; one sorted entry per line. */\n// deno-fmt-ignore\nexport const EMBEDDED_AGENT_DOCS_PAGES: readonly AgentDocsPage[] = [\n${
    rows.join('\n\n')
  }\n];\n`;
}

/** Read generated rows without evaluating modules or retaining a stale module-loader snapshot. */
export async function readAgentDocsPages(
  path: string | URL,
  version: string,
): Promise<Record<string, string>> {
  const source = await Deno.readTextFile(path);
  const rows = parseAgentDocsPages(source);
  const files = await decodeAgentDocsPages(rows);
  files['llms-full.txt'] = agentDocsFullCorpus(files, version);
  return files;
}

/** Parse revision text using the same transport contract as filesystem generation. */
export function parseAgentDocsPages(source: string): readonly AgentDocsPage[] {
  const rows = source.split('\n').filter((line) => line.startsWith('  [')).map((line) =>
    JSON.parse(line.trim().replace(/,$/, '')) as AgentDocsPage
  );
  if (!rows.length) throw new Error('Agent docs page carrier is empty');
  return rows;
}
