import { assert, assertEquals, assertStringIncludes, assertThrows } from '@std/assert';
import { fromFileUrl, join, toFileUrl } from '@std/path';
import { renderTemplate } from '../../../packages/cli/src/kernel/adapters/scaffold/template-adapter.ts';
import { readTemplateAssetSync } from '../../../packages/cli/src/kernel/adapters/templates/template-asset.ts';
import { TEMPLATE_KEYS } from '../../../packages/cli/src/kernel/assets/manifest.ts';
import {
  APP_ROUTER_TEMPLATE_VARS,
  DOCUMENTED_READER_ROUTES,
  materializeAppRouterSupport,
  shippedAppRouteAssets,
} from './app-router-support.ts';
import { resolveWorkspaceSurface } from './snippet-workspace.ts';

const repositoryRoot = fromFileUrl(new URL('../../../', import.meta.url));

/** Type-check a probe that consumes the materialized router the way README fences do. */
async function checkRouterProbe(tempRoot: string, routerPath: string): Promise<Deno.CommandOutput> {
  const probePath = join(tempRoot, 'probe.ts');
  await Deno.writeTextFile(
    probePath,
    `import { appRouter, appRoutes, routes } from '${toFileUrl(routerPath).href}';
export const partial = routes.partials.orders.$id.$route;
export const order = appRoutes.order;
export const patterns = appRouter.routePatterns;
`,
  );
  const workspace = await resolveWorkspaceSurface(repositoryRoot);
  const configPath = join(tempRoot, 'deno.json');
  await Deno.writeTextFile(
    configPath,
    JSON.stringify({
      compilerOptions: { strict: true, jsx: 'precompile', jsxImportSource: 'preact' },
      imports: workspace.imports,
      catalog: workspace.catalog,
    }),
  );
  // A private lock copy keeps the tracked root deno.lock untouched, as the snippet compiler does.
  const lockPath = join(tempRoot, 'deno.lock');
  await Deno.copyFile(join(repositoryRoot, 'deno.lock'), lockPath);
  return await new Deno.Command(Deno.execPath(), {
    cwd: repositoryRoot,
    args: ['check', '--unstable-kv', '--lock', lockPath, '--config', configPath, probePath],
    stdout: 'piped',
    stderr: 'piped',
  }).output();
}

async function withTempRoot(run: (tempRoot: string) => Promise<void>): Promise<void> {
  const tempRoot = await Deno.makeTempDir({ prefix: 'netscript-app-router-support-' });
  try {
    await run(tempRoot);
  } finally {
    await Deno.remove(tempRoot, { recursive: true });
  }
}

Deno.test('the support router is byte-identical to the scaffold router template render', async () => {
  await withTempRoot(async (tempRoot) => {
    const routerPath = await materializeAppRouterSupport(join(tempRoot, 'app'));

    assertEquals(
      await Deno.readTextFile(routerPath),
      renderTemplate(readTemplateAssetSync(TEMPLATE_KEYS.appRouter), {
        ...APP_ROUTER_TEMPLATE_VARS,
      }),
    );
  });
});

Deno.test('every router template placeholder is supplied, and nothing else', () => {
  // The scaffold writer fills these per app; if the template gains or drops one, this fails before
  // a stale variable set can render a router the scaffold would never emit.
  const placeholders = [
    ...readTemplateAssetSync(TEMPLATE_KEYS.appRouter).matchAll(/\{\{\s*(\w+)/g),
  ].map((match) => match[1]);

  assertEquals([...new Set(placeholders)].sort(), Object.keys(APP_ROUTER_TEMPLATE_VARS).sort());
  assertThrows(
    () => renderTemplate(readTemplateAssetSync(TEMPLATE_KEYS.appRouter), {}),
    Error,
    'is not defined in context',
  );
});

Deno.test('route modules are generated from the shipped route assets, not restated', async () => {
  await withTempRoot(async (tempRoot) => {
    const appRoot = join(tempRoot, 'app');
    await materializeAppRouterSupport(appRoot);
    const generatedRoutes = await Deno.readTextFile(join(appRoot, '.generated/routes.ts'));

    assert(shippedAppRouteAssets().includes(TEMPLATE_KEYS.appRouter) === false);
    assert(shippedAppRouteAssets().includes('app/routes/examples/orders/[id].tsx.template'));
    assertStringIncludes(generatedRoutes, 'auto-generated by @netscript/fresh/vite');
    assertStringIncludes(
      generatedRoutes,
      `createRouteReference(routePatterns.partials.orders.$id.$route, { id: "partials.orders.$id", kind: "partial" })`,
    );
    assertEquals(Object.keys(DOCUMENTED_READER_ROUTES), ['partials/orders/[id].tsx']);
  });
});

Deno.test('the support router type-checks for the README partial consumer', async () => {
  await withTempRoot(async (tempRoot) => {
    const routerPath = await materializeAppRouterSupport(join(tempRoot, 'app'));
    const output = await checkRouterProbe(tempRoot, routerPath);

    assertEquals(output.code, 0, new TextDecoder().decode(output.stderr));
  });
});

Deno.test('negative control: a route tree drifted from the router template fails the check', async () => {
  await withTempRoot(async (tempRoot) => {
    // Drop the scaffold's order route, which the shipped router binds as `appRoutes.order`.
    const routerPath = await materializeAppRouterSupport(join(tempRoot, 'app'), {
      routeAssets: shippedAppRouteAssets().filter((asset) => !asset.includes('/orders/')),
    });
    const output = await checkRouterProbe(tempRoot, routerPath);
    const diagnostics = new TextDecoder().decode(output.stderr);

    assert(output.code !== 0, 'expected the drifted router to fail type-checking');
    assertStringIncludes(diagnostics, "Property 'orders' does not exist");
  });
});
