import { dirname, fromFileUrl } from '@std/path';
import type { JsdocTypeErrorExample } from './jsdoc-example-contract.ts';
import { compileJsdocExamples } from './jsdoc-example-compiler.ts';
import {
  analyzeJsdocExamples,
  formatJsdocExampleCensus,
  jsdocExampleRatchetFailures,
} from './jsdoc-example-policy.ts';

const repositoryRoot = dirname(dirname(dirname(dirname(fromFileUrl(import.meta.url)))));

function ownerLabel(example: JsdocTypeErrorExample): string {
  const owner = example.owner;
  if (owner.kind === 'module') return `module ${owner.memberName}`;
  return `symbol ${owner.symbol ?? '(unknown)'}${
    owner.publicSpecifier ? ` (${owner.publicSpecifier})` : ''
  }`;
}

/** Render the classifier-owned enforced type errors without reclassifying them. */
export function formatTypeErrorsMarkdown(examples: readonly JsdocTypeErrorExample[]): string {
  const sections: Array<{
    failureClass: JsdocTypeErrorExample['failureClass'];
    title: string;
  }> = [
    { failureClass: 'typeError', title: 'Published-API type-error class' },
  ];
  const lines = [
    '# JSDoc example type errors',
    '',
    '> Generated by the gate classifier. Every entry is an enforced failure, including invalid',
    '> syntax and usage that disagrees with the published API signature.',
    '',
  ];
  for (const section of sections) {
    const selected = examples.filter((example) => example.failureClass === section.failureClass);
    lines.push(`## ${section.title} — ${selected.length} examples`, '');
    for (const example of selected) {
      const codes = example.tsCodes.map((code) => `TS${code}`).join(', ');
      lines.push(
        `- ${example.owner.sourcePath} · ${
          ownerLabel(example)
        } · example ${example.exampleOrdinal} · fence ${example.fenceOrdinal} · ${codes}`,
      );
    }
    lines.push('');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

function typeErrorOutputPath(args: readonly string[]): string | undefined {
  const index = args.indexOf('--type-error-output');
  if (index === -1) return undefined;
  const path = args[index + 1];
  if (!path) throw new Error('--type-error-output requires a path');
  return path;
}

/** Check the published JSDoc example corpus without executing example code. */
export async function main(args: readonly string[] = Deno.args): Promise<number> {
  const analysis = await analyzeJsdocExamples(repositoryRoot);
  const result = await compileJsdocExamples(analysis, repositoryRoot);
  const ratchetFailures = jsdocExampleRatchetFailures(analysis.census);
  const exitCode = result.code === 0 && ratchetFailures.length === 0 ? 0 : 1;
  const census = {
    ...analysis.census,
    failures: result.enforcedFailureCount,
  };
  console.log(formatJsdocExampleCensus(census, exitCode === 0 ? 'PASS' : 'FAIL'));
  console.log(`enforcedFailureCensus=${
    JSON.stringify({
      badSpecifier: result.failureCensus.badSpecifier,
      typeError: result.failureCensus.typeError,
      unfenced: result.failureCensus.unfenced,
      malformed: result.failureCensus.malformed,
      unboundName: result.failureCensus.unboundName,
    })
  }`);
  for (const failure of ratchetFailures) console.error(`ratchet failure: ${failure}`);
  for (const block of analysis.exemptions) {
    console.log(
      `exemption=${block.owner.sourcePath}:${block.openingLine} reason=${block.exemptionReason}`,
    );
  }
  const outputPath = typeErrorOutputPath(args);
  if (outputPath) {
    await Deno.mkdir(dirname(outputPath), { recursive: true });
    await Deno.writeTextFile(outputPath, formatTypeErrorsMarkdown(result.typeErrorExamples));
    console.log(`typeErrorExamples=${outputPath}`);
  }
  if (exitCode !== 0 && result.diagnostics.trim()) console.error(result.diagnostics.trimEnd());
  return exitCode;
}

if (import.meta.main) {
  try {
    Deno.exit(await main());
  } catch (error) {
    console.error(
      `jsdoc examples: FAIL ${error instanceof Error ? error.message : String(error)}`,
    );
    Deno.exit(1);
  }
}
